// Fichier généré par tools/build-pack.mjs depuis research/presidentielle-2027 : ne pas modifier à la main.
// Séries vidéo reprises de « choisir-2027 » (research/presidentielle-2027/reuse.json) : thème de la série → thème d'ici,
// question de « choisir-2027 » → question identique d'ici. Une série absente de « topics » n'est pas montrée.

export const videoScope: { topics: Record<string, string>; questions: Record<string, string> } = {
  "topics": {},
  "questions": {
    "retraites-1": "retraites-1",
    "fiscalite-2": "finances_publiques-1",
    "industrie_economie-3": "industrie_economie-1",
    "travail_salaires-1": "travail_salaires-1",
    "fiscalite-1": "fiscalite-1",
    "travail_salaires-x1": "travail_salaires-2",
    "travail_salaires-4": "travail_salaires-3",
    "travail_salaires-3": "travail_salaires-4",
    "industrie_economie-2": "industrie_economie-2",
    "retraites-2": "retraites-3",
    "sante-1": "sante-1",
    "solidarites-x1": "solidarites-1",
    "logement-2": "logement-1",
    "sante-2": "sante-2",
    "sante-x1": "sante-4",
    "sante-3": "sante-5",
    "logement-1": "logement-2",
    "egalite-x1": "egalite-2",
    "education-2": "education-2",
    "education-x1": "education-4",
    "societe-1": "societe-2",
    "numerique-1": "numerique-1",
    "numerique-2": "numerique-2",
    "numerique-3": "numerique-3",
    "ecologie_energie-1": "ecologie_energie-1",
    "ecologie_energie-2": "ecologie_energie-2",
    "territoires-1": "territoires-1",
    "ecologie_energie-3": "ecologie_energie-3",
    "ecologie_energie-5": "ecologie_energie-4",
    "ecologie_energie-x1": "ecologie_energie-5",
    "ecologie_energie-x2": "ecologie_energie-6",
    "ecologie_energie-6": "ecologie_energie-7",
    "territoires-x2": "territoires-2",
    "securite_justice-3": "securite_justice-1",
    "securite_justice-1": "securite_justice-2",
    "securite_justice-2": "securite_justice-3",
    "immigration-1": "immigration-1",
    "immigration-2": "immigration-6",
    "europe-1": "europe-1",
    "europe-2": "europe-2",
    "europe-3": "europe-3",
    "international_defense-1": "ukraine_russie-1",
    "international_defense-4": "proche_orient-1",
    "international_defense-5": "defense-3",
    "international_defense-3": "defense-4",
    "institutions-1": "institutions-1",
    "institutions-2": "institutions-3",
    "laicite_republique-1": "laicite_republique-1",
    "laicite_republique-2": "laicite_republique-2"
  }
}
