// Série « Impôts et budget » (famille « Travail et économie ») : l'introduction, puis cinq approfondissements
// (déficit et dette, grandes fortunes, héritages, capital et bénéfices, affectation d'une recette nouvelle).
// Tous les chiffres viennent des fiches du thème (research/choisir-2027/explainers.json, questions fiscalite-1,
// fiscalite-2, fiscalite-3, fiscalite-x1) et de leurs graphiques (explainer-charts.json). Règles d'écriture :
// ../GUIDE-SERIES.md ; planches : ../pistes/planches/fiscalite.tsx.
// Ne pas toucher aux identifiants ni aux textes dits sans raison : changer un « say » ou un « spoken », c'est
// devoir réenregistrer la voix du passage.
// Datée : dette publique à fin juin 2026 (Insee, 29 septembre 2026) ; prévisions de déficit du Gouvernement pour
// 2026 et 2027 et avis du Haut Conseil des finances publiques du 25 septembre 2026 (projets de lois de finances
// pour 2027). À revoir après le vote du budget 2027 et la publication de la dette du troisième trimestre 2026.

import type { VideoSeries } from '../types'

/** Les sources communes à plusieurs vidéos, copiées des fiches */
const INSEE_APU = {
  title: 'Le compte des administrations publiques en 2025 (Insee Première n° 2106)',
  url: 'https://www.insee.fr/fr/statistiques/8997691',
  publisher: 'Insee',
  date: '2026-05-29',
}

const COMITE_CAPITAL = {
  title: 'Comité d’évaluation des réformes de la fiscalité du capital – Rapport final (avis du comité)',
  url: 'https://www.strategie-plan.gouv.fr/files/files/Publications/Rapport/fs-2023-rapport-isf-quatrieme_rapport_complet_17octobre_avis_0.pdf',
  publisher: 'France Stratégie',
  date: '2023-10',
}

const EXECUTION_2025 = {
  title: 'Exécution budgétaire 2025 des recettes fiscales nettes de l’État et des remboursements et dégrèvements',
  url: 'https://www.budget.gouv.fr/documentation/file-download/33360',
  publisher: 'Direction du Budget, DG Trésor, DGFiP (budget.gouv.fr)',
  date: '2026-02',
}

const RALFSS_2026 = {
  title: 'La sécurité sociale 2026 – Rapport sur l’application des lois de financement de la sécurité sociale',
  url: 'https://www.ccomptes.fr/sites/default/files/2026-05/20260527-RALFSS-2026_0.pdf',
  publisher: 'Cour des comptes',
  date: '2026-05-27',
}

export const FISCALITE: VideoSeries = {
  topicId: 'fiscalite',
  familyId: 'economie',
  label: 'Impôts et budget',
  videos: [
    {
      id: 'impots-intro',
      kind: 'intro',
      questionIds: ['fiscalite-2', 'fiscalite-1', 'fiscalite-x1', 'fiscalite-3'],
      title: 'Impôts et budget, l’essentiel',
      short: 'Introduction',
      register: 'vous',
      segments: [
        {
          id: 'impots-intro-01',
          say: 'Impôts, cotisations sociales\u00a0: une part de ce que vous gagnez finance l’action publique. Où va cet argent, et suffit-il\u202f?',
          visual: 'hook',
          draw: 'Une personne au trait\u202f; quelques pièces partent d’elle vers un bâtiment public à colonnes, que surmonte un point d’interrogation.',
          emphasis: ['Où va cet argent', 'suffit-il'],
        },
        {
          id: 'impots-intro-02',
          say: 'En 2025, l’ensemble des administrations publiques a dépensé 1\u202f714,2\u00a0milliards d’euros. D’abord en prestations sociales\u00a0: retraites, chômage, remboursements médicaux.',
          spoken: 'En deux mille vingt-cinq, l’ensemble des administrations publiques a dépensé mille sept cent quatorze virgule deux milliards d’euros. D’abord en prestations sociales : retraites, chômage, remboursements médicaux.',
          visual: 'figure',
          draw: 'Quatre barres horizontales depuis zéro, à la même échelle\u00a0: prestations sociales, fonctionnement, subventions et autres transferts, investissement\u202f; la première au bleu bille.',
          alt: 'Quatre barres à la même échelle, en milliards d’euros\u00a0: prestations sociales, 771\u202f; fonctionnement, 548,8\u202f; subventions et autres transferts, 192,1\u202f; investissement, 132,2.',
          emphasis: ['1\u202f714,2\u00a0milliards', 'prestations sociales'],
          figure: {
            value: '1\u202f714,2\u00a0Md€',
            label: 'Dépenses de l’ensemble des administrations publiques, dont 771,0\u00a0Md€ de prestations sociales (retraites, chômage, remboursements médicaux…), 548,8\u00a0Md€ de fonctionnement (dont 370,0\u00a0Md€ de rémunérations des agents publics), 192,1\u00a0Md€ de subventions et autres transferts, et 132,2\u00a0Md€ d’investissement',
            date: '2025',
            sourceIndex: 0,
          },
          chart: {
            kind: 'compare',
            unit: 'Md€',
            items: [
              { label: 'Prestations sociales', value: 771 },
              { label: 'Fonctionnement', value: 548.8 },
              { label: 'Subventions et autres transferts', value: 192.1 },
              { label: 'Investissement', value: 132.2 },
            ],
          },
        },
        {
          id: 'impots-intro-03',
          say: 'Ces dépenses valent 57,3\u00a0% du PIB, la richesse produite en un an. Les recettes, 52,2\u00a0%. L’écart, c’est le déficit.',
          spoken: 'Ces dépenses valent cinquante-sept virgule trois pour cent du P.I.B., la richesse produite en un an. Les recettes, cinquante-deux virgule deux pour cent. L’écart, c’est le déficit.',
          visual: 'compare',
          draw: 'Deux barres depuis zéro, à la même échelle\u00a0: les dépenses et les recettes\u202f; au bout des recettes, l’écart qui manque, au bleu bille, marqué «\u00a0le déficit\u00a0».',
          alt: 'Deux barres à la même échelle, en part du PIB\u00a0: les dépenses et les recettes\u202f; l’écart entre elles est marqué.',
          emphasis: ['57,3\u00a0%', '52,2\u00a0%', 'le déficit'],
          figure: {
            value: '57,3\u00a0% du PIB',
            label: 'Dépenses publiques en 2025\u202f; recettes publiques\u00a0: 52,2\u00a0% du PIB, dont 43,6\u00a0% d’impôts et de cotisations sociales (les «\u00a0prélèvements obligatoires\u00a0»)',
            date: '2025',
            sourceIndex: 0,
          },
        },
        {
          id: 'impots-intro-04',
          say: 'Ces recettes sont surtout des impôts et des cotisations sociales, les «\u00a0prélèvements obligatoires\u00a0»\u00a0: 43,6\u00a0% du PIB en 2025.',
          spoken: 'Ces recettes sont surtout des impôts et des cotisations sociales, les « prélèvements obligatoires » : quarante-trois virgule six pour cent du P.I.B. en deux mille vingt-cinq.',
          visual: 'figure',
          draw: 'La barre des recettes reprise du passage précédent\u202f; sa plus grande part se hachure au bleu bille\u00a0: les impôts et les cotisations.',
          alt: 'La barre des recettes publiques, 52,2\u00a0% du PIB, dont la part des prélèvements obligatoires.',
          emphasis: ['prélèvements obligatoires', '43,6\u00a0%'],
          figure: {
            value: '43,6\u00a0% du PIB',
            label: 'Prélèvements obligatoires (impôts et cotisations sociales) en 2025, sur 52,2\u00a0% du PIB de recettes publiques',
            date: '2025',
            sourceIndex: 0,
          },
        },
        {
          id: 'impots-intro-05',
          say: 'Et chaque déficit s’ajoute à la dette. Fin juin 2026, elle atteint 3\u202f595,5\u00a0milliards d’euros. C’est 119\u00a0% du PIB, plus d’une année de richesse produite.',
          spoken: 'Et chaque déficit s’ajoute à la dette. Fin juin deux mille vingt-six, elle atteint trois mille cinq cent quatre-vingt-quinze virgule cinq milliards d’euros. C’est cent dix-neuf pour cent du P.I.B., plus d’une année de richesse produite.',
          visual: 'figure',
          draw: 'Deux disques au trait, chacun une année de richesse produite\u00a0: le premier entièrement hachuré au bleu bille, le second sur un peu moins d’un cinquième.',
          alt: 'Un disque plein, une année de PIB, et une part d’un second disque\u00a0: 119\u00a0% du PIB.',
          emphasis: ['119\u00a0%', 'plus d’une année'],
          figure: {
            value: '119,0\u00a0% du PIB',
            label: 'Dette publique selon la définition des règles européennes («\u00a0au sens de Maastricht\u00a0»), soit 3\u202f595,5\u00a0Md€',
            date: 'fin juin 2026',
            sourceIndex: 1,
          },
        },
        {
          id: 'impots-intro-06',
          say: 'Alors, cinq questions se posent. Que faire face à la dette\u202f? Comment imposer les grandes fortunes\u202f? Et les héritages\u202f? Et le capital, les bénéfices\u202f? À quoi affecter une recette nouvelle\u202f?',
          visual: 'question',
          draw: 'Cinq pictogrammes en grille, dessinés l’un après l’autre\u00a0: une pile de pièces, un immeuble, une clé, une courbe de Bourse, une cible.',
          emphasis: ['la dette', 'grandes fortunes', 'héritages'],
        },
        {
          id: 'impots-intro-07',
          say: 'Ce sont les cinq sujets des vidéos qui suivent.',
          visual: 'outro',
          draw: 'Les cinq pictogrammes se rangent en file, comme les chapitres d’un carnet.',
        },
      ],
      sources: [
        INSEE_APU,
        {
          title: 'À la fin du deuxième trimestre 2026, le ratio de dette publique s’établit à 119,0\u00a0% du PIB (Informations rapides n° 239)',
          url: 'https://www.insee.fr/fr/statistiques/9053525',
          publisher: 'Insee',
          date: '2026-09-29',
        },
      ],
    },
    {
      id: 'impots-dette',
      kind: 'deep',
      questionIds: ['fiscalite-2'],
      title: 'Que faire face à la dette publique\u202f?',
      short: 'Déficit et dette',
      register: 'vous',
      segments: [
        {
          id: 'impots-dette-01',
          say: 'Quand les recettes publiques ne couvrent pas les dépenses, on emprunte la différence. Année après année, ces emprunts forment la dette. Comment y faire face\u202f?',
          visual: 'hook',
          draw: 'Deux colonnes, recettes et dépenses\u202f; ce qui manque aux recettes, emprunté, va s’empiler en briques sur une colonne marquée «\u00a0la dette\u00a0».',
          alt: 'Deux colonnes, les recettes et les dépenses\u00a0; la différence empruntée s’empile, année après année.',
          emphasis: ['on emprunte', 'la dette'],
        },
        {
          id: 'impots-dette-02',
          say: 'Et la dette a un coût\u00a0: 64,7\u00a0milliards d’euros d’intérêts en 2025, pour l’ensemble des administrations publiques. C’est 11,2\u00a0% de plus qu’en 2024.',
          spoken: 'Et la dette a un coût : soixante-quatre virgule sept milliards d’euros d’intérêts en deux mille vingt-cinq, pour l’ensemble des administrations publiques. C’est onze virgule deux pour cent de plus qu’en deux mille vingt-quatre.',
          visual: 'figure',
          draw: 'Deux colonnes de pièces depuis zéro, 2024 et 2025, la seconde plus haute de 11,2\u00a0%\u202f; la hausse marquée d’une accolade au bleu bille.',
          alt: 'Deux colonnes à la même échelle, les intérêts de 2024 et de 2025\u00a0; la hausse de 11,2\u00a0% est marquée.',
          emphasis: ['64,7\u00a0milliards', '11,2\u00a0%'],
          figure: {
            value: '64,7\u00a0Md€',
            label: 'Charges d’intérêts de la dette de l’ensemble des administrations publiques, en hausse de 11,2\u00a0% sur un an',
            date: '2025',
            sourceIndex: 0,
          },
        },
        {
          id: 'impots-dette-03',
          say: 'Le déficit, lui, recule\u00a0: 5,8\u00a0% du PIB en 2024, 5,1\u00a0% en 2025. Soit 152,5\u00a0milliards d’euros.',
          spoken: 'Le déficit, lui, recule : cinq virgule huit pour cent du P.I.B. en deux mille vingt-quatre, cinq virgule un pour cent en deux mille vingt-cinq. Soit cent cinquante-deux virgule cinq milliards d’euros.',
          visual: 'figure',
          draw: 'Deux colonnes depuis zéro, 2024 et 2025, la valeur écrite au-dessus de chacune.',
          alt: 'Deux colonnes à la même échelle, le déficit en part du PIB\u00a0: 5,8\u00a0% en 2024, 5,1\u00a0% en 2025.',
          emphasis: ['5,8\u00a0%', '5,1\u00a0%'],
          figure: {
            value: '5,1\u00a0% du PIB',
            label: 'Déficit public, soit 152,5\u00a0Md€ (5,8\u00a0% du PIB en 2024)',
            date: '2025',
            sourceIndex: 0,
          },
          chart: {
            kind: 'series',
            unit: '% du PIB',
            items: [
              { label: '2024', value: 5.8 },
              { label: '2025', value: 5.1 },
            ],
          },
        },
        {
          id: 'impots-dette-04',
          say: 'Depuis juillet 2024, la France fait l’objet d’une procédure européenne pour déficit excessif. Elle doit le ramener sous 3\u00a0% du PIB d’ici 2029.',
          spoken: 'Depuis juillet deux mille vingt-quatre, la France fait l’objet d’une procédure européenne pour déficit excessif. Elle doit le ramener sous trois pour cent du P.I.B. d’ici deux mille vingt-neuf.',
          visual: 'timeline',
          draw: 'Les deux colonnes du passage précédent sur une frise de 2024 à 2029\u202f; un trait pointillé au bleu bille à 3\u00a0%, et un fanion planté en 2029.',
          alt: 'Une frise des années 2024 à 2029\u00a0: les déficits de 2024 et 2025, et la limite de 3\u00a0% du PIB, à atteindre en 2029.',
          emphasis: ['3\u00a0%', '2029'],
          figure: {
            value: 'sous 3\u00a0% du PIB',
            label: 'Déficit public à atteindre d’ici 2029 dans le cadre de la procédure de l’Union européenne pour déficit excessif, ouverte en juillet 2024',
            date: '2026',
            sourceIndex: 1,
          },
        },
        {
          id: 'impots-dette-05',
          say: 'Le Gouvernement prévoit 5,4\u00a0% en 2026, puis 5\u00a0% en 2027. Le Haut Conseil des finances publiques juge un retour sous 3\u00a0% en 2029 «\u00a0très peu vraisemblable\u00a0», sauf conjoncture très favorable.',
          spoken: 'Le Gouvernement prévoit cinq virgule quatre pour cent en deux mille vingt-six, puis cinq pour cent en deux mille vingt-sept. Le Haut Conseil des finances publiques juge un retour sous trois pour cent en deux mille vingt-neuf « très peu vraisemblable », sauf conjoncture très favorable.',
          visual: 'timeline',
          draw: 'Sur la même frise, deux colonnes en pointillé, 2026 et 2027, les prévisions\u202f; près du fanion de 2029, l’appréciation du Haut Conseil entre guillemets.',
          alt: 'Sur la frise, les prévisions du Gouvernement en pointillé\u00a0: 5,4\u00a0% en 2026, 5\u00a0% en 2027\u00a0; la limite de 3\u00a0% en 2029.',
          emphasis: ['5,4\u00a0%', 'très peu vraisemblable'],
          figure: {
            value: '5,4\u00a0% du PIB',
            label: 'Déficit public prévu par le Gouvernement pour 2026, puis 5,0\u00a0% en 2027 (avis du Haut Conseil des finances publiques sur les projets de lois de finances pour 2027)',
            date: '2026',
            sourceIndex: 1,
          },
        },
        {
          id: 'impots-dette-06',
          say: 'Réduire le déficit freine la dette et ses intérêts, mais oblige à dépenser moins ou à prélever plus. Emprunter davantage évite de dépenser moins ou de prélever plus, mais alourdit la dette et ses intérêts.',
          visual: 'compare',
          draw: 'Un tableau à deux colonnes\u00a0: «\u00a0réduire le déficit\u00a0» d’un côté, «\u00a0emprunter davantage\u00a0» de l’autre\u202f; pour la dette, les dépenses et les prélèvements, une flèche qui monte, qui descend, ou un signe égal.',
          alt: 'Trois lignes, la dette, les dépenses, les prélèvements\u00a0; pour chaque choix, ce qui monte, ce qui baisse, ce qui ne bouge pas.',
          emphasis: ['Réduire le déficit', 'Emprunter davantage'],
        },
        {
          id: 'impots-dette-07',
          say: 'Alors, face à la dette, quelle stratégie, et à quel rythme\u202f?',
          visual: 'question',
          draw: 'Une pile de pièces au début d’une frise d’années, une flèche en pointillé vers un point d’interrogation.',
          emphasis: ['quelle stratégie'],
        },
      ],
      sources: [
        INSEE_APU,
        {
          title: 'Avis n° HCFP-2026-5 relatif aux projets de lois de finances et de financement de la sécurité sociale pour l’année 2027',
          url: 'https://www.hcfp.fr/sites/default/files/2026-10/Avis%20HCFP%202026-5%20-%20PLF-PLFSS%202027.pdf',
          publisher: 'Haut Conseil des finances publiques',
          date: '2026-09-25',
        },
      ],
    },
    {
      id: 'impots-fortune',
      kind: 'deep',
      questionIds: ['fiscalite-1'],
      title: 'Comment imposer les grandes fortunes\u202f?',
      short: 'Grandes fortunes',
      register: 'vous',
      segments: [
        {
          id: 'impots-fortune-01',
          say: 'Logement, épargne, placements\u00a0: ce que vous possédez forme votre patrimoine. Et les plus grandes fortunes, comment l’impôt les touche-t-il\u202f?',
          visual: 'hook',
          draw: 'Une maison, une tirelire et une courbe de Bourse réunies par une accolade\u202f; à côté, un immeuble plus grand et un point d’interrogation.',
          emphasis: ['votre patrimoine', 'les plus grandes fortunes'],
        },
        {
          id: 'impots-fortune-02',
          say: 'Les 10\u00a0% de ménages les mieux dotés détiennent 48\u00a0% du patrimoine brut, presque la moitié. Les 1\u00a0% les mieux dotés, 15\u00a0%.',
          spoken: 'Les dix pour cent de ménages les mieux dotés détiennent quarante-huit pour cent du patrimoine brut, presque la moitié. Les un pour cent les mieux dotés, quinze pour cent.',
          visual: 'figure',
          draw: 'Cent petits carrés, tout le patrimoine\u00a0: quarante-huit se teintent au bleu bille, dont quinze au bleu plein.',
          alt: 'Cent carrés pour tout le patrimoine\u00a0: 48 au bleu clair et plein, la part des 10\u00a0% les mieux dotés\u00a0; 15 au bleu plein, celle des 1\u00a0%.',
          emphasis: ['48\u00a0%', '15\u00a0%'],
          figure: {
            value: '48\u00a0%',
            label: 'Part du patrimoine brut total détenue par les 10\u00a0% de ménages les mieux dotés (France hors Mayotte, ménages en logement ordinaire). Les 1\u00a0% les mieux dotés en détiennent 15\u00a0%.',
            date: '2023-2024',
            sourceIndex: 0,
          },
          chart: { kind: 'part', value: 48, total: 100, unit: '%', whole: 'du patrimoine brut total' },
        },
        {
          id: 'impots-fortune-03',
          say: 'En 2017, l’impôt de solidarité sur la fortune, l’ISF, a rapporté 4,2\u00a0milliards d’euros. En 2018, l’impôt sur la fortune immobilière, l’IFI, l’a remplacé\u00a0: 1,29\u00a0milliard.',
          spoken: 'En deux mille dix-sept, l’impôt de solidarité sur la fortune, l’I.S.F., a rapporté quatre virgule deux milliards d’euros. En deux mille dix-huit, l’impôt sur la fortune immobilière, l’I.F.I., l’a remplacé : un virgule vingt-neuf milliard.',
          visual: 'compare',
          draw: 'Deux barres depuis zéro, à la même échelle\u00a0: les recettes de l’ISF en 2017, celles de l’IFI en 2018.',
          alt: 'Deux barres à la même échelle\u00a0: recettes de l’ISF en 2017, recettes de l’IFI en 2018.',
          emphasis: ['4,2\u00a0milliards', '1,29\u00a0milliard'],
          figure: {
            value: '4,2\u00a0Md€',
            label: 'Recettes de l’impôt de solidarité sur la fortune (ISF) en 2017, sa dernière année. L’IFI, qui l’a remplacé, a rapporté 1,29\u00a0Md€ en 2018 (hors contrôle fiscal).',
            date: '2017',
            sourceIndex: 1,
          },
          chart: {
            kind: 'compare',
            unit: 'Md€',
            items: [
              { label: 'Recettes de l’ISF en 2017', value: 4.2 },
              { label: 'Recettes de l’IFI en 2018', value: 1.29 },
            ],
          },
        },
        {
          id: 'impots-fortune-04',
          say: 'Cet impôt ne porte que sur l’immobilier. En 2025, 193\u202f600\u00a0foyers ont reçu un avis d’IFI, pour 2,3\u00a0milliards d’euros en tout.',
          spoken: 'Cet impôt ne porte que sur l’immobilier. En deux mille vingt-cinq, cent quatre-vingt-treize mille six cents foyers ont reçu un avis d’I.F.I., pour deux virgule trois milliards d’euros en tout.',
          visual: 'figure',
          draw: 'Un immeuble et une maison, chacun avec son avis d’impôt\u202f; une flèche vers une pile de pièces.',
          emphasis: ['193\u202f600\u00a0foyers', '2,3\u00a0milliards'],
          figure: {
            value: '193\u202f600\u00a0foyers',
            label: 'Foyers ayant reçu un avis d’impôt sur la fortune immobilière (IFI), pour un total de 2,3\u00a0Md€ d’impôt (+8,0\u00a0% sur un an)',
            date: '2025',
            sourceIndex: 2,
          },
        },
        {
          id: 'impots-fortune-05',
          say: 'Ces impôts poussent-ils à partir à l’étranger\u202f? Sous l’ISF, environ 950\u00a0départs par an, pour 370\u00a0retours. Sous l’IFI, qui touche moins de foyers, 260\u00a0départs, pour 380\u00a0retours.',
          spoken: 'Ces impôts poussent-ils à partir à l’étranger ? Sous l’I.S.F., environ neuf cent cinquante départs par an, pour trois cent soixante-dix retours. Sous l’I.F.I., qui touche moins de foyers, deux cent soixante départs, pour trois cent quatre-vingts retours.',
          visual: 'compare',
          draw: 'Deux paires de barres depuis zéro, à la même échelle\u00a0: les départs et les retours par an, sous l’ISF puis sous l’IFI.',
          alt: 'Deux paires de barres à la même échelle, départs et retours de foyers assujettis, par an\u00a0: sous l’ISF (moyenne 2011-2016), sous l’IFI (moyenne 2018-2021).',
          emphasis: ['950\u00a0départs', '260\u00a0départs'],
          figure: {
            value: '260\u00a0départs par an',
            label: 'Départs à l’étranger de foyers assujettis à l’IFI (moyenne 2018-2021), pour 380\u00a0retours\u202f; sous l’ISF, environ 950\u00a0départs et 370\u00a0retours par an (moyenne 2011-2016)',
            date: '2018-2021',
            sourceIndex: 1,
          },
        },
        {
          id: 'impots-fortune-06',
          say: 'Pour le comité d’évaluation, l’enjeu budgétaire de ces départs est «\u00a0vraisemblablement de second ordre\u00a0». Selon une étude pour France Stratégie, les entreprises dont l’actionnaire principal part évolueraient ensuite moins bien, en moyenne.',
          visual: 'point',
          draw: 'Deux colonnes séparées d’un filet\u00a0: à gauche, une pile de pièces, «\u00a0second ordre\u00a0»\u202f; à droite, une mallette d’entreprise et une flèche qui descend.',
          emphasis: ['second ordre', 'moins bien'],
        },
        {
          id: 'impots-fortune-07',
          say: 'Pour les uns, les plus grands patrimoines doivent contribuer davantage aux finances publiques. Pour d’autres, les taxer plus risque de freiner l’investissement, ou de pousser au départ.',
          visual: 'compare',
          draw: 'Une balance au fléau horizontal\u00a0: des pièces qui montent sur un plateau\u202f; une grue de chantier et une valise sur l’autre.',
          emphasis: ['contribuer davantage', 'freiner l’investissement'],
        },
        {
          id: 'impots-fortune-08',
          say: 'Alors, comment imposer les plus grandes fortunes, et jusqu’où\u202f?',
          visual: 'question',
          draw: 'L’immeuble du début, une règle graduée posée contre lui, et un point d’interrogation.',
          emphasis: ['jusqu’où'],
        },
      ],
      sources: [
        {
          title: 'Les montants de patrimoine détenus par les ménages en 2024 (Insee Focus n° 371)',
          url: 'https://www.insee.fr/fr/statistiques/8672665',
          publisher: 'Insee',
          date: '2025-12-09',
        },
        COMITE_CAPITAL,
        {
          title: 'Bulletin «\u00a0DGFiP Statistiques\u00a0» n° 45 – L’impôt sur la fortune immobilière en 2025',
          url: 'https://www.impots.gouv.fr/actualite/bulletin-dgfip-statistiques-ndeg45-limpot-sur-la-fortune-immobiliere-en-2025',
          publisher: 'DGFiP (impots.gouv.fr)',
          date: '2026-04-14',
        },
      ],
    },
    {
      id: 'impots-heritages',
      kind: 'deep',
      questionIds: ['fiscalite-1'],
      title: 'Comment taxer les héritages\u202f?',
      short: 'Héritages',
      register: 'vous',
      segments: [
        {
          id: 'impots-heritages-01',
          say: 'Quand vous héritez, une part peut revenir à l’État\u00a0: ce sont les droits de succession. Qui les paie, et combien\u202f?',
          visual: 'hook',
          draw: 'Une clé passe d’une personne à une autre\u202f; en chemin, une pièce se détache vers un bâtiment public.',
          emphasis: ['droits de succession', 'Qui les paie'],
        },
        {
          id: 'impots-heritages-02',
          say: 'En 2025, ils ont rapporté 16,1\u00a0milliards d’euros à l’État. Et 5,1\u00a0milliards de plus pour les donations, faites de son vivant.',
          spoken: 'En deux mille vingt-cinq, ils ont rapporté seize virgule un milliards d’euros à l’État. Et cinq virgule un milliards de plus pour les donations, faites de son vivant.',
          visual: 'figure',
          draw: 'Deux barres depuis zéro, à la même échelle\u00a0: les droits de succession et les droits sur les donations.',
          alt: 'Deux barres à la même échelle\u00a0: droits de succession, droits sur les donations.',
          emphasis: ['16,1\u00a0milliards', '5,1\u00a0milliards'],
          figure: {
            value: '16,1\u00a0Md€',
            label: 'Droits de succession perçus par l’État (s’y ajoutent 5,1\u00a0Md€ de droits sur les donations)',
            date: '2025',
            sourceIndex: 0,
          },
          chart: {
            kind: 'compare',
            unit: 'Md€',
            items: [
              { label: 'Droits de succession', value: 16.1 },
              { label: 'Droits sur les donations', value: 5.1 },
            ],
          },
        },
        {
          id: 'impots-heritages-03',
          say: 'Sur 39\u00a0États de l’OCDE ou de l’Union européenne, c’est en France que ces droits pèsent le plus. En 2021, 0,74\u00a0% du PIB.',
          spoken: 'Sur trente-neuf États de l’O.C.D.E. ou de l’Union européenne, c’est en France que ces droits pèsent le plus. En deux mille vingt et un, zéro virgule soixante-quatorze pour cent du P.I.B.',
          visual: 'figure',
          draw: 'Trente-neuf cases en rang, une par État\u202f; la première, au bleu bille, est la France.',
          alt: 'Trente-neuf cases, une par État de l’OCDE ou de l’Union européenne\u00a0; la première est la France.',
          emphasis: ['39\u00a0États', 'pèsent le plus'],
          figure: {
            value: '0,74\u00a0% du PIB',
            label: 'Poids des droits de succession et de donation en France, le plus élevé de 39 États de l’OCDE ou de l’Union européenne',
            date: '2021',
            sourceIndex: 1,
          },
        },
        {
          id: 'impots-heritages-04',
          say: 'Selon une simulation du Trésor, 24\u00a0% des successions en ligne directe, entre parents et enfants par exemple, sont effectivement taxées.',
          spoken: 'Selon une simulation du Trésor, vingt-quatre pour cent des successions en ligne directe, entre parents et enfants par exemple, sont effectivement taxées.',
          visual: 'figure',
          draw: 'Cent petits carrés, cent successions\u202f; vingt-quatre se remplissent au bleu bille.',
          emphasis: ['24\u00a0%', 'effectivement taxées'],
          figure: {
            value: '24\u00a0%',
            label: 'Part des successions en ligne directe (entre parents et enfants, ou grands-parents et petits-enfants) effectivement taxées, selon une microsimulation de la DG Trésor',
            date: '2024',
            sourceIndex: 1,
          },
        },
        {
          id: 'impots-heritages-05',
          say: 'Sur les successions de plus d’un million d’euros, le taux réel est de 15\u00a0%, avec les exonérations sur les entreprises familiales et l’assurance-vie. Sans elles, plus de 20\u00a0%.',
          spoken: 'Sur les successions de plus d’un million d’euros, le taux réel est de quinze pour cent, avec les exonérations sur les entreprises familiales et l’assurance-vie. Sans elles, plus de vingt pour cent.',
          visual: 'compare',
          draw: 'Deux barres depuis zéro, à la même échelle\u00a0: avec les exonérations, 15\u00a0%\u202f; sans elles, plus de 20\u00a0%.',
          alt: 'Deux barres à la même échelle\u00a0: le taux avec les exonérations, et sans elles.',
          emphasis: ['15\u00a0%', 'plus de 20\u00a0%'],
          figure: {
            value: '15\u00a0%',
            label: 'Taux effectif d’imposition des successions de plus de 1\u00a0M€, avec les exonérations sur les entreprises familiales et l’assurance-vie\u202f; plus de 20\u00a0% sans elles',
            date: '2024',
            sourceIndex: 1,
          },
        },
        {
          id: 'impots-heritages-06',
          say: 'Pour les uns, la France taxe déjà les successions plus qu’ailleurs. Pour d’autres, les plus gros héritages, allégés par les exonérations, doivent contribuer davantage.',
          visual: 'compare',
          draw: 'Une balance au fléau horizontal\u00a0: une rangée de cases dont la première est comptée, sur un plateau\u202f; une clé et une flèche qui monte, sur l’autre.',
          emphasis: ['plus qu’ailleurs', 'contribuer davantage'],
        },
        {
          id: 'impots-heritages-07',
          say: 'Alors, quelle place donner aux droits de succession, et pour quels héritages\u202f?',
          visual: 'question',
          draw: 'La clé du début, posée devant un point d’interrogation.',
          emphasis: ['quels héritages'],
        },
      ],
      sources: [
        {
          ...EXECUTION_2025,
          title: 'Exécution budgétaire 2025 des recettes fiscales nettes de l’État et des remboursements et dégrèvements (§\u00a07.1)',
        },
        {
          title: 'Les droits de succession – Communication à la commission des finances de l’Assemblée nationale',
          url: 'https://www.ccomptes.fr/sites/default/files/2024-09/20240925-Droits-de-succession%C2%A0_1.pdf',
          publisher: 'Cour des comptes',
          date: '2024-09-25',
        },
      ],
    },
    {
      id: 'impots-capital',
      kind: 'deep',
      questionIds: ['fiscalite-x1'],
      title: 'Comment imposer le capital et les bénéfices\u202f?',
      short: 'Capital et bénéfices',
      register: 'vous',
      segments: [
        {
          id: 'impots-capital-01',
          say: 'Votre salaire est imposé au barème progressif\u00a0: plus le revenu est élevé, plus le taux monte. Et les dividendes, les intérêts de votre épargne\u202f?',
          visual: 'hook',
          draw: 'Un escalier de taux qui monte marche après marche, une mallette au pied\u202f; à côté, une pile de pièces et un point d’interrogation.',
          emphasis: ['barème progressif', 'les dividendes'],
        },
        {
          id: 'impots-capital-02',
          say: 'Depuis 2018, ces revenus ont en principe un taux unique. Il additionne 12,8\u00a0% d’impôt sur le revenu et 18,6\u00a0% de prélèvements sociaux, depuis janvier 2026.',
          spoken: 'Depuis deux mille dix-huit, ces revenus ont en principe un taux unique. Il additionne douze virgule huit pour cent d’impôt sur le revenu et dix-huit virgule six pour cent de prélèvements sociaux, depuis janvier deux mille vingt-six.',
          visual: 'figure',
          draw: 'Une barre unique, depuis zéro, en deux tronçons\u00a0: l’impôt sur le revenu, puis les prélèvements sociaux au bleu bille.',
          alt: 'Une barre en deux tronçons\u00a0: impôt sur le revenu, prélèvements sociaux.',
          emphasis: ['12,8\u00a0%', '18,6\u00a0%'],
          figure: {
            value: '12,8\u00a0%',
            label: 'Taux d’impôt sur le revenu du prélèvement forfaitaire unique sur les revenus de l’épargne, auquel s’ajoutent les prélèvements sociaux, passés à 18,6\u00a0% au 1er\u00a0janvier 2026',
            date: '2026',
            sourceIndex: 0,
          },
        },
        {
          id: 'impots-capital-03',
          say: 'En 2021, 1\u00a0% des foyers fiscaux, 400\u202f000 sur 40\u00a0millions, déclaraient 96\u00a0% des dividendes.',
          spoken: 'En deux mille vingt et un, un pour cent des foyers fiscaux, quatre cent mille sur quarante millions, déclaraient quatre-vingt-seize pour cent des dividendes.',
          visual: 'figure',
          draw: 'Deux grilles de cent carrés côte à côte\u00a0: les foyers, dont un seul est compté\u202f; les dividendes, dont quatre-vingt-seize sont comptés.',
          alt: 'Deux grilles de cent carrés\u00a0: les foyers fiscaux, 1 compté\u00a0; les dividendes, 96 comptés.',
          emphasis: ['1\u00a0% des foyers', '96\u00a0%'],
          figure: {
            value: '96\u00a0%',
            label: 'Part des dividendes déclarés par 1\u00a0% des foyers fiscaux (400\u202f000 foyers sur 40\u00a0millions)',
            date: '2021',
            sourceIndex: 1,
          },
          chart: { kind: 'part', value: 96, total: 100, unit: '%', whole: 'des dividendes déclarés' },
        },
        {
          id: 'impots-capital-04',
          say: 'Après la réforme, les dividendes déclarés sont passés d’environ 14 à 23\u00a0milliards d’euros. Selon le comité d’évaluation de cette réforme, cela aurait compensé son coût les premières années.',
          spoken: 'Après la réforme, les dividendes déclarés sont passés d’environ quatorze à vingt-trois milliards d’euros. Selon le comité d’évaluation de cette réforme, cela aurait compensé son coût les premières années.',
          visual: 'figure',
          draw: 'Deux colonnes depuis zéro\u00a0: les dividendes déclarés avant la réforme (2013-2017), puis après (2018-2020).',
          alt: 'Deux colonnes à la même échelle, en milliards d’euros\u00a0: 2013-2017, puis 2018-2020.',
          emphasis: ['14', '23\u00a0milliards'],
          figure: {
            value: '23\u00a0Md€',
            label: 'Dividendes déclarés par les ménages (2018-2020), contre environ 14\u00a0Md€ (2013-2017)',
            date: '2018-2020',
            sourceIndex: 1,
          },
        },
        {
          id: 'impots-capital-05',
          say: 'Le comité n’a détecté aucun effet sur l’investissement ni sur les salaires des entreprises les plus concernées. Les créations d’entreprises, elles, ont progressé plus vite dans les secteurs les plus favorisés par les réformes de 2018.',
          spoken: 'Le comité n’a détecté aucun effet sur l’investissement ni sur les salaires des entreprises les plus concernées. Les créations d’entreprises, elles, ont progressé plus vite dans les secteurs les plus favorisés par les réformes de deux mille dix-huit.',
          visual: 'point',
          draw: 'Deux colonnes séparées d’un filet\u00a0: une grue et un billet suivis d’un signe égal\u202f; une mallette et une flèche qui monte.',
          emphasis: ['aucun effet', 'créations d’entreprises'],
        },
        {
          id: 'impots-capital-06',
          say: 'Les entreprises paient l’impôt sur les sociétés\u00a0: 25\u00a0% des bénéfices au taux normal. En 2025, cet impôt a rapporté 59,9\u00a0milliards d’euros net à l’État. Les plus grandes ont versé en plus 7,5\u00a0milliards de contribution exceptionnelle.',
          spoken: 'Les entreprises paient l’impôt sur les sociétés : vingt-cinq pour cent des bénéfices au taux normal. En deux mille vingt-cinq, cet impôt a rapporté cinquante-neuf virgule neuf milliards d’euros net à l’État. Les plus grandes ont versé en plus sept virgule cinq milliards de contribution exceptionnelle.',
          visual: 'figure',
          draw: 'Un disque dont un quart est compté, le taux normal\u202f; dessous, deux barres depuis zéro, à la même échelle\u00a0: l’impôt sur les sociétés et la contribution exceptionnelle.',
          alt: 'Un disque, un quart des bénéfices\u00a0; deux barres à la même échelle\u00a0: impôt sur les sociétés, contribution exceptionnelle.',
          emphasis: ['25\u00a0%', '59,9\u00a0milliards', '7,5\u00a0milliards'],
          figure: {
            value: '7,5\u00a0Md€',
            label: 'Rendement de la contribution exceptionnelle sur les bénéfices des grandes entreprises. L’impôt sur les sociétés lui-même a rapporté 59,9\u00a0Md€ net à l’État la même année.',
            date: '2025',
            sourceIndex: 2,
          },
          chart: {
            kind: 'compare',
            unit: 'Md€',
            items: [
              { label: 'Contribution exceptionnelle', value: 7.5 },
              { label: 'Impôt sur les sociétés', value: 59.9 },
            ],
          },
        },
        {
          id: 'impots-capital-07',
          say: 'Pour les uns, revenus du travail et du capital doivent être imposés de la même façon. Pour d’autres, il ne faut pas décourager l’épargne et l’investissement.',
          visual: 'compare',
          draw: 'Une balance au fléau horizontal\u00a0: une mallette et une courbe de Bourse à égalité sur un plateau\u202f; une tirelire et une grue sur l’autre.',
          emphasis: ['de la même façon', 'décourager l’épargne'],
        },
        {
          id: 'impots-capital-08',
          say: 'Alors, comment imposer les revenus du capital et les bénéfices des entreprises\u202f?',
          visual: 'question',
          draw: 'Une courbe de Bourse et une mallette côte à côte, devant un point d’interrogation.',
          emphasis: ['comment imposer'],
        },
      ],
      sources: [
        {
          title: 'Impôt sur le revenu – Revenus d’épargne et de placement (revenus 2026)',
          url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F34913/1_7',
          publisher: 'Service-public.gouv.fr (DILA)',
          date: '2026-04-15',
        },
        COMITE_CAPITAL,
        {
          ...EXECUTION_2025,
          title: 'Exécution budgétaire 2025 des recettes fiscales nettes de l’État (§\u00a07.5 et tableau 14)',
        },
        {
          title: 'Impôt sur les sociétés (IS)\u00a0: taux, déclaration, paiement',
          url: 'https://entreprendre.service-public.gouv.fr/vosdroits/F23575',
          publisher: 'Entreprendre.service-public.gouv.fr (DILA)',
          date: '2026-02-17',
        },
      ],
    },
    {
      id: 'impots-recettes',
      kind: 'deep',
      questionIds: ['fiscalite-3'],
      title: 'À quoi affecter une recette nouvelle\u202f?',
      short: 'Recettes nouvelles',
      register: 'vous',
      segments: [
        {
          id: 'impots-recettes-01',
          say: 'Un impôt rapporte davantage. À quoi sert cet argent en plus\u202f?',
          visual: 'hook',
          draw: 'Une pile de pièces, une pièce de plus posée dessus\u202f; trois flèches en pointillé partent vers un point d’interrogation.',
          emphasis: ['À quoi sert cet argent'],
        },
        {
          id: 'impots-recettes-02',
          say: 'En règle générale, à l’ensemble des dépenses\u00a0: toutes les recettes de l’État vont dans un même budget, sauf exceptions. C’est la règle d’universalité.',
          visual: 'point',
          draw: 'Des pièces de toutes parts tombent dans une même caisse, d’où partent des flèches vers plusieurs guichets.',
          emphasis: ['un même budget', 'universalité'],
        },
        {
          id: 'impots-recettes-03',
          say: 'La Sécurité sociale, elle, répartit ses recettes entre ses branches\u00a0: maladie, vieillesse, famille, autonomie… Depuis 2024, la branche autonomie reçoit 0,15\u00a0point de CSG, qui allait avant au remboursement de la dette sociale.',
          spoken: 'La Sécurité sociale, elle, répartit ses recettes entre ses branches : maladie, vieillesse, famille, autonomie… Depuis deux mille vingt-quatre, la branche autonomie reçoit zéro virgule quinze point de C.S.G., qui allait avant au remboursement de la dette sociale.',
          visual: 'point',
          draw: 'Quatre caisses côte à côte, une par branche\u202f; une flèche au bleu bille part d’une caisse en pointillé, la dette sociale, vers celle de l’autonomie.',
          alt: 'Quatre caisses, une par branche\u00a0; une part de CSG passe du remboursement de la dette sociale à la branche autonomie.',
          emphasis: ['ses branches', '0,15\u00a0point de CSG'],
          figure: {
            value: '0,15\u00a0point de CSG',
            label: 'Part de la CSG (contribution sociale généralisée) attribuée à la branche autonomie depuis 2024, qui allait auparavant à la caisse chargée de rembourser la dette sociale (Cades)',
            date: '2024',
            sourceIndex: 0,
          },
        },
        {
          id: 'impots-recettes-04',
          say: 'Une recette nouvelle peut donc servir à trois choses\u00a0: alléger d’autres prélèvements, financer une dépense jugée prioritaire, ou réduire le déficit.',
          visual: 'point',
          draw: 'Trois lignes, chacune un pictogramme et sa flèche\u00a0: un avis d’impôt qui baisse, un guichet qui monte, une pile de pièces qui baisse.',
          emphasis: ['trois choses'],
        },
        {
          id: 'impots-recettes-05',
          say: 'Les prélèvements sur les salaires\u202f? En 2025, les cotisations sociales rapportent 312,5\u00a0milliards d’euros à la Sécurité sociale. Le grand âge\u202f? La branche autonomie dépense 41,8\u00a0milliards.',
          spoken: 'Les prélèvements sur les salaires ? En deux mille vingt-cinq, les cotisations sociales rapportent trois cent douze virgule cinq milliards d’euros à la Sécurité sociale. Le grand âge ? La branche autonomie dépense quarante et un virgule huit milliards.',
          visual: 'figure',
          draw: 'Deux fiches côte à côte, sans échelle commune\u00a0: une fiche de paie et son montant\u202f; un fauteuil et le sien.',
          alt: 'Deux ordres de grandeur, chacun avec son pictogramme\u00a0: les cotisations sociales, la branche autonomie.',
          emphasis: ['312,5\u00a0milliards', '41,8\u00a0milliards'],
          figure: {
            value: '312,5\u00a0Md€',
            label: 'Cotisations sociales perçues par les régimes obligatoires de base de la Sécurité sociale (hors retraites complémentaires et assurance chômage). Dépenses de la branche autonomie (personnes âgées et personnes handicapées)\u00a0: 41,8\u00a0Md€, en hausse de 4,8\u00a0% sur un an.',
            date: '2025',
            sourceIndex: 0,
          },
        },
        {
          id: 'impots-recettes-06',
          say: 'La transition climatique\u202f? Elle demanderait 25 à 34\u00a0milliards d’euros de dépenses publiques en plus par an à l’horizon 2030, selon France Stratégie. La dette\u202f? 64,7\u00a0milliards d’intérêts en 2025.',
          spoken: 'La transition climatique ? Elle demanderait vingt-cinq à trente-quatre milliards d’euros de dépenses publiques en plus par an à l’horizon deux mille trente, selon France Stratégie. La dette ? Soixante-quatre virgule sept milliards d’intérêts en deux mille vingt-cinq.',
          visual: 'figure',
          draw: 'Deux fiches côte à côte, sans échelle commune\u00a0: un thermomètre et une fourchette de montants\u202f; une pile de pièces et son montant.',
          alt: 'Deux ordres de grandeur, chacun avec son pictogramme\u00a0: la transition climatique, les intérêts de la dette.',
          emphasis: ['25 à 34\u00a0milliards', '64,7\u00a0milliards'],
          figure: {
            value: '25 à 34\u00a0Md€ par an',
            label: 'Supplément annuel de dépenses publiques lié à la transition climatique, à l’horizon 2030 (estimation publiée en mai 2023)',
            date: 'horizon 2030',
            sourceIndex: 1,
          },
        },
        {
          id: 'impots-recettes-07',
          say: 'Alors, à quoi affecter en priorité une recette nouvelle\u202f?',
          visual: 'question',
          draw: 'Un point d’interrogation au centre, quatre flèches en pointillé vers les quatre pictogrammes\u00a0: fiche de paie, fauteuil, thermomètre, pile de pièces.',
          emphasis: ['en priorité'],
        },
      ],
      sources: [
        {
          ...RALFSS_2026,
          title: 'La sécurité sociale 2026 – Rapport sur l’application des lois de financement de la sécurité sociale (p.\u00a037, 38 et 43)',
        },
        {
          title: 'Les incidences économiques de l’action pour le climat (rapport, chapitre 10, p.\u00a0113)',
          url: 'https://www.strategie-plan.gouv.fr/files/files/Publications/Rapport/2023-incidences-economiques-rapport-pisani-5juin.pdf',
          publisher: 'France Stratégie',
          date: '2023-05',
        },
        INSEE_APU,
        {
          title: 'Loi organique n° 2001-692 du 1er\u00a0août 2001 relative aux lois de finances (articles 6 et 16)',
          url: 'https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000394028',
          publisher: 'Légifrance',
        },
      ],
    },
  ],
}
