// Série « Logement » (famille « Santé, logement, solidarités ») : l'introduction, puis quatre approfondissements
// (loyers, logement social, construction, logements existants). Série d'essai validée par le propriétaire ;
// voix enregistrée (public/videos/audio/aigue/logement-*/). Règles d'écriture : ../GUIDE-SERIES.md.
// Ne pas toucher aux identifiants ni aux textes dits sans raison : changer un « say » ou un « spoken », c'est
// devoir réenregistrer la voix du passage.
// Datée : fin de l'essai d'encadrement des loyers en novembre 2026 sans nouvelle loi (examen au Sénat le
// 21 octobre 2026). À revoir après cette date.

import type { VideoSeries } from '../types'

export const LOGEMENT: VideoSeries = {
  topicId: 'logement',
  familyId: 'social',
  label: 'Logement',
  videos: [
    {
      id: 'logement-intro',
      kind: 'intro',
      questionIds: ['logement-1', 'logement-2', 'logement-x1'],
      title: 'Le logement\u00a0: ce qui se joue',
      short: 'Introduction',
      register: 'vous',
      segments: [
        {
          id: 'logement-intro-01',
          say: 'Sur 100\u00a0euros que vous gagnez, combien partent dans votre logement\u202f?',
          spoken: 'Sur cent euros que vous gagnez, combien partent dans votre logement ?',
          visual: 'hook',
          draw: 'Un billet de 100\u00a0euros dessiné au trait, découpé en parts comme un gâteau\u202f; une petite maison vient croquer une part.',
          emphasis: ['100\u00a0euros'],
        },
        {
          id: 'logement-intro-02',
          say: 'Pour la moitié des locataires du privé, c’est plus de 29,6\u00a0%, aides au logement déduites. Presque 30\u00a0euros sur 100.',
          spoken: 'Pour la moitié des locataires du privé, c’est plus de vingt-neuf virgule six pour cent, aides au logement déduites. Presque trente euros sur cent.',
          visual: 'figure',
          draw: 'Une rangée de 100 pièces de monnaie\u202f; 30 d’entre elles glissent une à une dans une clé de porte géante.',
          emphasis: ['29,6\u00a0%', '30\u00a0euros sur 100'],
          figure: {
            value: '29,6\u00a0%',
            label: 'Taux d’effort médian des locataires du parc privé\u00a0: la moitié d’entre eux consacrent plus de 29,6\u00a0% de leur revenu au logement (loyer, charges, eau, énergie, assurance), aides déduites (France métropolitaine)',
            date: '2023',
            sourceIndex: 0,
          },
        },
        {
          id: 'logement-intro-03',
          say: 'Acheter aussi demande plus d’efforts. Pour acheter le même logement avec le même apport qu’en 1975, un premier acheteur doit emprunter sur 22,9\u00a0ans, contre 14\u00a0ans à l’époque.',
          spoken: 'Acheter aussi demande plus d’efforts. Pour acheter le même logement avec le même apport qu’en mille neuf cent soixante-quinze, un premier acheteur doit emprunter sur vingt-deux virgule neuf ans, contre quatorze ans à l’époque.',
          visual: 'compare',
          draw: 'Deux calendriers côte à côte qui se déroulent comme des rubans\u00a0: 14 pages pour 1975, 23 pages pour aujourd’hui.',
          emphasis: ['22,9\u00a0ans', '14\u00a0ans'],
          figure: {
            value: '22,9\u00a0ans',
            label: 'Durée d’emprunt nécessaire à un primo-accédant pour acheter le même logement ancien avec le même apport personnel qu’en 1975, contre 14\u00a0ans en 1975 (calcul de J. Friggit cité par le Trésor)',
            date: '2e trimestre 2025',
            sourceIndex: 1,
          },
        },
        {
          id: 'logement-intro-04',
          say: 'Côté logement social, 2,76\u00a0millions de demandes fin 2024, pour 380\u202f000\u00a0logements attribués en un an. À peu près 1 demande sur 7.',
          spoken: 'Côté logement social, deux virgule soixante-seize millions de demandes fin deux mille vingt-quatre, pour trois cent quatre-vingt mille logements attribués en un an. À peu près une demande sur sept.',
          visual: 'figure',
          draw: 'Une file de sept silhouettes au trait devant une porte\u202f; une seule entre, les six autres restent dans la file.',
          emphasis: ['380\u202f000', '1 demande sur 7'],
          figure: {
            value: '380\u202f000',
            label: 'logements sociaux attribués en un an, pour 2,76\u00a0millions de demandes actives fin 2024 (France)',
            date: '2024',
            sourceIndex: 2,
          },
        },
        {
          id: 'logement-intro-05',
          say: 'Et l’on autorise moins de logements\u00a0: 369\u202f723 en douze mois. Pour 10\u00a0logements autorisés en moyenne les cinq années d’avant, à peine plus de 9 aujourd’hui.',
          spoken: 'Et l’on autorise moins de logements : trois cent soixante-neuf mille sept cent vingt-trois en douze mois. Pour dix logements autorisés en moyenne les cinq années d’avant, à peine plus de neuf aujourd’hui.',
          visual: 'figure',
          draw: 'Dix petites grues alignées\u202f; la dixième s’efface à moitié, en pointillé.',
          emphasis: ['369\u202f723', 'à peine plus de 9'],
          figure: {
            value: '369\u202f723',
            label: 'logements autorisés à la construction en douze mois, soit 9,7\u00a0% de moins que la moyenne des cinq années précédentes (France entière, hors Mayotte)',
            date: 'Septembre 2025 – août 2026',
            sourceIndex: 3,
          },
        },
        {
          id: 'logement-intro-06',
          say: 'Pour agir, il existe plusieurs leviers\u00a0: les loyers, le logement social, la construction, et les logements qui existent déjà.',
          visual: 'point',
          draw: 'Un tableau de bord dessiné à la main avec quatre manettes, chacune surmontée d’un pictogramme\u00a0: étiquette de prix, immeuble, grue, maison avec une fenêtre éteinte.',
          emphasis: ['loyers', 'logement social', 'construction'],
        },
        {
          id: 'logement-intro-07',
          say: 'Ils n’agissent pas sur les mêmes choses, n’ont pas le même coût, et ne vont pas à la même vitesse.',
          visual: 'point',
          draw: 'Les quatre manettes reliées chacune à un cadran différent\u00a0: une pièce de monnaie, un sablier, une flèche\u202f; les aiguilles bougent chacune à leur rythme.',
          emphasis: ['même coût', 'même vitesse'],
        },
        {
          id: 'logement-intro-08',
          say: 'Alors, quel levier, pour qui, et à quel prix\u202f?',
          visual: 'question',
          draw: 'Un grand point d’interrogation tracé au trait, dont le point est une petite maison.',
          emphasis: ['quel levier'],
        },
        {
          id: 'logement-intro-09',
          say: 'Dans les vidéos suivantes, on regarde chacun de ces leviers de plus près.',
          visual: 'outro',
          draw: 'Une loupe passe sur les quatre pictogrammes, l’un après l’autre.',
          emphasis: ['de plus près'],
        },
      ],
      sources: [
        {
          title: 'Logement – France, portrait social, édition 2025',
          url: 'https://www.insee.fr/fr/statistiques/8612550?sommaire=8612596',
          publisher: 'Insee',
          date: '2025-11-18',
        },
        {
          title: 'Trésor-Éco n° 405 – Logement\u00a0: des tensions structurelles pesant sur l’offre et la mobilité',
          url: 'https://www.tresor.economie.gouv.fr/Articles/572b5c4f-81c1-4879-ba96-50962e878252/files/7b57ca30-411c-4af3-8785-01924c8ef73d',
          publisher: 'Direction générale du Trésor',
          date: '2026-10',
        },
        {
          title: 'Rapport public annuel 2026 – Faciliter le parcours d’accès au logement social dans les territoires',
          url: 'https://www.ccomptes.fr/sites/default/files/2026-03/20260325-RPA-2026-I-4-Faciliter-le-parcours-d-acces-au-logement-social_0.pdf',
          publisher: 'Cour des comptes',
          date: '2026-03-25',
        },
        {
          title: 'Construction de logements\u00a0: résultats à fin août 2026 (France entière)',
          url: 'https://www.statistiques.developpement-durable.gouv.fr/construction-de-logements-resultats-fin-aout-2026-france-entiere',
          publisher: 'SDES – Ministère de la Transition écologique',
          date: '2026-09-29',
        },
      ],
    },
    {
      id: 'logement-loyers',
      kind: 'deep',
      questionIds: ['logement-1'],
      title: 'Encadrer les loyers',
      short: 'Loyers',
      register: 'vous',
      segments: [
        {
          id: 'logement-loyers-01',
          say: 'Vous changez d’appartement. Le propriétaire peut-il fixer le loyer comme il veut\u202f?',
          visual: 'hook',
          draw: 'Une clé tendue d’une main à l’autre, avec une étiquette de prix vierge qui se balance au bout.',
          emphasis: ['fixer le loyer', 'comme il veut'],
        },
        {
          id: 'logement-loyers-02',
          say: 'Dans les zones tendues, les grandes agglomérations où le logement manque, le loyer ne peut en général pas augmenter librement entre deux locataires.',
          visual: 'point',
          draw: 'Une carte de France au trait où quelques grandes villes s’entourent d’un cercle hachuré\u202f; une flèche de hausse butte contre un petit cadenas.',
          emphasis: ['zones tendues', 'librement'],
        },
        {
          id: 'logement-loyers-03',
          say: 'Dans neuf territoires volontaires, dont Paris, Lille, Lyon et Bordeaux, le loyer lui-même a un plafond, selon le quartier, le nombre de pièces et l’âge du logement.',
          visual: 'point',
          draw: 'Neuf épingles plantées sur la carte\u202f; au-dessus d’une barre de loyer, une ligne horizontale en pointillé marque le plafond.',
          emphasis: ['neuf territoires', 'plafond'],
        },
        {
          id: 'logement-loyers-04',
          say: 'C’est un essai de huit ans. Sans nouvelle loi, il s’arrête en novembre 2026. Un texte pour le rendre permanent, adopté par l’Assemblée, doit être examiné au Sénat le 21\u00a0octobre.',
          spoken: 'C’est un essai de huit ans. Sans nouvelle loi, il s’arrête en novembre deux mille vingt-six. Un texte pour le rendre permanent, adopté par l’Assemblée, doit être examiné au Sénat le vingt et un octobre.',
          visual: 'timeline',
          draw: 'Une frise de 2018 à 2026 tracée à la règle\u202f; un sablier posé sur novembre 2026 et un petit drapeau sur le 21\u00a0octobre.',
          emphasis: ['novembre 2026', '21\u00a0octobre'],
        },
        {
          id: 'logement-loyers-05',
          say: 'Effet mesuré sur les loyers\u00a0: 2 à 4\u00a0% de moins en deux ans. Sur un loyer de 800\u00a0euros, 16 à 32\u00a0euros par mois.',
          spoken: 'Effet mesuré sur les loyers : deux à quatre pour cent de moins en deux ans. Sur un loyer de huit cents euros, seize à trente-deux euros par mois.',
          visual: 'figure',
          draw: 'Une quittance de loyer de 800\u00a0euros\u202f; quelques pièces s’en détachent et retombent dans une tirelire.',
          emphasis: ['2 à 4\u00a0%', '16 à 32\u00a0euros'],
          figure: {
            value: '−2 à −4\u00a0%',
            label: 'Effet estimé du plafonnement sur les loyers en deux ans, dans les métropoles concernées',
            date: 'Évaluation publiée en mai 2026',
            sourceIndex: 3,
          },
        },
        {
          id: 'logement-loyers-06',
          say: 'Effet mesuré sur l’offre, hors Île-de-France\u00a0: 8\u00a0% de logements privés à louer en moins, en deux ans. À Paris, aucun effet mesuré.',
          spoken: 'Effet mesuré sur l’offre, hors Île-de-France : huit pour cent de logements privés à louer en moins, en deux ans. À Paris, aucun effet mesuré.',
          visual: 'figure',
          draw: 'Une grille de 100 petites portes\u202f; 8 se referment et s’effacent en pointillé.',
          emphasis: ['8\u00a0%', 'aucun effet mesuré'],
          figure: {
            value: '−8\u00a0%',
            label: 'Effet estimé sur l’offre de logements privés à louer hors Île-de-France, en deux ans (aucun effet mesuré à Paris)',
            date: 'Évaluation publiée en mai 2026',
            sourceIndex: 3,
          },
        },
        {
          id: 'logement-loyers-07',
          say: 'Et plus d’un tiers des baux récents étudiés dépassent le plafond\u00a0: complément autorisé, bail hors du dispositif, ou règle non respectée.',
          visual: 'figure',
          draw: 'Trois baux empilés\u202f; sur l’un des trois, la barre de loyer passe au-dessus de la ligne de plafond.',
          emphasis: ['plus d’un tiers'],
          figure: {
            value: 'Plus d’un tiers',
            label: 'des baux récents étudiés ont un loyer hors charges supérieur au plafond. Causes possibles selon le rapport\u00a0: complément de loyer autorisé, non-respect de la règle ou bail non soumis au plafond (environ 270\u202f000 baux signés de 2020 à 2024, dans les communes entrées dans le dispositif avant 2024)',
            date: 'Baux signés de 2020 à 2024',
            sourceIndex: 4,
          },
        },
        {
          id: 'logement-loyers-08',
          say: 'Pour les uns, c’est une protection des locataires. Pour d’autres, un risque de voir moins de logements à louer.',
          visual: 'compare',
          draw: 'Une balance à deux plateaux de même taille\u00a0: d’un côté un parapluie au-dessus d’un locataire, de l’autre une pancarte «\u00a0à louer\u00a0» qui rétrécit.',
          emphasis: ['protection des locataires', 'moins de logements à louer'],
        },
        {
          id: 'logement-loyers-09',
          say: 'Alors, jusqu’où encadrer les loyers\u202f?',
          visual: 'question',
          draw: 'La ligne de plafond en pointillé, avec un point d’interrogation posé dessus.',
          emphasis: ['jusqu’où'],
        },
      ],
      sources: [
        {
          title: 'En quoi consiste l’encadrement des loyers à respecter en zone tendue\u202f?',
          url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F1314',
          publisher: 'Service-Public.fr (DILA)',
          date: '2026-08-01',
        },
        {
          title: 'Texte adopté n° 196 – Proposition de loi pour retrouver la confiance et l’équilibre dans les rapports locatifs',
          url: 'https://www.assemblee-nationale.fr/dyn/17/textes/l17t0196_texte-adopte-provisoire',
          publisher: 'Assemblée nationale',
          date: '2025-12-11',
        },
        {
          title: 'Ordre du jour du Sénat (proposition de loi n° 217, 2025-2026)',
          url: 'https://www.senat.fr/ordre-du-jour/ordre-du-jour.html',
          publisher: 'Sénat',
          date: '2026-10-03',
        },
        {
          title: 'Trésor-Éco n° 405 – Logement\u00a0: des tensions structurelles pesant sur l’offre et la mobilité',
          url: 'https://www.tresor.economie.gouv.fr/Articles/572b5c4f-81c1-4879-ba96-50962e878252/files/7b57ca30-411c-4af3-8785-01924c8ef73d',
          publisher: 'Direction générale du Trésor',
          date: '2026-10',
        },
        {
          title: 'L’encadrement des loyers\u00a0: effets économiques et redistributifs – Rapport de la mission d’évaluation (G. Chapelle, G. Fack, avec l’IGEDD et l’IGF)',
          url: 'https://www.clcv.org/storage/app/media/RAPPORT%20FACK%20CHAPELLE.pdf',
          publisher: 'Mission d’évaluation commandée par le Premier ministre (copie hébergée par la CLCV)',
          date: '2026-05',
        },
      ],
    },
    {
      id: 'logement-social',
      kind: 'deep',
      questionIds: ['logement-2'],
      title: 'Le logement social',
      short: 'Logement social',
      register: 'vous',
      segments: [
        {
          id: 'logement-social-01',
          say: 'Le logement social, réservé aux ménages très modestes\u202f? Non\u00a0: 72\u00a0% des ménages, plus de 7\u00a0sur 10, pourraient en demander un, au vu de leurs revenus.',
          spoken: 'Le logement social, réservé aux ménages très modestes ? Non : soixante-douze pour cent des ménages, plus de sept sur dix, pourraient en demander un, au vu de leurs revenus.',
          visual: 'hook',
          draw: 'Dix maisonnettes au trait\u202f; sept se remplissent d’un léger aplat, trois restent vides.',
          emphasis: ['72\u00a0%', 'plus de 7\u00a0sur 10'],
          figure: {
            value: '72\u00a0%',
            label: 'des ménages résidant en France ont des revenus sous les plafonds du logement social\u202f; la moitié de ces ménages éligibles sont propriétaires de leur logement',
            date: '2024',
            sourceIndex: 0,
          },
        },
        {
          id: 'logement-social-02',
          say: 'Le principe\u00a0: un loyer plus bas, sous conditions de revenus, dans des logements gérés par des bailleurs sociaux.',
          visual: 'point',
          draw: 'Un immeuble dessiné au trait\u202f; à l’entrée, une toise qui mesure une pile de pièces au lieu d’une taille.',
          emphasis: ['loyer plus bas', 'conditions de revenus'],
        },
        {
          id: 'logement-social-03',
          say: 'Loyer médian\u00a0: 5,90\u00a0euros le mètre carré, contre 11,30 dans le privé. Pour 50\u00a0mètres carrés, environ 295\u00a0euros, contre 565.',
          spoken: 'Loyer médian : cinq euros quatre-vingt-dix le mètre carré, contre onze euros trente dans le privé. Pour cinquante mètres carrés, environ deux cent quatre-vingt-quinze euros, contre cinq cent soixante-cinq.',
          visual: 'compare',
          draw: 'Deux appartements identiques de 50\u00a0m², côte à côte, chacun avec sa pile de billets\u202f; la pile du privé est environ deux fois plus haute.',
          emphasis: ['5,90\u00a0euros', '11,30'],
          figure: {
            value: '5,90\u00a0€/m²',
            label: 'Loyer médian au mètre carré dans le parc social, contre 11,30\u00a0€/m² dans le parc privé (chiffres de l’Ancols cités par le Trésor)',
            sourceIndex: 1,
            date: 'Données publiées en 2021',
          },
        },
        {
          id: 'logement-social-04',
          say: 'Il y a 5,4\u00a0millions de logements sociaux en France. À peu près 1 résidence principale sur 6.',
          spoken: 'Il y a cinq virgule quatre millions de logements sociaux en France. À peu près une résidence principale sur six.',
          visual: 'figure',
          draw: 'Six maisons en rang\u202f; l’une d’elles prend la forme d’un petit immeuble.',
          emphasis: ['5,4\u00a0millions', '1 résidence principale sur 6'],
          figure: {
            value: '5,4\u00a0millions',
            label: 'logements locatifs sociaux en France, soit 15,9\u00a0% des résidences principales',
            date: '1er janvier 2025',
            sourceIndex: 2,
          },
        },
        {
          id: 'logement-social-05',
          say: 'Mais il faut attendre\u00a0: 19\u00a0mois en moyenne pour obtenir un logement. En Île-de-France, 39,5\u00a0mois, plus de trois ans.',
          spoken: 'Mais il faut attendre : dix-neuf mois en moyenne pour obtenir un logement. En Île-de-France, trente-neuf virgule cinq mois, plus de trois ans.',
          visual: 'figure',
          draw: 'Un calendrier dont les pages s’envolent une à une\u202f; un second, à côté, en perd deux fois plus.',
          emphasis: ['19\u00a0mois', 'plus de trois ans'],
          figure: {
            value: '19\u00a0mois',
            label: 'Durée moyenne d’obtention d’un logement social, contre 39,5\u00a0mois en Île-de-France',
            date: '2024',
            sourceIndex: 0,
          },
        },
        {
          id: 'logement-social-06',
          say: 'Pourquoi\u202f? D’abord, les locataires partent moins. En 2024, 7\u00a0logements sociaux sur 100 ont changé d’occupant, contre 12,5 en 1999. Ensuite, la production de logements sociaux a ralenti depuis 2015.',
          spoken: 'Pourquoi ? D’abord, les locataires partent moins. En deux mille vingt-quatre, sept logements sociaux sur cent ont changé d’occupant, contre douze virgule cinq en mille neuf cent quatre-vingt-dix-neuf. Ensuite, la production de logements sociaux a ralenti depuis deux mille quinze.',
          visual: 'figure',
          draw: 'Une porte tournante qui ralentit\u202f; un compteur passe de 12,5 à 7\u202f; à côté, une grue qui pose de moins en moins d’étages.',
          emphasis: ['7\u00a0logements sociaux sur 100', '12,5'],
          figure: {
            value: '7\u00a0%',
            label: 'Taux moyen de rotation des locataires du parc social, contre 12,5\u00a0% en 1999',
            date: '2024',
            sourceIndex: 0,
          },
        },
        {
          id: 'logement-social-07',
          say: 'Construire plus de logements sociaux ajoute des loyers bas. Le soutien public au logement social était de 9,9\u00a0milliards d’euros en 2025.',
          spoken: 'Construire plus de logements sociaux ajoute des loyers bas. Le soutien public au logement social était de neuf virgule neuf milliards d’euros en deux mille vingt-cinq.',
          visual: 'figure',
          draw: 'Une grue qui pose des étages\u202f; à côté, une tirelire en forme de maison d’où tombent des pièces.',
          emphasis: ['9,9\u00a0milliards'],
          figure: {
            value: '9,9\u00a0Md€',
            label: 'Soutien public au logement social (aides à la construction et à la rénovation des logements sociaux)',
            date: '2025',
            sourceIndex: 1,
          },
        },
        {
          id: 'logement-social-08',
          say: 'Les rapports publics relèvent aussi des décalages\u00a0: la moitié des demandes vient de personnes seules, et les petits logements manquent. Et le loyer ne dépend pas directement des revenus de l’occupant.',
          visual: 'point',
          draw: 'Une silhouette seule devant une rangée de grands appartements\u202f; un seul studio, minuscule, au bout de la rangée.',
          emphasis: ['personnes seules', 'petits logements'],
        },
        {
          id: 'logement-social-09',
          say: 'Alors, comment raccourcir l’attente\u202f?',
          visual: 'question',
          draw: 'Un sablier couché sur le côté, avec un point d’interrogation.',
          emphasis: ['raccourcir l’attente'],
        },
      ],
      sources: [
        {
          title: 'Rapport public annuel 2026 – Faciliter le parcours d’accès au logement social dans les territoires',
          url: 'https://www.ccomptes.fr/sites/default/files/2026-03/20260325-RPA-2026-I-4-Faciliter-le-parcours-d-acces-au-logement-social_0.pdf',
          publisher: 'Cour des comptes',
          date: '2026-03-25',
        },
        {
          title: 'Trésor-Éco n° 405 – Logement\u00a0: des tensions structurelles pesant sur l’offre et la mobilité',
          url: 'https://www.tresor.economie.gouv.fr/Articles/572b5c4f-81c1-4879-ba96-50962e878252/files/7b57ca30-411c-4af3-8785-01924c8ef73d',
          publisher: 'Direction générale du Trésor',
          date: '2026-10',
        },
        {
          title: '5,4\u00a0millions de logements locatifs sociaux en France au 1er janvier 2025',
          url: 'https://www.statistiques.developpement-durable.gouv.fr/54-millions-de-logements-locatifs-sociaux-en-france-au-1er-janvier-2025',
          publisher: 'SDES – Ministère de la Transition écologique',
          date: '2026-01-20',
        },
      ],
    },
    {
      id: 'logement-construire',
      kind: 'deep',
      questionIds: ['logement-2', 'logement-x1'],
      title: 'Construire\u00a0: terrains et chantiers',
      short: 'Construction',
      register: 'vous',
      segments: [
        {
          id: 'logement-construire-01',
          say: 'Pour loger plus de monde, il faut des logements. Or, depuis 2022, les chantiers ont ralenti.',
          spoken: 'Pour loger plus de monde, il faut des logements. Or, depuis deux mille vingt-deux, les chantiers ont ralenti.',
          visual: 'hook',
          draw: 'Une grue au trait, immobile, avec une toile d’araignée accrochée au crochet.',
          emphasis: ['depuis 2022'],
        },
        {
          id: 'logement-construire-02',
          say: 'En cause d’abord, les taux des crédits immobiliers\u00a0: multipliés par quatre de 2022 à début 2024, avant de baisser un peu.',
          spoken: 'En cause d’abord, les taux des crédits immobiliers : multipliés par quatre de deux mille vingt-deux à début deux mille vingt-quatre, avant de baisser un peu.',
          visual: 'timeline',
          draw: 'Une courbe de taux qui grimpe comme un escalier de 2022 à 2024\u202f; en dessous, une file d’acheteurs qui s’amincit.',
          emphasis: ['multipliés par quatre'],
        },
        {
          id: 'logement-construire-03',
          say: 'Résultat\u00a0: 260\u202f000\u00a0logements mis en chantier en 2024, et autant en 2025, au plus bas. Environ 700 par jour. Une reprise s’amorce depuis fin 2025.',
          spoken: 'Résultat : deux cent soixante mille logements mis en chantier en deux mille vingt-quatre, et autant en deux mille vingt-cinq, au plus bas. Environ sept cents par jour. Une reprise s’amorce depuis fin deux mille vingt-cinq.',
          visual: 'figure',
          draw: 'Un compteur de chantier qui tourne au ralenti, puis une petite flèche qui repart vers le haut.',
          emphasis: ['260\u202f000', '700 par jour'],
          figure: {
            value: '260\u202f000',
            label: 'logements mis en chantier en 2024 et en 2025, au plus bas, avant une reprise depuis fin 2025',
            date: '2024 et 2025',
            sourceIndex: 0,
          },
        },
        {
          id: 'logement-construire-04',
          say: 'Il faut aussi des terrains. Pour une maison, 102\u00a0euros le mètre carré en moyenne en 2024, soit 95\u202f000\u00a0euros par terrain.',
          spoken: 'Il faut aussi des terrains. Pour une maison, cent deux euros le mètre carré en moyenne en deux mille vingt-quatre, soit quatre-vingt-quinze mille euros par terrain.',
          visual: 'figure',
          draw: 'Une parcelle quadrillée vue de dessus, avec une étiquette de prix plantée comme un piquet.',
          emphasis: ['102\u00a0euros', '95\u202f000\u00a0euros'],
          figure: {
            value: '102\u00a0€/m²',
            label: 'Prix moyen au m² d’un terrain acheté pour faire construire une maison individuelle, en hausse de 1,7\u00a0% sur un an\u202f; prix moyen par terrain\u00a0: 95\u202f000\u00a0€, pour 932\u00a0m² en moyenne (France métropolitaine)',
            date: '2024',
            sourceIndex: 1,
          },
        },
        {
          id: 'logement-construire-05',
          say: 'Et quand les prix montent de 1\u00a0%, la construction ne suit que de 0,5\u00a0% en moyenne dans les villes françaises. Selon une étude citée par le Trésor, les règles d’urbanisme locales expliqueraient environ deux tiers des écarts de réactivité de la construction entre villes.',
          spoken: 'Et quand les prix montent d’un pour cent, la construction ne suit que de zéro virgule cinq pour cent en moyenne dans les villes françaises. Selon une étude citée par le Trésor, les règles d’urbanisme locales expliqueraient environ deux tiers des écarts de réactivité de la construction entre villes.',
          visual: 'compare',
          draw: 'Deux flèches qui partent ensemble\u00a0: celle des prix monte, celle des constructions s’arrête à mi-hauteur\u202f; un règlement d’urbanisme posé en travers.',
          emphasis: ['1\u00a0%', '0,5\u00a0%'],
        },
        {
          id: 'logement-construire-06',
          say: 'Ces règles ont aussi des buts\u00a0: protéger le patrimoine, les paysages et les terres naturelles.',
          visual: 'point',
          draw: 'Un clocher, une colline et un champ dessinés au trait, entourés d’une clôture légère\u202f; une maison attend à l’extérieur.',
          emphasis: ['patrimoine', 'terres naturelles'],
        },
        {
          id: 'logement-construire-07',
          say: 'Pour encourager les particuliers à acheter des logements à louer, il existe des aides\u00a0: 2,2\u00a0milliards d’euros en 2025. Limite relevée par le Trésor\u00a0: là où le terrain manque, elles peuvent faire monter les prix.',
          spoken: 'Pour encourager les particuliers à acheter des logements à louer, il existe des aides : deux virgule deux milliards d’euros en deux mille vingt-cinq. Limite relevée par le Trésor : là où le terrain manque, elles peuvent faire monter les prix.',
          visual: 'figure',
          draw: 'Une pièce de monnaie glisse dans une maison-tirelire\u202f; à côté, l’étiquette de prix du terrain s’allonge.',
          emphasis: ['2,2\u00a0milliards', 'monter les prix'],
          figure: {
            value: '2,2\u00a0Md€',
            label: 'Aides publiques à l’investissement locatif privé (sur 45,9\u00a0Md€ d’aides au logement). Elles couvrent notamment le coût restant de la réduction d’impôt pour l’achat d’un logement neuf à louer, éteinte fin 2024\u202f; la loi de finances pour 2026 a créé un nouveau dispositif',
            date: '2025',
            sourceIndex: 0,
          },
        },
        {
          id: 'logement-construire-08',
          say: 'Alors, comment construire plus, où, et à quel coût\u202f?',
          visual: 'question',
          draw: 'La grue du début, un point d’interrogation pendu à son crochet.',
          emphasis: ['construire plus'],
        },
      ],
      sources: [
        {
          title: 'Trésor-Éco n° 405 – Logement\u00a0: des tensions structurelles pesant sur l’offre et la mobilité',
          url: 'https://www.tresor.economie.gouv.fr/Articles/572b5c4f-81c1-4879-ba96-50962e878252/files/7b57ca30-411c-4af3-8785-01924c8ef73d',
          publisher: 'Direction générale du Trésor',
          date: '2026-10',
        },
        {
          title: 'Le prix des terrains et du bâti pour les maisons individuelles en 2024',
          url: 'https://www.statistiques.developpement-durable.gouv.fr/le-prix-des-terrains-et-du-bati-pour-les-maisons-individuelles-en-2024',
          publisher: 'SDES – Enquête sur le prix des terrains à bâtir',
          date: '2025-11-27',
        },
      ],
    },
    {
      id: 'logement-existant',
      kind: 'deep',
      questionIds: ['logement-2', 'logement-x1'],
      title: 'Les logements qui existent déjà',
      short: 'Logements existants',
      register: 'vous',
      segments: [
        {
          id: 'logement-existant-01',
          say: 'Et si une partie des logements nécessaires existait déjà\u202f?',
          visual: 'hook',
          draw: 'Une rue dessinée au trait, de nuit\u202f; quelques fenêtres restent éteintes.',
          emphasis: ['une partie des logements', 'existait déjà'],
        },
        {
          id: 'logement-existant-02',
          say: '2,9\u00a0millions de logements sont vides en France\u00a0: à peu près 1\u00a0sur 13.',
          spoken: 'Deux virgule neuf millions de logements sont vides en France : à peu près un sur treize.',
          visual: 'figure',
          draw: 'Treize fenêtres alignées\u202f; une seule reste noire.',
          emphasis: ['2,9\u00a0millions', '1\u00a0sur 13'],
          figure: {
            value: '2,9\u00a0millions',
            label: 'logements vacants, soit 7,6\u00a0% du parc, contre 8,1\u00a0% en 2019. Le chiffre inclut les logements simplement en attente d’un locataire ou d’un acheteur (France hors Mayotte, données provisoires)',
            date: '1er janvier 2026',
            sourceIndex: 0,
          },
        },
        {
          id: 'logement-existant-03',
          say: 'Souvent, entre deux occupants. Vides depuis plus de deux ans\u00a0: environ 1,1\u00a0million dans le privé, surtout là où le logement ne manque pas.',
          spoken: 'Souvent, entre deux occupants. Vides depuis plus de deux ans : environ un virgule un million dans le privé, surtout là où le logement ne manque pas.',
          visual: 'figure',
          draw: 'Une carte de France\u00a0: les points des logements vides se regroupent loin des grandes villes.',
          emphasis: ['1,1\u00a0million', 'plus de deux ans'],
          figure: {
            value: '1,1\u00a0million',
            label: 'logements du parc privé vacants depuis plus de deux ans\u202f; la très grande majorité se situe dans des territoires où l’offre de logements est abondante\u202f; 118\u202f330 en zones tendues',
            date: '2022',
            sourceIndex: 1,
          },
        },
        {
          id: 'logement-existant-04',
          say: 'Dans les zones tendues, un logement vide depuis un an est taxé, pour qu’il revienne sur le marché. Selon la Cour des comptes, cette taxe n’a pas fait reculer les logements vides de longue durée.',
          visual: 'point',
          draw: 'Un avis d’imposition glissé sous une porte close\u202f; derrière la porte, un pot de peinture, des cartons et un fauteuil vide.',
          emphasis: ['taxé', 'longue durée'],
        },
        {
          id: 'logement-existant-05',
          say: 'Depuis 2025, une commune peut limiter à 90\u00a0jours par an, au lieu de 120, la location d’une résidence principale aux touristes.',
          spoken: 'Depuis deux mille vingt-cinq, une commune peut limiter à quatre-vingt-dix jours par an, au lieu de cent vingt, la location d’une résidence principale aux touristes.',
          visual: 'point',
          draw: 'Une valise à roulettes devant une porte, et un calendrier où 90 cases sont cochées sur 365.',
          emphasis: ['90\u00a0jours', '120'],
        },
        {
          id: 'logement-existant-06',
          say: 'Les passoires énergétiques, classées F ou G\u00a0: 3,9\u00a0millions de résidences principales début 2025, dont 1,1\u00a0million en location privée. Un nouveau calcul du DPE, depuis 2026, en fait sortir environ 700\u202f000.',
          spoken: 'Les passoires énergétiques, classées F ou G : trois virgule neuf millions de résidences principales début deux mille vingt-cinq, dont un virgule un million en location privée. Un nouveau calcul du D.P.E., depuis deux mille vingt-six, en fait sortir environ sept cent mille.',
          visual: 'figure',
          draw: 'Une maison au trait d’où s’échappent des volutes de chaleur par le toit et les fenêtres\u202f; une règle graduée glisse à côté et décale légèrement son étiquette.',
          emphasis: ['3,9\u00a0millions', '700\u202f000'],
          figure: {
            value: '3,9\u00a0millions',
            label: 'résidences principales classées F ou G au DPE («\u00a0passoires énergétiques\u00a0»), soit 12,7\u00a0% du parc, dont 1,1\u00a0million dans le parc locatif privé (France métropolitaine). Avec le calcul du DPE en vigueur depuis le 1er janvier 2026, environ 700\u202f000 de moins (simulation\u00a0: 3,2\u00a0millions, 10,4\u00a0% du parc)',
            date: '1er janvier 2025',
            sourceIndex: 4,
          },
        },
        {
          id: 'logement-existant-07',
          say: 'La loi interdit peu à peu de les louer\u00a0: classe G depuis 2025, F en 2028, E en 2034.',
          spoken: 'La loi interdit peu à peu de les louer : classe G depuis deux mille vingt-cinq, F en deux mille vingt-huit, E en deux mille trente-quatre.',
          visual: 'timeline',
          draw: 'Une frise avec trois étiquettes de DPE, G, F puis E, qui se décrochent l’une après l’autre.',
          emphasis: ['2025', '2028', '2034'],
        },
        {
          id: 'logement-existant-08',
          say: 'Rénover réduit les factures, et selon le Trésor, la mesure incite les propriétaires à engager des travaux. Mais, d’après une étude qu’il cite, l’annonce de l’interdiction des G aurait aussi poussé certains propriétaires à vendre plutôt qu’à rénover.',
          visual: 'compare',
          draw: 'À gauche, un radiateur et une facture qui rétrécit\u202f; à droite, une pancarte «\u00a0à vendre\u00a0» plantée devant la même maison.',
          emphasis: ['réduit les factures', 'vendre plutôt qu’à rénover'],
        },
        {
          id: 'logement-existant-09',
          say: 'Alors, comment mieux utiliser les logements existants\u202f?',
          visual: 'question',
          draw: 'La rue du début\u00a0: une à une, des fenêtres se rallument, avec un point d’interrogation au-dessus des toits.',
          emphasis: ['logements existants'],
        },
      ],
      sources: [
        {
          title: 'Parc de logements au 1er janvier 2026 – Insee Focus n° 388',
          url: 'https://www.insee.fr/fr/statistiques/9055697',
          publisher: 'Insee',
          date: '2026-09-30',
        },
        {
          title: 'La lutte contre les logements vacants dans le parc privé',
          url: 'https://www.ccomptes.fr/fr/publications/la-lutte-contre-les-logements-vacants-dans-le-parc-prive',
          publisher: 'Cour des comptes',
          date: '2025-05-22',
        },
        {
          title: 'Taxe annuelle sur les logements vacants (TLV) et taxe d’habitation sur les logements vacants (THLV)',
          url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F17293',
          publisher: 'Service-Public.fr (DILA)',
          date: '2025-06-11',
        },
        {
          title: 'Locations touristiques\u00a0: de nouvelles règles en 2025\u202f?',
          url: 'https://www.service-public.gouv.fr/particuliers/actualites/A17883',
          publisher: 'Service-Public.fr (DILA)',
          date: '2025-01-20',
        },
        {
          title: 'Le parc de logements par classe de performance énergétique au 1er janvier 2025',
          url: 'https://www.statistiques.developpement-durable.gouv.fr/le-parc-de-logements-par-classe-de-performance-energetique-au-1er-janvier-2025',
          publisher: 'SDES – Observatoire national de la rénovation énergétique',
          date: '2025-11-12',
        },
        {
          title: 'Diagnostic de performance énergétique (DPE)',
          url: 'https://www.ecologie.gouv.fr/politiques-publiques/diagnostic-performance-energetique-dpe',
          publisher: 'Ministère de la Transition écologique',
          date: '2025-12-19',
        },
        {
          title: 'Trésor-Éco n° 405 – Logement\u00a0: des tensions structurelles pesant sur l’offre et la mobilité',
          url: 'https://www.tresor.economie.gouv.fr/Articles/572b5c4f-81c1-4879-ba96-50962e878252/files/7b57ca30-411c-4af3-8785-01924c8ef73d',
          publisher: 'Direction générale du Trésor',
          date: '2026-10',
        },
      ],
    },
  ],
}
