// Série « Retraites » (famille « Travail et économie ») : l'introduction, puis quatre approfondissements
// (âge de départ, financement, montant des pensions, usure au travail). Série d'essai validée par le propriétaire ;
// voix enregistrée (public/videos/audio/aigue/retraites-*/). Règles d'écriture : ../GUIDE-SERIES.md.
// Ne pas toucher aux identifiants ni aux textes dits sans raison : changer un « say » ou un « spoken », c'est
// devoir réenregistrer la voix du passage.
// Datée : suspension de la réforme des retraites jusqu'en 2028. À revoir après cette date.

import type { VideoSeries } from '../types'

export const RETRAITES: VideoSeries = {
  topicId: 'retraites',
  familyId: 'economie',
  label: 'Retraites',
  videos: [
    {
      id: 'retraites-intro',
      kind: 'intro',
      questionIds: ['retraites-1', 'retraites-2'],
      title: 'Les retraites, l’essentiel',
      short: 'Introduction',
      register: 'vous',
      segments: [
        {
          id: 'retraites-intro-01',
          say: 'Un jour, vous arrêterez de travailler. Qui vous versera alors votre retraite\u202f?',
          visual: 'hook',
          draw: 'Un personnage au trait referme son casier de travail\u202f; au-dessus de sa tête, une enveloppe de pension marquée d’un point d’interrogation.',
          emphasis: ['Qui vous versera'],
        },
        {
          id: 'retraites-intro-02',
          say: 'Surtout ceux qui travailleront à ce moment-là\u00a0: leurs cotisations paient les pensions de la même année. C’est la répartition.',
          visual: 'point',
          draw: 'Une rangée d’actifs dont les pièces descendent par des flèches vers une rangée de retraités, le tout encadré par une même année.',
          emphasis: ['la répartition'],
        },
        {
          id: 'retraites-intro-03',
          say: 'Fin 2024, 17,3\u00a0millions de personnes touchaient une retraite.',
          spoken: 'Fin deux mille vingt-quatre, dix-sept virgule trois millions de personnes touchaient une retraite.',
          visual: 'figure',
          draw: 'Une foule de petites silhouettes au trait qui se remplit rangée par rangée, le nombre écrit à la main au-dessus.',
          emphasis: ['17,3\u00a0millions'],
          figure: {
            value: '17,3\u00a0millions',
            label: 'Personnes percevant une pension de retraite de droit direct au 31 décembre 2024, tous régimes, dont 16,4\u00a0millions résidant en France',
            date: '2024',
            sourceIndex: 0,
          },
        },
        {
          id: 'retraites-intro-04',
          say: 'En 2025, les dépenses de retraite atteignent 422\u00a0milliards d’euros. C’est 14,1\u00a0% du PIB, la richesse produite en un an.',
          spoken: 'En deux mille vingt-cinq, les dépenses de retraite atteignent quatre cent vingt-deux milliards d’euros. C’est quatorze virgule un pour cent du P.I.B., la richesse produite en un an.',
          visual: 'figure',
          draw: 'Un grand disque qui figure la richesse produite en un an\u202f; une part d’un peu plus d’un septième se hachure.',
          emphasis: ['422\u00a0milliards', '14,1\u00a0%'],
          figure: {
            value: '14,1\u00a0% du PIB',
            label: 'Dépenses de retraite en 2025, tous régimes obligatoires\u00a0: 422\u00a0Md€, soit 24,3\u00a0% de l’ensemble des dépenses publiques. Projection du COR\u00a0: 14,2\u00a0% du PIB en 2045 et 15,3\u00a0% en 2070',
            date: '2025',
            sourceIndex: 1,
          },
        },
        {
          id: 'retraites-intro-05',
          say: 'Environ un euro sur quatre de toutes les dépenses publiques.',
          visual: 'point',
          draw: 'Quatre pièces alignées\u202f; l’une est entourée d’un cercle de crayon et porte une petite enveloppe de pension.',
          emphasis: ['un euro sur quatre'],
        },
        {
          id: 'retraites-intro-06',
          say: 'Mais l’équilibre bouge. En 2002, 2,1\u00a0cotisants pour un retraité. En 2025, 1,8. En 2070, 1,3 selon les projections.',
          spoken: 'Mais l’équilibre bouge. En deux mille deux, deux virgule un cotisants pour un retraité. En deux mille vingt-cinq, un virgule huit. En deux mille soixante-dix, un virgule trois selon les projections.',
          visual: 'timeline',
          draw: 'Trois petites scènes datées sur une frise\u00a0: d’abord deux actifs face à un retraité, puis de moins en moins d’actifs.',
          emphasis: ['2,1', '1,8', '1,3'],
          figure: {
            value: '1,8',
            label: 'Nombre de cotisants par retraité en 2025 (estimation), contre 2,1 en 2002. Projection\u00a0: 1,3 en 2070 dans le scénario de référence',
            date: '2025',
            sourceIndex: 1,
          },
        },
        {
          id: 'retraites-intro-07',
          say: 'En 2025, il manque 5,1\u00a0milliards d’euros, sur plus de 400\u00a0milliards dépensés.',
          spoken: 'En deux mille vingt-cinq, il manque cinq virgule un milliards d’euros, sur plus de quatre cents milliards dépensés.',
          visual: 'figure',
          draw: 'Deux piles de pièces presque égales, recettes et dépenses\u202f; la pile des recettes un peu plus basse, l’écart marqué d’une accolade.',
          alt: 'Deux piles à la même échelle, les recettes et les dépenses\u00a0: l’écart, trop fin pour se voir, est montré du doigt.',
          emphasis: ['5,1\u00a0milliards'],
          figure: {
            value: '−5,1\u00a0Md€',
            label: 'Solde du système de retraite en 2025 (régimes de base et complémentaires), hors charges et produits financiers, soit −0,2\u00a0% du PIB. En les comptant, le déficit est de 1,3\u00a0Md€. Projection à règles inchangées\u00a0: −2,4\u00a0% du PIB en 2070 dans le scénario de référence, entre −1,7\u00a0% et −3,1\u00a0% selon la croissance de la productivité',
            date: '2025',
            sourceIndex: 1,
          },
        },
        {
          id: 'retraites-intro-08',
          say: 'Pour partir, il faut avoir l’âge minimum\u202f; pour une pension sans réduction, assez de trimestres. En 2025, on part en moyenne à 63,1\u00a0ans.',
          spoken: 'Pour partir, il faut avoir l’âge minimum ; pour une pension sans réduction, assez de trimestres. En deux mille vingt-cinq, on part en moyenne à soixante-trois virgule un ans.',
          visual: 'figure',
          draw: 'Une ligne de vie au trait avec une barrière d’âge minimum, et à côté une jauge de trimestres\u202f; un petit drapeau planté à 63,1.',
          alt: 'Sur une ligne des âges marquée 60, 62, 64 et 66\u00a0ans, un drapeau marque l’âge moyen de départ.',
          emphasis: ['63,1\u00a0ans'],
          figure: {
            value: '63,1\u00a0ans',
            label: 'Âge moyen de départ à la retraite en 2025, tous régimes obligatoires. Projection du COR\u00a0: 64,6\u00a0ans en 2070, en tenant compte de la suspension de la réforme',
            date: '2025',
            sourceIndex: 1,
          },
        },
        {
          id: 'retraites-intro-09',
          say: 'Alors, quatre questions se posent. À quel âge partir\u202f? Qui paie, et comment\u202f? Combien toucher\u202f? Et comment tenir compte de l’usure au travail\u202f?',
          visual: 'question',
          draw: 'Quatre pictogrammes en grille, dessinés l’un après l’autre\u00a0: un calendrier, une tirelire, une enveloppe de pension, une lune pour le travail de nuit.',
          emphasis: ['quel âge', 'Qui paie', 'Combien toucher'],
        },
        {
          id: 'retraites-intro-10',
          say: 'Ce sont les quatre sujets des vidéos qui suivent.',
          visual: 'outro',
          draw: 'Les quatre pictogrammes se rangent en file, comme les chapitres d’un carnet.',
        },
      ],
      sources: [
        {
          title: 'Effectifs de retraités et montants des pensions versées\u00a0: mise à disposition des données 2024',
          url: 'https://drees.solidarites-sante.gouv.fr/communique-de-presse-jeux-de-donnees/jeux-de-donnees/effectifs-de-retraites-et-montants-des',
          publisher: 'DREES',
          date: '2026-05-26',
        },
        {
          title: 'Rapport annuel du COR, juin 2026\u00a0: Évolutions et perspectives des retraites en France',
          url: 'https://www.cor-retraites.fr/sites/default/files/2026-07/RA_2026_def.pdf',
          publisher: 'Conseil d’orientation des retraites',
          date: '2026-06',
        },
      ],
    },
    {
      id: 'retraites-age',
      kind: 'deep',
      questionIds: ['retraites-1'],
      title: 'À quel âge partir à la retraite\u202f?',
      short: 'Âge de départ',
      register: 'vous',
      segments: [
        {
          id: 'retraites-age-01',
          say: 'Pour partir à la retraite, deux compteurs\u00a0: votre âge, et vos trimestres.',
          visual: 'hook',
          draw: 'Deux compteurs au trait côte à côte\u00a0: un cadran gradué en années, une grille de petites cases pour les trimestres.',
          emphasis: ['votre âge', 'vos trimestres'],
        },
        {
          id: 'retraites-age-02',
          say: 'L’âge légal, c’est le minimum pour partir, sauf exceptions comme les carrières longues.',
          visual: 'point',
          draw: 'Une barrière levante posée sur la ligne de vie, avec un petit portillon sur le côté pour les exceptions.',
          emphasis: ['âge légal'],
        },
        {
          id: 'retraites-age-03',
          say: 'Les trimestres mesurent votre carrière. S’il en manque, la pension baisse, sauf à 67\u00a0ans.',
          spoken: 'Les trimestres mesurent votre carrière. S’il en manque, la pension baisse, sauf à soixante-sept ans.',
          visual: 'point',
          draw: 'La grille de trimestres avec quelques cases vides\u202f; une paire de ciseaux rogne l’enveloppe de pension, puis s’efface au jalon 67.',
          emphasis: ['67\u00a0ans'],
        },
        {
          id: 'retraites-age-04',
          say: 'La réforme de 2023 relève l’âge légal de 62 à 64\u00a0ans, et la durée exigée à 172\u00a0trimestres.',
          spoken: 'La réforme de deux mille vingt-trois relève l’âge légal de soixante-deux à soixante-quatre ans, et la durée exigée à cent soixante-douze trimestres.',
          visual: 'compare',
          draw: 'Sur la ligne de vie, la barrière glisse de 62 à 64\u202f; en dessous, la grille de trimestres s’allonge d’une rangée.',
          emphasis: ['64\u00a0ans', '172\u00a0trimestres'],
        },
        {
          id: 'retraites-age-05',
          say: 'Elle est suspendue jusqu’en 2028, pas annulée\u00a0: dès la génération 1969, l’âge légal prévu reste 64\u00a0ans.',
          spoken: 'Elle est suspendue jusqu’en deux mille vingt-huit, pas annulée : dès la génération mille neuf cent soixante-neuf, l’âge légal prévu reste soixante-quatre ans.',
          visual: 'timeline',
          draw: 'Une frise des années de naissance\u202f; un panneau «\u00a0pause\u00a0» posé dessus jusqu’en 2028, puis la frise repart et rejoint le jalon 64 à la génération 1969.',
          alt: 'Le texte de la réforme de 2023, en pause jusqu’en 2028.',
          emphasis: ['jusqu’en 2028', 'pas annulée', '1969'],
        },
        {
          id: 'retraites-age-06',
          say: 'Cette suspension coûte 1,8\u00a0milliard d’euros par an en moyenne, jusqu’en 2032.',
          spoken: 'Cette suspension coûte un virgule huit milliard d’euros par an en moyenne, jusqu’en deux mille trente-deux.',
          visual: 'figure',
          draw: 'Une tirelire d’où s’échappent quelques pièces, une étiquette «\u00a0par an\u00a0» accrochée à sa queue.',
          emphasis: ['1,8\u00a0milliard'],
          figure: {
            value: '1,8\u00a0Md€ par an',
            label: 'Coût moyen de la suspension de la réforme de 2023, en année pleine, jusqu’en 2032 (chiffrage de la DREES repris par le COR)',
            date: '2026',
            sourceIndex: 2,
          },
        },
        {
          id: 'retraites-age-07',
          say: 'Selon le Conseil d’orientation des retraites, reculer l’âge rapporte deux fois\u00a0: plus de cotisations, et des pensions versées moins longtemps.',
          visual: 'point',
          draw: 'Une balance\u00a0: d’un côté une pièce de cotisation en plus tombe, de l’autre une année de pension se retire.',
          emphasis: ['deux fois'],
        },
        {
          id: 'retraites-age-08',
          say: 'Depuis la réforme, le taux d’emploi des 60 à 64\u00a0ans a gagné 3,4\u00a0points en 2024, puis 2 en 2025.',
          spoken: 'Depuis la réforme, le taux d’emploi des soixante à soixante-quatre ans a gagné trois virgule quatre points en deux mille vingt-quatre, puis deux en deux mille vingt-cinq.',
          visual: 'figure',
          draw: 'Une courbe au trait qui monte en deux marches, étiquetées 2024 et 2025.',
          alt: 'Deux marches au-dessus du niveau d’avant\u00a0: +3,4\u00a0points en 2024, puis +2 en 2025.',
          emphasis: ['3,4\u00a0points'],
          figure: {
            value: '+3,4\u00a0points',
            label: 'Hausse du taux d’emploi des 60-64\u00a0ans en 2024\u202f; nouvelle hausse de 2,0\u00a0points en 2025, principalement sous l’effet de la mise en œuvre de la réforme des retraites de 2023 selon l’Insee (France, personnes vivant en logement ordinaire)',
            date: '2024',
            sourceIndex: 3,
          },
        },
        {
          id: 'retraites-age-09',
          say: 'Mais à court terme, près d’un tiers des économies repart en autres dépenses sociales\u00a0: chômage, arrêts maladie, invalidité, minima sociaux.',
          visual: 'point',
          draw: 'Un tas de pièces économisées dont un tiers glisse, par une flèche, vers quatre guichets\u00a0: chômage, maladie, invalidité, minima sociaux.',
          emphasis: ['près d’un tiers'],
        },
        {
          id: 'retraites-age-10',
          say: 'Et la santé compte\u00a0: à 65\u00a0ans, il reste en moyenne 10,5\u00a0ans sans incapacité aux hommes, 11,8 aux femmes.',
          spoken: 'Et la santé compte : à soixante-cinq ans, il reste en moyenne dix virgule cinq ans sans incapacité aux hommes, onze virgule huit aux femmes.',
          visual: 'figure',
          draw: 'Deux sabliers au trait, hommes et femmes, dont le sable figure les années sans incapacité après 65\u00a0ans.',
          alt: 'Deux barres à la même échelle, hommes et femmes, à partir de 65\u00a0ans.',
          emphasis: ['10,5\u00a0ans', '11,8'],
          figure: {
            value: '10,5\u00a0ans (hommes), 11,8\u00a0ans (femmes)',
            label: 'Espérance de vie sans incapacité à 65\u00a0ans, c’est-à-dire sans être limité par un problème de santé dans les activités quotidiennes (France hors Mayotte, 2024)',
            date: '2024',
            sourceIndex: 4,
          },
        },
        {
          id: 'retraites-age-11',
          say: 'Financement et emploi d’un côté, santé de l’autre\u00a0: c’est la balance du débat.',
          visual: 'outro',
          draw: 'Une balance au trait\u00a0: une tirelire et une petite mallette de travail sur un plateau, un cœur sur l’autre, le fléau à l’horizontale.',
          emphasis: ['la balance'],
        },
      ],
      sources: [
        {
          title: 'Suspension de la réforme des retraites\u00a0: qui est concerné\u202f?',
          url: 'https://www.service-public.gouv.fr/particuliers/actualites/A18825',
          publisher: 'Service-public.gouv.fr (DILA)',
          date: '2026-02-27',
        },
        {
          title: 'Montant de la retraite du salarié du secteur privé',
          url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F21552',
          publisher: 'Service-public.gouv.fr (DILA)',
          date: '2026-09-01',
        },
        {
          title: 'Rapport annuel du COR, juin 2026\u00a0: Évolutions et perspectives des retraites en France',
          url: 'https://www.cor-retraites.fr/sites/default/files/2026-07/RA_2026_def.pdf',
          publisher: 'Conseil d’orientation des retraites',
          date: '2026-06',
        },
        {
          title: 'Une photographie du marché du travail en 2025 (Insee Première n° 2096)',
          url: 'https://www.insee.fr/fr/statistiques/8901327',
          publisher: 'Insee',
          date: '2026-03-25',
        },
        {
          title: 'L’espérance de vie sans incapacité à 65\u00a0ans est de 11,8\u00a0ans pour les femmes et de 10,5\u00a0ans pour les hommes en 2024 (Études et Résultats n° 1363)',
          url: 'https://drees.solidarites-sante.gouv.fr/sites/default/files/2026-01/ER1363_esperance_de_vie_sans_incapacit%C3%A9_0.pdf',
          publisher: 'DREES',
          date: '2026-01',
        },
      ],
    },
    {
      id: 'retraites-financement',
      kind: 'deep',
      questionIds: ['retraites-2'],
      title: 'Qui paie les retraites\u202f?',
      short: 'Financement',
      register: 'vous',
      segments: [
        {
          id: 'retraites-financement-01',
          say: 'Sur votre fiche de paie, une ligne «\u00a0Retraite\u00a0». Cet argent n’est pas mis de côté pour vous.',
          visual: 'hook',
          draw: 'Une fiche de paie esquissée, une ligne surlignée\u202f; une flèche en part, passe à côté d’une tirelire marquée à votre nom, et file vers une rangée de retraités.',
          emphasis: ['Retraite'],
        },
        {
          id: 'retraites-financement-02',
          say: 'Il paie les pensions d’aujourd’hui\u00a0: c’est la répartition.',
          visual: 'point',
          draw: 'Trois générations en escalier\u202f; chacune tend une pièce à la marche du dessus.',
          emphasis: ['la répartition'],
        },
        {
          id: 'retraites-financement-03',
          say: 'En 2025, le système a reçu 417\u00a0milliards d’euros, dont près des deux tiers en cotisations.',
          spoken: 'En deux mille vingt-cinq, le système a reçu quatre cent dix-sept milliards d’euros, dont près des deux tiers en cotisations.',
          visual: 'figure',
          draw: 'Un disque au trait dont les deux tiers se hachurent et prennent l’étiquette «\u00a0cotisations\u00a0».',
          emphasis: ['417\u00a0milliards', 'deux tiers'],
          figure: {
            value: '417\u00a0Md€',
            label: 'Ressources du système de retraite en 2025, hors produits financiers, dont 277\u00a0Md€ de cotisations sur les revenus d’activité\u202f; le reste vient d’impôts affectés et de transferts de l’État ou d’autres organismes publics',
            date: '2025',
            sourceIndex: 0,
          },
        },
        {
          id: 'retraites-financement-04',
          say: 'Mais il y a moins de cotisants par retraité\u00a0: 1,8 en 2025, et 1,3 projeté en 2070.',
          spoken: 'Mais il y a moins de cotisants par retraité : un virgule huit en deux mille vingt-cinq, et un virgule trois projeté en deux mille soixante-dix.',
          visual: 'timeline',
          draw: 'Deux petites scènes datées\u00a0: en 2025, deux actifs portent un banc où est assis un retraité\u202f; en 2070, moins d’épaules sous le même banc.',
          emphasis: ['1,8', '1,3'],
          figure: {
            value: '1,8',
            label: 'Nombre de cotisants par retraité en 2025 (estimation), contre 2,1 en 2002. Projection\u00a0: 1,3 en 2070 dans le scénario de référence',
            date: '2025',
            sourceIndex: 0,
          },
        },
        {
          id: 'retraites-financement-05',
          say: 'Pour combler le déficit, le Conseil d’orientation des retraites décrit trois leviers.',
          visual: 'point',
          draw: 'Une table de mixage avec trois curseurs au trait, étiquetés cotisations, pensions, âge.',
          alt: 'Trois curseurs, un par levier\u00a0: cotisations, pensions, âge de départ.',
          emphasis: ['trois leviers'],
        },
        {
          id: 'retraites-financement-06',
          say: 'Cotiser plus\u00a0: les pensions sont préservées, mais le salaire net baisse, ou le travail coûte plus cher à l’employeur.',
          visual: 'point',
          draw: 'Le curseur «\u00a0cotisations\u00a0» monte\u202f; l’enveloppe de pension reste intacte, une fiche de paie rétrécit d’un côté, une étiquette de coût s’allonge de l’autre.',
          emphasis: ['Cotiser plus'],
        },
        {
          id: 'retraites-financement-07',
          say: 'Revaloriser les pensions moins vite\u00a0: les dépenses baissent tout de suite, mais le revenu des retraités ralentit.',
          visual: 'point',
          draw: 'Le curseur «\u00a0pensions\u00a0» descend\u202f; une enveloppe de pension grandit moins vite qu’une étiquette de prix posée à côté.',
          emphasis: ['moins vite'],
        },
        {
          id: 'retraites-financement-08',
          say: 'Partir plus tard\u00a0: plus de cotisations et des pensions versées moins longtemps, mais des années de travail en plus, et à court terme, plus d’allocations versées.',
          visual: 'point',
          draw: 'Le curseur «\u00a0âge\u00a0» avance\u202f; des pièces rentrent dans la caisse, une silhouette voit sa ligne de travail s’allonger d’un cran, pendant qu’un guichet d’allocations voit sa file s’allonger un moment.',
          emphasis: ['Partir plus tard'],
        },
        {
          id: 'retraites-financement-09',
          say: 'Autre modèle, la capitalisation\u00a0: chacun épargne pour sa retraite. Fin 2024, 2,7\u00a0millions de personnes en touchaient une, en complément.',
          spoken: 'Autre modèle, la capitalisation : chacun épargne pour sa retraite. Fin deux mille vingt-quatre, deux virgule sept millions de personnes en touchaient une, en complément.',
          visual: 'figure',
          draw: 'Une tirelire personnelle posée à côté de la chaîne entre générations\u202f; une petite enveloppe en sort.',
          alt: 'À côté de la chaîne des générations, la répartition, une tirelire personnelle.',
          emphasis: ['la capitalisation', '2,7\u00a0millions'],
          figure: {
            value: '2,7\u00a0millions',
            label: 'Personnes percevant une retraite supplémentaire (épargne retraite par capitalisation, en plus des régimes obligatoires) fin 2024\u202f; 21,4\u00a0Md€ de cotisations en 2024, dont 77\u00a0% sur des plans d’épargne retraite',
            date: '2024',
            sourceIndex: 1,
          },
        },
        {
          id: 'retraites-financement-10',
          say: 'Selon un document de travail du COR, elle peut rapporter plus, mais dépend aussi de marchés plus instables que la croissance\u202f; la répartition, de la démographie et des choix politiques.',
          visual: 'compare',
          draw: 'Deux colonnes au trait\u00a0: sous la tirelire, une courbe de Bourse en dents de scie\u202f; sous la chaîne de générations, une pyramide des âges.',
          alt: 'À gauche, la capitalisation et une courbe de Bourse\u202f; à droite, la répartition et une pyramide des âges.',
          emphasis: ['rapporter plus', 'marchés', 'la démographie'],
        },
        {
          id: 'retraites-financement-11',
          say: 'Et passer à la capitalisation obligerait à financer deux retraites à la fois.',
          visual: 'point',
          draw: 'Une même main qui remplit en même temps l’enveloppe d’un retraité et une tirelire.',
          emphasis: ['deux retraites à la fois'],
        },
        {
          id: 'retraites-financement-12',
          say: 'Actifs, retraités, entreprises\u00a0: qui porte l’effort, et comment\u202f?',
          visual: 'question',
          draw: 'Les trois curseurs et la tirelire réunis sur une même table, en attente d’une main.',
          emphasis: ['qui porte l’effort'],
        },
      ],
      sources: [
        {
          title: 'Rapport annuel du COR, juin 2026\u00a0: Évolutions et perspectives des retraites en France',
          url: 'https://www.cor-retraites.fr/sites/default/files/2026-07/RA_2026_def.pdf',
          publisher: 'Conseil d’orientation des retraites',
          date: '2026-06',
        },
        {
          title: 'Les Plans épargne retraite représentent 77\u00a0% des cotisations de retraite supplémentaire en 2024',
          url: 'https://drees.solidarites-sante.gouv.fr/communique-de-presse-jeux-de-donnees/jeux-de-donnees/les-plans-epargne-retraite-cotisation',
          publisher: 'DREES',
          date: '2026-02-03',
        },
        {
          title: 'Typologie des systèmes de retraite\u00a0: de la répartition à la capitalisation individuelle (séance plénière du 18 décembre 2025, document n° 6, document de travail)',
          url: 'https://www.cor-retraites.fr/sites/default/files/2025-12/Doc_06_R%C3%A9partition%20%C3%A0%20Capitalisation.pdf',
          publisher: 'Secrétariat général du Conseil d’orientation des retraites',
          date: '2025-12-18',
        },
      ],
    },
    {
      id: 'retraites-pensions',
      kind: 'deep',
      questionIds: ['retraites-2'],
      title: 'Combien touche-t-on à la retraite\u202f?',
      short: 'Montant des pensions',
      register: 'vous',
      segments: [
        {
          id: 'retraites-pensions-01',
          say: 'Fin 2024, la retraite moyenne, c’est 1\u202f705\u00a0euros bruts par mois. Mais la moyenne cache des écarts.',
          spoken: 'Fin deux mille vingt-quatre, la retraite moyenne, c’est mille sept cent cinq euros bruts par mois. Mais la moyenne cache des écarts.',
          visual: 'hook',
          draw: 'Une enveloppe de pension ouverte, des billets qui en dépassent, le montant écrit à la main sur le rabat.',
          emphasis: ['1\u202f705\u00a0euros'],
          figure: {
            value: '1\u202f705\u00a0€',
            label: 'Pension moyenne de droit direct, brute, par mois, des retraités résidant en France, fin 2024 (tous régimes)',
            date: '2024',
            sourceIndex: 0,
          },
        },
        {
          id: 'retraites-pensions-02',
          say: 'Dans le privé, avec tous vos trimestres, la pension de base vaut la moitié du salaire moyen, plafonné, de vos 25 meilleures années. Plus une complémentaire.',
          spoken: 'Dans le privé, avec tous vos trimestres, la pension de base vaut la moitié du salaire moyen, plafonné, de vos vingt-cinq meilleures années. Plus une complémentaire.',
          visual: 'point',
          draw: 'Une frise de barres de salaire\u202f; les 25 plus hautes se colorent, leur moyenne est tracée puis coupée en deux\u202f; une seconde enveloppe plus petite vient s’ajouter.',
          emphasis: ['la moitié', '25 meilleures années'],
        },
        {
          id: 'retraites-pensions-03',
          say: 'La pension moyenne des femmes est 36\u00a0% plus basse que celle des hommes.',
          spoken: 'La pension moyenne des femmes est trente-six pour cent plus basse que celle des hommes.',
          visual: 'compare',
          draw: 'Deux barres au trait côte à côte, femmes et hommes, l’écart marqué d’une accolade.',
          emphasis: ['36\u00a0%'],
          figure: {
            value: '36\u00a0%',
            label: 'Écart de pension moyenne de droit direct entre les femmes et les hommes fin 2024, sans la pension de réversion (25\u00a0% en la comptant)',
            date: '2024',
            sourceIndex: 0,
          },
        },
        {
          id: 'retraites-pensions-04',
          say: 'Et 25\u00a0% plus basse en comptant la réversion, une part de la pension du conjoint décédé.',
          spoken: 'Et vingt-cinq pour cent plus basse en comptant la réversion, une part de la pension du conjoint décédé.',
          visual: 'compare',
          draw: 'Une petite rallonge vient se poser sur la barre des femmes\u202f; l’accolade se resserre.',
          alt: 'Les barres du passage précédent, femmes et hommes à la même échelle\u00a0: avec la réversion, celle des femmes s’allonge.',
          emphasis: ['25\u00a0%', 'la réversion'],
        },
        {
          id: 'retraites-pensions-05',
          say: 'Pour les plus petites ressources, le minimum vieillesse les complète, dès 65\u00a0ans, jusqu’à un peu plus de 1\u202f043\u00a0euros par mois pour une personne seule.',
          spoken: 'Pour les plus petites ressources, le minimum vieillesse les complète, dès soixante-cinq ans, jusqu’à un peu plus de mille quarante-trois euros par mois pour une personne seule.',
          visual: 'figure',
          draw: 'Un plancher au trait sous de petites enveloppes\u202f; une flèche remonte les plus basses jusqu’à lui.',
          emphasis: ['1\u202f043\u00a0euros'],
          figure: {
            value: '1\u202f043,59\u00a0€',
            label: 'Montant maximum mensuel de l’allocation de solidarité aux personnes âgées (minimum vieillesse), pour une personne seule, depuis le 1er\u00a0janvier 2026\u202f; l’allocation complète les autres ressources jusqu’à ce montant',
            date: '2026',
            sourceIndex: 2,
          },
        },
        {
          id: 'retraites-pensions-06',
          say: 'Chaque année, les pensions de base suivent les prix\u00a0: plus 0,9\u00a0% au 1er\u00a0janvier 2026.',
          spoken: 'Chaque année, les pensions de base suivent les prix : plus zéro virgule neuf pour cent au premier janvier deux mille vingt-six.',
          visual: 'figure',
          draw: 'Une étiquette de prix et une enveloppe de pension montent ensemble d’un cran, côte à côte.',
          emphasis: ['0,9\u00a0%'],
          figure: {
            value: '+0,9\u00a0%',
            label: 'Revalorisation des pensions de retraite de base au 1er\u00a0janvier 2026, selon la hausse des prix mesurée par l’Insee (hors tabac)',
            date: '2026',
            sourceIndex: 3,
          },
        },
        {
          id: 'retraites-pensions-07',
          say: 'Mais les salaires montent en général un peu plus vite que les prix.',
          visual: 'compare',
          draw: 'Deux lignes partent du même point\u00a0: celle des salaires grimpe un peu plus vite que celle des pensions.',
          emphasis: ['un peu plus vite'],
        },
        {
          id: 'retraites-pensions-08',
          say: 'Selon le Conseil d’orientation des retraites, le niveau de vie des retraités passerait de 100,2\u00a0% de celui de la population en 2023 à 90,3\u00a0% en 2070, tout en augmentant.',
          spoken: 'Selon le Conseil d’orientation des retraites, le niveau de vie des retraités passerait de cent virgule deux pour cent de celui de la population en deux mille vingt-trois à quatre-vingt-dix virgule trois pour cent en deux mille soixante-dix, tout en augmentant.',
          visual: 'figure',
          draw: 'Deux personnages qui montent un escalier\u202f; celui des retraités, d’abord à la même marche, prend peu à peu une marche de retard sans cesser de monter.',
          emphasis: ['100,2\u00a0%', '90,3\u00a0%'],
          figure: {
            value: '100,2\u00a0%',
            label: 'Niveau de vie moyen des retraités rapporté à celui de l’ensemble de la population en 2023. Projection du COR\u00a0: 90,3\u00a0% en 2070',
            date: '2023',
            sourceIndex: 4,
          },
        },
        {
          id: 'retraites-pensions-09',
          say: 'Revaloriser moins vite rapporte au système, mais réduit le revenu des retraités. Plus vite, c’est l’inverse.',
          visual: 'point',
          draw: 'Un curseur «\u00a0revalorisation\u00a0» entre deux plateaux\u00a0: la caisse des retraites d’un côté, le porte-monnaie d’un retraité de l’autre.',
          emphasis: ['moins vite', 'plus vite'],
        },
        {
          id: 'retraites-pensions-10',
          say: 'Quel niveau de pension garantir, et à quel rythme le faire évoluer\u202f?',
          visual: 'question',
          draw: 'L’enveloppe de pension du début, posée sur une frise d’années, avec un point d’interrogation au bout.',
          emphasis: ['quel rythme'],
        },
      ],
      sources: [
        {
          title: 'Effectifs de retraités et montants des pensions versées\u00a0: mise à disposition des données 2024',
          url: 'https://drees.solidarites-sante.gouv.fr/communique-de-presse-jeux-de-donnees/jeux-de-donnees/effectifs-de-retraites-et-montants-des',
          publisher: 'DREES',
          date: '2026-05-26',
        },
        {
          title: 'Montant de la retraite du salarié du secteur privé',
          url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F21552',
          publisher: 'Service-public.gouv.fr (DILA)',
          date: '2026-09-01',
        },
        {
          title: 'Allocation de solidarité aux personnes âgées (Aspa)',
          url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F16871',
          publisher: 'Service-public.gouv.fr (DILA)',
          date: '2026-06-23',
        },
        {
          title: 'Pensions de retraite de base\u00a0: quelle revalorisation au 1er\u00a0janvier 2026\u202f?',
          url: 'https://www.service-public.gouv.fr/particuliers/actualites/A17919',
          publisher: 'Service-public.gouv.fr (DILA)',
          date: '2025-12-24',
        },
        {
          title: 'Rapport annuel du COR, juin 2026\u00a0: Évolutions et perspectives des retraites en France',
          url: 'https://www.cor-retraites.fr/sites/default/files/2026-07/RA_2026_def.pdf',
          publisher: 'Conseil d’orientation des retraites',
          date: '2026-06',
        },
      ],
    },
    {
      id: 'retraites-penibilite',
      kind: 'deep',
      questionIds: ['retraites-1'],
      title: 'L’usure au travail et la retraite',
      short: 'Usure au travail',
      register: 'vous',
      segments: [
        {
          id: 'retraites-penibilite-01',
          say: 'Travail de nuit, bruit, gestes répétés\u00a0: certains métiers pèsent sur la santé. La retraite en tient-elle compte\u202f?',
          visual: 'hook',
          draw: 'Trois pictogrammes au trait\u00a0: une lune, une onde de bruit, une main qui répète le même geste en boucle.',
          emphasis: ['La retraite', 'en tient-elle compte'],
        },
        {
          id: 'retraites-penibilite-02',
          say: 'À 35\u00a0ans, un homme cadre vit en moyenne 5,3\u00a0ans de plus qu’un ouvrier. Chez les femmes, 3,4\u00a0ans.',
          spoken: 'À trente-cinq ans, un homme cadre vit en moyenne cinq virgule trois ans de plus qu’un ouvrier. Chez les femmes, trois virgule quatre ans.',
          visual: 'compare',
          draw: 'Deux lignes de vie parallèles qui partent de 35\u00a0ans, une veste et un bleu de travail esquissés au départ\u202f; l’écart d’arrivée fléché.',
          emphasis: ['5,3\u00a0ans', '3,4\u00a0ans'],
          figure: {
            value: '5,3\u00a0ans',
            label: 'Écart d’espérance de vie à 35\u00a0ans entre les hommes cadres et les hommes ouvriers (3,4\u00a0ans chez les femmes), France hors Mayotte, selon la mortalité observée en 2020-2022',
            date: '2020-2022',
            sourceIndex: 0,
          },
        },
        {
          id: 'retraites-penibilite-03',
          say: 'Un outil existe\u00a0: le compte professionnel de prévention, ou C2P. Il s’ouvre quand l’employeur déclare une exposition au-delà de certains seuils.',
          spoken: 'Un outil existe : le compte professionnel de prévention, ou C deux P. Il s’ouvre quand l’employeur déclare une exposition au-delà de certains seuils.',
          visual: 'point',
          draw: 'Une carte au trait marquée C2P, glissée dans une fente par une main d’employeur.',
          emphasis: ['C2P', 'l’employeur déclare'],
        },
        {
          id: 'retraites-penibilite-04',
          say: 'Six risques comptent\u00a0: nuit, équipes alternantes, gestes répétitifs, bruit, températures extrêmes et forte pression, comme en plongée.',
          visual: 'point',
          draw: 'La carte se déplie en six cases-pictogrammes\u00a0: lune, flèches qui tournent, main, onde, thermomètre, casque de scaphandrier.',
          emphasis: ['Six risques'],
        },
        {
          id: 'retraites-penibilite-05',
          say: 'Une année d’exposition rapporte 4\u00a0points par risque. Après 20\u00a0points pour la formation, 10\u00a0points valent un trimestre, jusqu’à 2\u00a0ans de départ anticipé.',
          spoken: 'Une année d’exposition rapporte quatre points par risque. Après vingt points pour la formation, dix points valent un trimestre, jusqu’à deux ans de départ anticipé.',
          visual: 'figure',
          draw: 'Des jetons tombent dans la carte\u202f; les premiers rejoignent un petit livre de formation, les suivants s’empilent par dix et se changent en cases de trimestre\u202f; la barrière d’âge recule d’un cran.',
          emphasis: ['4\u00a0points', '2\u00a0ans'],
          figure: {
            value: '4\u00a0points',
            label: 'Points acquis par année complète d’exposition et par facteur de risque sur le compte professionnel de prévention. Les 20 premiers points sont réservés à la formation\u202f; ensuite, 10\u00a0points donnent 1\u00a0trimestre, jusqu’à 8\u00a0trimestres, soit un départ jusqu’à 2\u00a0ans avant l’âge légal',
            date: '2026',
            sourceIndex: 1,
          },
        },
        {
          id: 'retraites-penibilite-06',
          say: 'En 2017, quatre risques en sont sortis\u00a0: postures pénibles, charges lourdes, vibrations, produits chimiques.',
          spoken: 'En deux mille dix-sept, quatre risques en sont sortis : postures pénibles, charges lourdes, vibrations, produits chimiques.',
          visual: 'timeline',
          draw: 'Sur une frise, au jalon 2017, quatre cases de la carte sont gommées une à une.',
          emphasis: ['quatre risques'],
        },
        {
          id: 'retraites-penibilite-07',
          say: 'Motif officiel\u00a0: leur évaluation était particulièrement complexe. Un départ anticipé reste possible, mais lié à une maladie professionnelle.',
          visual: 'point',
          draw: 'Les quatre cases gommées réapparaissent devant un autre guichet, marqué d’une croix de soin.',
          emphasis: ['maladie professionnelle'],
        },
        {
          id: 'retraites-penibilite-08',
          say: 'En 2022, la Cour des comptes demandait un programme de contrôle des employeurs sur ce compte.',
          spoken: 'En deux mille vingt-deux, la Cour des comptes demandait un programme de contrôle des employeurs sur ce compte.',
          visual: 'point',
          draw: 'Une loupe au trait passe au-dessus de la fente où les employeurs glissent les déclarations.',
          emphasis: ['Cour des comptes'],
        },
        {
          id: 'retraites-penibilite-09',
          say: 'D’un côté, des écarts d’espérance de vie selon la profession. De l’autre, certaines expositions dures à mesurer, et le coût de départs anticipés.',
          visual: 'compare',
          draw: 'Deux plateaux d’une balance\u00a0: deux lignes de vie inégales d’un côté\u202f; de l’autre, un mètre ruban emmêlé et une tirelire.',
          emphasis: ['écarts d’espérance de vie', 'dures à mesurer'],
        },
        {
          id: 'retraites-penibilite-10',
          say: 'Comment mesurer l’usure, et quelle place lui donner dans l’âge de départ\u202f?',
          visual: 'question',
          draw: 'Le mètre ruban se déroule le long d’une ligne de vie et s’arrête sur un point d’interrogation.',
          emphasis: ['mesurer l’usure'],
        },
      ],
      sources: [
        {
          title: 'Les écarts d’espérance de vie entre cadres et ouvriers\u00a0: 5\u00a0ans chez les hommes, 3\u00a0ans chez les femmes (Insee Première n° 2005)',
          url: 'https://www.insee.fr/fr/statistiques/8220688',
          publisher: 'Insee',
          date: '2024-07-16',
        },
        {
          title: 'Compte professionnel de prévention (C2P)',
          url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F15504',
          publisher: 'Service-public.gouv.fr (DILA)',
          date: '2026-04-10',
        },
        {
          title: 'Utilisation du compte professionnel de prévention (C2P) pour la retraite du salarié',
          url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F36326',
          publisher: 'Service-public.gouv.fr (DILA)',
          date: '2026-01-01',
        },
        {
          title: 'Rapport au Président de la République relatif à l’ordonnance n° 2017-1389 du 22 septembre 2017',
          url: 'https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000035607467',
          publisher: 'Légifrance',
          date: '2017-09-23',
        },
        {
          title: 'Les politiques publiques de prévention en santé au travail dans les entreprises',
          url: 'https://www.ccomptes.fr/fr/documents/62810',
          publisher: 'Cour des comptes',
          date: '2022-12',
        },
        {
          title: 'Rapport annuel du COR, juin 2026\u00a0: Évolutions et perspectives des retraites en France',
          url: 'https://www.cor-retraites.fr/sites/default/files/2026-07/RA_2026_def.pdf',
          publisher: 'Conseil d’orientation des retraites',
          date: '2026-06',
        },
      ],
    },
  ],
}
