// Série « Santé et grand âge » (famille « Santé, logement, solidarités ») : l'introduction, puis quatre
// approfondissements, un par question de la banque (accès aux soins, remboursements, grand âge, prévention).
// Matière : les fiches du thème (research/choisir-2027/explainers.json, sante-1, sante-2, sante-3, sante-x1)
// et leurs graphiques, rien d'autre. Règles d'écriture : ../GUIDE-SERIES.md ; planches :
// ../pistes/planches/sante.tsx.
// Ne pas toucher aux identifiants ni aux textes dits sans raison : changer un « say » ou un « spoken », c'est
// devoir réenregistrer la voix du passage.
// Datée : proposition de loi sur l'installation des médecins, adoptée par l'Assemblée nationale, examen en séance
// au Sénat commencé le 11 juin 2026 puis suspendu (fiche du Sénat de juin 2026). À revoir si l'examen reprend
// ou si le texte est adopté.

import type { VideoSeries } from '../types'

export const SANTE: VideoSeries = {
  topicId: 'sante',
  familyId: 'social',
  label: 'Santé et grand âge',
  videos: [
    {
      id: 'sante-intro',
      kind: 'intro',
      questionIds: ['sante-1', 'sante-2', 'sante-3', 'sante-x1'],
      title: 'Santé et grand âge, l’essentiel',
      short: 'Introduction',
      register: 'vous',
      segments: [
        {
          id: 'sante-intro-01',
          say: 'Vous tombez malade. Qui vous soigne, et qui paie\u202f?',
          visual: 'hook',
          draw: 'Une personne au trait, un thermomètre à côté\u202f; deux flèches en pointillé mènent à une croix de soin et à un porte-monnaie, sous un point d’interrogation.',
          emphasis: ['Qui vous soigne', 'qui paie'],
        },
        {
          id: 'sante-intro-02',
          say: 'En 2025, 6,3\u00a0millions d’assurés adultes n’avaient pas de médecin traitant\u00a0: plus d’un adulte sur 10.',
          spoken: 'En deux mille vingt-cinq, six virgule trois millions d’assurés adultes n’avaient pas de médecin traitant : plus d’un adulte sur dix.',
          visual: 'figure',
          draw: 'Dix silhouettes en deux rangées, chacune avec sa petite croix de soin\u202f; la dixième passe au bleu bille, sa croix en pointillé.',
          emphasis: ['6,3\u00a0millions', 'plus d’un adulte sur 10'],
          figure: {
            value: '6,3\u00a0millions',
            label: 'Assurés adultes sans médecin traitant en 2025\u00a0; 88,5\u00a0% de la population adulte en avait déclaré un',
            date: '2025',
            sourceIndex: 0,
          },
        },
        {
          id: 'sante-intro-03',
          say: 'Vos soins sont souvent payés par la Sécurité sociale, une complémentaire santé, et par vous. Ce reste à payer, en 2025\u00a0: 9,7\u00a0% des dépenses de santé, 495\u00a0euros par habitant.',
          spoken: 'Vos soins sont souvent payés par la Sécurité sociale, une complémentaire santé, et par vous. Ce reste à payer, en deux mille vingt-cinq : neuf virgule sept pour cent des dépenses de santé, quatre cent quatre-vingt-quinze euros par habitant.',
          visual: 'figure',
          draw: 'Un disque, toutes les dépenses de santé\u202f; une fine part se hachure au bleu bille, ce qui reste à payer, avec le montant par habitant.',
          alt: 'Un disque, les dépenses de santé\u00a0: la part payée par vous.',
          emphasis: ['9,7\u00a0%', '495\u00a0euros'],
          figure: {
            value: '9,7\u00a0%',
            label: 'Part de la dépense courante de santé qui reste à payer par les ménages en 2025, soit 495\u00a0€ par habitant\u00a0; moyenne de l’Union européenne\u00a0: 14,8\u00a0% (dernière année disponible)',
            date: '2025',
            sourceIndex: 1,
          },
        },
        {
          id: 'sante-intro-04',
          say: 'Le grand âge, aussi\u00a0: en 2024, 31,1\u00a0milliards d’euros d’argent public pour les personnes âgées qui perdent leur autonomie.',
          spoken: 'Le grand âge, aussi : en deux mille vingt-quatre, trente et un virgule un milliards d’euros d’argent public pour les personnes âgées qui perdent leur autonomie.',
          visual: 'figure',
          draw: 'Un fauteuil au trait\u202f; à côté, une pile de pièces qui passe au bleu bille.',
          emphasis: ['31,1\u00a0milliards'],
          figure: {
            value: '31,1\u00a0Md€',
            label: 'Argent public consacré en 2024 à la perte d’autonomie des personnes âgées\u00a0: 79\u00a0% par la Sécurité sociale, 16\u00a0% par les départements, 5\u00a0% par l’État, sans compter les dépenses des personnes elles-mêmes ni celles de leurs proches',
            date: '2024',
            sourceIndex: 2,
          },
        },
        {
          id: 'sante-intro-05',
          say: 'Et pour éviter les maladies, la prévention\u00a0: 9,2\u00a0milliards d’euros en 2025, sans compter une partie faite en consultation.',
          spoken: 'Et pour éviter les maladies, la prévention : neuf virgule deux milliards d’euros en deux mille vingt-cinq, sans compter une partie faite en consultation.',
          visual: 'figure',
          draw: 'Un parapluie au trait au-dessus d’une silhouette\u202f; à côté, une pile de pièces au bleu bille, et une croix de soin en pointillé, la prévention faite en consultation.',
          emphasis: ['9,2\u00a0milliards'],
          figure: {
            value: '9,2\u00a0Md€',
            label: 'Dépenses de prévention repérées dans les comptes de la santé en 2025 (+6,8\u00a0% en un an, du fait de la hausse des dépenses de vaccination)\u00a0; une partie de la prévention faite en consultation est comptée dans les soins de ville ou d’hôpital',
            date: '2025',
            sourceIndex: 3,
          },
        },
        {
          id: 'sante-intro-06',
          say: 'Alors, quatre questions se posent. Comment mieux accéder aux soins\u202f? Qui rembourse quoi\u202f? Comment accompagner le grand âge\u202f? Et quelle place pour la prévention\u202f?',
          visual: 'question',
          draw: 'Quatre pictogrammes en grille, dessinés l’un après l’autre\u00a0: une croix de soin, un porte-monnaie, un fauteuil, un parapluie.',
          emphasis: ['accéder aux soins', 'Qui rembourse quoi', 'le grand âge'],
        },
        {
          id: 'sante-intro-07',
          say: 'Dans les vidéos suivantes, on regarde chacune de ces questions de plus près.',
          visual: 'outro',
          draw: 'Les quatre pictogrammes se rangent en file, comme les chapitres d’un carnet.',
          emphasis: ['de plus près'],
        },
      ],
      sources: [
        {
          title: 'Le dispositif du médecin traitant',
          url: 'https://www.ccomptes.fr/fr/publications/le-dispositif-du-medecin-traitant',
          publisher: 'Cour des comptes',
          date: '2026-09-30',
        },
        {
          title: 'Les dépenses de santé en 2025 – édition 2026 (Panorama)',
          url: 'https://drees.solidarites-sante.gouv.fr/publications-communique-de-presse-infographie-documents-de-reference/261001-les-d%C3%A9penses-de-sant%C3%A9-en-2025-edition-2026-panorama-de-la-drees',
          publisher: 'DREES',
          date: '2026-10-01',
        },
        {
          title: 'Les chiffres clés de l’aide à l’autonomie 2026',
          url: 'https://www.cnsa.fr/sites/default/files/2026-06/PUB-CNSA-CC2026-WEB-ACCESS.pdf',
          publisher: 'CNSA',
          date: '2026-06-30',
        },
        {
          title: 'Les dépenses de santé en 2025, édition 2026 – Fiche 27\u00a0: Les dépenses de prévention',
          url: 'https://drees.solidarites-sante.gouv.fr/sites/default/files/2026-09/CNS2026%20-%20Fiche%2027%20-%20Les%20d%C3%A9penses%20de%20pr%C3%A9vention.pdf',
          publisher: 'DREES',
          date: '2026-10-01',
        },
      ],
    },
    {
      id: 'sante-acces',
      kind: 'deep',
      questionIds: ['sante-1'],
      title: 'Comment mieux accéder aux soins\u202f?',
      short: 'Accès aux soins',
      register: 'vous',
      segments: [
        {
          id: 'sante-acces-01',
          say: 'Vous cherchez un médecin traitant, celui que vous déclarez pour vous suivre. En trouverez-vous un près de chez vous\u202f?',
          visual: 'hook',
          draw: 'Une personne au trait\u202f; une flèche en pointillé mène à la porte d’un cabinet marquée d’une croix de soin, puis à un point d’interrogation.',
          emphasis: ['médecin traitant', 'près de chez vous'],
        },
        {
          id: 'sante-acces-02',
          say: 'En 2025, 6,3\u00a0millions d’assurés adultes n’en avaient pas\u00a0: plus d’un adulte sur 10.',
          spoken: 'En deux mille vingt-cinq, six virgule trois millions d’assurés adultes n’en avaient pas : plus d’un adulte sur dix.',
          visual: 'figure',
          draw: 'Dix silhouettes en deux rangées, chacune avec sa petite croix de soin\u202f; la dixième passe au bleu bille, sa croix en pointillé.',
          emphasis: ['6,3\u00a0millions', 'plus d’un adulte sur 10'],
          figure: {
            value: '6,3\u00a0millions',
            label: 'Assurés adultes sans médecin traitant en 2025\u00a0; 88,5\u00a0% de la population adulte en avait déclaré un',
            date: '2025',
            sourceIndex: 0,
          },
        },
        {
          id: 'sante-acces-03',
          say: 'Et cela dépend des lieux. Les 10\u00a0% d’habitants les mieux pourvus ont 4,3\u00a0fois plus accès aux généralistes que les 10\u00a0% les moins pourvus.',
          spoken: 'Et cela dépend des lieux. Les dix pour cent d’habitants les mieux pourvus ont quatre virgule trois fois plus accès aux généralistes que les dix pour cent les moins pourvus.',
          visual: 'compare',
          draw: 'Deux barres à la même échelle\u00a0: celle des mieux pourvus 4,3\u00a0fois plus longue que celle des moins pourvus.',
          alt: 'Deux barres à la même échelle\u00a0: 4,3 pour les 10\u00a0% les mieux pourvus, 1 pour les 10\u00a0% les moins pourvus.',
          emphasis: ['4,3\u00a0fois plus'],
          figure: {
            value: '4,3\u00a0fois',
            label: 'Accessibilité aux généralistes des 10\u00a0% les mieux pourvus par rapport aux 10\u00a0% les moins pourvus (France, 2024)\u00a0; en moyenne, chaque habitant a accès à 3,3\u00a0consultations par an',
            date: '2024',
            sourceIndex: 1,
          },
        },
        {
          id: 'sante-acces-04',
          say: 'Premières installations de généralistes à leur compte\u00a0: 2\u202f130 en 2024, 2\u202f810 en 2025. Là où ils manquent le plus, près de 45\u00a0% de plus qu’en 2024.',
          spoken: 'Premières installations de généralistes à leur compte : deux mille cent trente en deux mille vingt-quatre, deux mille huit cent dix en deux mille vingt-cinq. Là où ils manquent le plus, près de quarante-cinq pour cent de plus qu’en deux mille vingt-quatre.',
          visual: 'figure',
          draw: 'Deux colonnes au trait, 2024 et 2025, la seconde plus haute\u202f; dessous, la phrase sur les zones où les médecins manquent le plus.',
          emphasis: ['2\u202f130', '2\u202f810', 'près de 45\u00a0%'],
          figure: {
            value: '2\u202f810',
            label: 'Médecins généralistes installés pour la première fois en libéral en 2025, contre 2\u202f130 en 2024 (année où ce nombre avait baissé de 9,8\u00a0%)\u00a0; dans les zones d’intervention prioritaire, où les médecins manquent le plus, 891\u00a0installations, près de 45\u00a0% de plus qu’en 2024',
            date: '2025',
            sourceIndex: 2,
          },
        },
        {
          id: 'sante-acces-05',
          say: 'Une proposition de loi adoptée par l’Assemblée nationale prévoit une autorisation pour s’installer. De droit là où les médecins manquent\u202f; ailleurs, seulement au départ d’un médecin de la même spécialité.',
          visual: 'point',
          draw: 'Deux zones côte à côte\u00a0: à gauche, un médecin entre librement, l’autorisation accordée de droit\u202f; à droite, un médecin entre quand un autre sort.',
          alt: 'Deux zones\u00a0: là où les médecins manquent, et ailleurs.',
          emphasis: ['une autorisation', 'De droit', 'au départ d’un médecin'],
        },
        {
          id: 'sante-acces-06',
          say: 'En commission, les sénateurs l’ont remplacée par une condition. Un généraliste qui s’installe là où les médecins sont nombreux s’engage à exercer aussi, à temps partiel, là où ils manquent.',
          visual: 'point',
          draw: 'Les deux zones\u00a0: un médecin installé là où les médecins sont nombreux fait, en pointillé, l’aller vers l’autre zone, où il s’engage à exercer\u202f; dessous, un calendrier au bleu bille, à temps partiel.',
          emphasis: ['une condition', 'à temps partiel'],
        },
        {
          id: 'sante-acces-07',
          say: 'L’examen au Sénat, commencé le 11\u00a0juin 2026, a été suspendu. Autorisation d’un côté, engagement de l’autre\u00a0: les deux versions du texte.',
          spoken: 'L’examen au Sénat, commencé le onze juin deux mille vingt-six, a été suspendu. Autorisation d’un côté, engagement de l’autre : les deux versions du texte.',
          visual: 'compare',
          draw: 'Une balance au fléau horizontal\u00a0: une clé d’un côté, un document de l’autre\u202f; un signe pause sur le pied.',
          alt: 'Une balance au fléau horizontal\u00a0: l’autorisation d’un côté, l’engagement de l’autre\u202f; un signe pause sur le pied.',
          emphasis: ['suspendu', 'Autorisation', 'engagement'],
        },
        {
          id: 'sante-acces-08',
          say: 'Côté hôpital, en 2019, 59,2\u00a0% de ce que l’Assurance maladie versait aux hôpitaux publics dépendait de leur activité. C’est un tarif par séjour ou par acte.',
          spoken: 'Côté hôpital, en deux mille dix-neuf, cinquante-neuf virgule deux pour cent de ce que l’Assurance maladie versait aux hôpitaux publics dépendait de leur activité. C’est un tarif par séjour ou par acte.',
          visual: 'figure',
          draw: 'Un disque, ce que l’Assurance maladie verse aux hôpitaux publics\u202f; un peu plus de la moitié se hachure au bleu bille, payée selon l’activité.',
          alt: 'Un disque, les versements de l’Assurance maladie aux hôpitaux publics\u00a0: la part payée selon l’activité.',
          emphasis: ['59,2\u00a0%', 'un tarif par séjour ou par acte'],
          figure: {
            value: '59,2\u00a0%',
            label: 'Part de ce que l’assurance maladie verse aux hôpitaux publics qui dépend de l’activité, en 2019 (recettes tarifaires\u00a0: un tarif fixé pour chaque séjour ou acte, la «\u00a0tarification à l’activité\u00a0»)\u00a0; 69,2\u00a0% dans le privé non lucratif et 81,4\u00a0% dans le privé lucratif',
            date: '2019',
            sourceIndex: 4,
          },
          chart: {
            kind: 'compare',
            unit: '%',
            items: [
              { label: 'Hôpitaux publics', value: 59.2 },
              { label: 'Privé non lucratif', value: 69.2 },
              { label: 'Privé lucratif', value: 81.4 },
            ],
          },
        },
        {
          id: 'sante-acces-09',
          say: 'En 2025, près de 3\u202f880 ruptures ou risques de rupture ont été déclarés pour des médicaments d’intérêt thérapeutique majeur. Surtout faute de capacités de production suffisantes, ou parce que les ventes augmentent.',
          spoken: 'En deux mille vingt-cinq, près de trois mille huit cent quatre-vingts ruptures ou risques de rupture ont été déclarés pour des médicaments d’intérêt thérapeutique majeur. Surtout faute de capacités de production suffisantes, ou parce que les ventes augmentent.',
          visual: 'figure',
          draw: 'Deux gélules, l’une en pointillé\u202f; à côté, une usine et une flèche de hausse, les deux causes.',
          emphasis: ['près de 3\u202f880', 'capacités de production', 'les ventes augmentent'],
          figure: {
            value: 'près de 3\u202f880',
            label: 'Déclarations de ruptures ou de risques de rupture de médicaments d’intérêt thérapeutique majeur en 2025, un niveau stable par rapport à 2024\u00a0; principales causes\u00a0: capacités de production insuffisantes ou hausse des ventes',
            date: '2025',
            sourceIndex: 5,
          },
        },
        {
          id: 'sante-acces-10',
          say: 'Médecins, hôpital, médicaments\u00a0: quelle priorité pour mieux accéder aux soins\u202f?',
          visual: 'question',
          draw: 'Une croix de soin, un hôpital et une gélule en rang, suivis d’un point d’interrogation.',
          emphasis: ['quelle priorité'],
        },
      ],
      sources: [
        {
          title: 'Le dispositif du médecin traitant',
          url: 'https://www.ccomptes.fr/fr/publications/le-dispositif-du-medecin-traitant',
          publisher: 'Cour des comptes',
          date: '2026-09-30',
        },
        {
          title: 'Accessibilité aux soins de premier recours en 2024',
          url: 'https://drees.solidarites-sante.gouv.fr/communique-de-presse-jeux-de-donnees/jeux-de-donnees/260722-accessibilite-aux-soins-de-premier-recours-en-2024',
          publisher: 'DREES',
          date: '2026-07-22',
        },
        {
          title: 'Observatoire de l’accès aux soins\u00a0: les résultats 2025 témoignent d’une dynamique positive sur l’ensemble du territoire',
          url: 'https://www.assurance-maladie.ameli.fr/presse/2026-06-11-cp-observatoire-de-l-acces-aux-soins',
          publisher: 'Assurance maladie',
          date: '2026-06-11',
        },
        {
          title: 'Proposition de loi visant à lutter contre les déserts médicaux, d’initiative transpartisane (la loi en clair)',
          url: 'https://www.senat.fr/travaux-parlementaires/textes-legislatifs/la-loi-en-clair/proposition-de-loi-visant-a-lutter-contre-les-deserts-medicaux-dinitiative-transpartisane.html',
          publisher: 'Sénat',
          date: '2026-06',
        },
        {
          title: 'La tarification à l’activité',
          url: 'https://www.ccomptes.fr/fr/publications/la-tarification-lactivite',
          publisher: 'Cour des comptes',
          date: '2023-07-28',
        },
        {
          title: 'Rapport d’activité 2025 – Une mobilisation constante pour assurer la disponibilité des produits de santé',
          url: 'https://ansm.sante.fr/qui-sommes-nous/rapport-dactivite-2025/rapport-dactivite-2025/p/une-mobilisation-constante-pour-assurer-la-disponibilite-des-produits-de-sante',
          publisher: 'ANSM',
          date: '2026-07',
        },
      ],
    },
    {
      id: 'sante-remboursements',
      kind: 'deep',
      questionIds: ['sante-2'],
      title: 'Qui rembourse vos soins\u202f?',
      short: 'Remboursements',
      register: 'vous',
      segments: [
        {
          id: 'sante-remboursements-01',
          say: 'Une consultation, des lunettes, des soins dentaires. Qui paie la facture\u202f?',
          visual: 'hook',
          draw: 'Trois pictogrammes au trait, l’un après l’autre\u00a0: une croix de soin, une paire de lunettes, une dent\u202f; puis un point d’interrogation.',
          emphasis: ['Qui paie la facture'],
        },
        {
          id: 'sante-remboursements-02',
          say: 'La plupart des soins sont payés à trois\u00a0: la Sécurité sociale, une complémentaire santé, comme une mutuelle, et vous.',
          visual: 'point',
          draw: 'Une facture au trait\u202f; trois flèches de même taille en partent vers trois payeurs\u00a0: un monument, un parapluie, une personne.',
          emphasis: ['la Sécurité sociale', 'une complémentaire santé', 'et vous'],
        },
        {
          id: 'sante-remboursements-03',
          say: 'Les complémentaires paient 12,3\u00a0% des dépenses de santé. Mais 69\u00a0% de l’optique, 48\u00a0% des appareils auditifs, 46\u00a0% du dentaire.',
          spoken: 'Les complémentaires paient douze virgule trois pour cent des dépenses de santé. Mais soixante-neuf pour cent de l’optique, quarante-huit pour cent des appareils auditifs, quarante-six pour cent du dentaire.',
          visual: 'figure',
          draw: 'Quatre barres à la même échelle, de zéro à cent\u00a0: toutes les dépenses de santé, puis l’optique, les appareils auditifs, le dentaire.',
          alt: 'Quatre barres à la même échelle, sur 100\u00a0%.',
          emphasis: ['12,3\u00a0%', '69\u00a0%'],
          figure: {
            value: '12,3\u00a0%',
            label: 'Part de la dépense courante de santé financée par les complémentaires en 2025 (au sens international)\u00a0; elles prennent en charge 69\u00a0% de l’optique, 48\u00a0% des audioprothèses et 46\u00a0% des soins et prothèses dentaires',
            date: '2025',
            sourceIndex: 0,
          },
          chart: {
            kind: 'compare',
            unit: '%',
            items: [
              { label: 'Dépense courante de santé', value: 12.3 },
              { label: 'Optique', value: 69 },
              { label: 'Audioprothèses', value: 48 },
              { label: 'Soins et prothèses dentaires', value: 46 },
            ],
          },
        },
        {
          id: 'sante-remboursements-04',
          say: 'Reste ce que paient les ménages\u00a0: en France, 9,7\u00a0% en 2025, 495\u00a0euros par habitant. Moyenne de l’Union européenne\u00a0: 14,8\u00a0%, dernière année disponible.',
          spoken: 'Reste ce que paient les ménages : en France, neuf virgule sept pour cent en deux mille vingt-cinq, quatre cent quatre-vingt-quinze euros par habitant. Moyenne de l’Union européenne : quatorze virgule huit pour cent, dernière année disponible.',
          visual: 'compare',
          draw: 'Deux disques de même taille, la France et l’Union européenne\u202f; dans chacun, la part qui reste aux ménages se hachure au bleu bille.',
          alt: 'Deux disques de même taille\u00a0: la part des dépenses de santé qui reste aux ménages, en France et en moyenne dans l’Union européenne.',
          emphasis: ['9,7\u00a0%', '495\u00a0euros', '14,8\u00a0%'],
          figure: {
            value: '9,7\u00a0%',
            label: 'Part de la dépense courante de santé qui reste à payer par les ménages en 2025, soit 495\u00a0€ par habitant\u00a0; moyenne de l’Union européenne\u00a0: 14,8\u00a0% (dernière année disponible). La France est parmi les pays où ce reste à charge est le plus faible, après le Luxembourg et la Croatie',
            date: '2025',
            sourceIndex: 0,
          },
        },
        {
          id: 'sante-remboursements-05',
          say: 'Tout employeur privé doit offrir une complémentaire à ses salariés, et en payer au moins la moitié.',
          visual: 'point',
          draw: 'Un parapluie au-dessus d’une pièce coupée en deux\u202f; la moitié côté employeur, au bleu bille, l’autre côté salariés.',
          emphasis: ['au moins la moitié'],
        },
        {
          id: 'sante-remboursements-06',
          say: 'En 2023, 44\u00a0% de la population avait un contrat d’entreprise ou de la fonction publique, 42\u00a0% un contrat individuel. Et 11\u00a0% la complémentaire santé solidaire, réservée aux revenus modestes.',
          spoken: 'En deux mille vingt-trois, quarante-quatre pour cent de la population avait un contrat d’entreprise ou de la fonction publique, quarante-deux pour cent un contrat individuel. Et onze pour cent la complémentaire santé solidaire, réservée aux revenus modestes.',
          visual: 'compare',
          draw: 'Trois barres à la même échelle, de zéro à cent\u00a0: contrat d’entreprise ou de la fonction publique, contrat individuel, complémentaire santé solidaire.',
          alt: 'Trois barres à la même échelle, sur 100\u00a0%.',
          emphasis: ['44\u00a0%', '42\u00a0%', '11\u00a0%'],
        },
        {
          id: 'sante-remboursements-07',
          say: 'Sans aucune complémentaire\u00a0: 3,4\u00a0% de la population, 7\u00a0% des personnes sous le seuil de pauvreté.',
          spoken: 'Sans aucune complémentaire : trois virgule quatre pour cent de la population, sept pour cent des personnes sous le seuil de pauvreté.',
          visual: 'figure',
          draw: 'Deux grilles de cent cases côte à côte\u00a0: dans la première, un peu plus de trois cases au bleu bille\u202f; dans la seconde, sept.',
          alt: 'Deux grilles de 100 cases\u00a0: 3,4 cases comptées pour la population, 7 pour les personnes sous le seuil de pauvreté.',
          emphasis: ['3,4\u00a0%', '7\u00a0%'],
          figure: {
            value: '3,4\u00a0%',
            label: 'Part de la population sans complémentaire santé en 2023, en France hors Mayotte\u00a0; 7\u00a0% parmi les personnes sous le seuil de pauvreté',
            date: '2023',
            sourceIndex: 1,
          },
          chart: {
            kind: 'compare',
            unit: '%',
            items: [
              { label: 'Ensemble de la population', value: 3.4 },
              { label: 'Sous le seuil de pauvreté', value: 7 },
            ],
          },
        },
        {
          id: 'sante-remboursements-08',
          say: 'Gérer tout cela coûte 17,6\u00a0milliards d’euros en 2025. Dont 9,2 pour les complémentaires, 7,2 pour la Sécurité sociale.',
          spoken: 'Gérer tout cela coûte dix-sept virgule six milliards d’euros en deux mille vingt-cinq. Dont neuf virgule deux pour les complémentaires, sept virgule deux pour la Sécurité sociale.',
          visual: 'figure',
          draw: 'Une barre des frais de gestion, partagée en trois\u00a0: les complémentaires, la Sécurité sociale, et un reste en pointillé, l’État et ses agences.',
          alt: 'Une barre de 17,6\u00a0milliards\u00a0: 9,2 pour les complémentaires, 7,2 pour la Sécurité sociale, le reste pour le ministère et les agences.',
          emphasis: ['17,6\u00a0milliards', '9,2', '7,2'],
          figure: {
            value: '9,2\u00a0Md€ et 7,2\u00a0Md€',
            label: 'Frais de gestion en santé des complémentaires et des régimes de Sécurité sociale en 2025, sur 17,6\u00a0Md€ de dépenses de gestion du système de santé (52\u00a0% et 41\u00a0% du total\u00a0; le reste\u00a0: ministère et agences)',
            date: '2025',
            sourceIndex: 2,
          },
          chart: {
            kind: 'compare',
            unit: 'Md€',
            items: [
              { label: 'Complémentaires', value: 9.2 },
              { label: 'Sécurité sociale', value: 7.2 },
            ],
          },
        },
        {
          id: 'sante-remboursements-09',
          say: 'En 2022, le Haut Conseil pour l’avenir de l’assurance maladie a étudié plusieurs scénarios. Dans l’un d’eux, la Sécurité sociale rembourse aussi le reste du tarif, et les dépenses nécessaires en optique, dentaire et audition.',
          spoken: 'En deux mille vingt-deux, le Haut Conseil pour l’avenir de l’assurance maladie a étudié plusieurs scénarios. Dans l’un d’eux, la Sécurité sociale rembourse aussi le reste du tarif, et les dépenses nécessaires en optique, dentaire et audition.',
          visual: 'point',
          draw: 'L’un des scénarios étudiés\u00a0: la Sécurité sociale, un monument au trait\u202f; vers elle glissent le reste du tarif, la part qu’elle laisse aujourd’hui, puis des lunettes, une dent et une onde sonore.',
          emphasis: ['plusieurs scénarios', 'le reste du tarif'],
        },
        {
          id: 'sante-remboursements-10',
          say: 'Selon ce chiffrage, 18,8\u00a0milliards d’euros de dépenses publiques en plus, 5,4\u00a0milliards de frais de gestion en moins. Des prélèvements obligatoires remplacent une partie des cotisations aux complémentaires.',
          spoken: 'Selon ce chiffrage, dix-huit virgule huit milliards d’euros de dépenses publiques en plus, cinq virgule quatre milliards de frais de gestion en moins. Des prélèvements obligatoires remplacent une partie des cotisations aux complémentaires.',
          visual: 'compare',
          draw: 'Deux effets l’un sous l’autre, de même taille\u00a0: des pièces et une flèche de hausse, les dépenses publiques\u202f; un document et une flèche de baisse, les frais de gestion.',
          emphasis: ['18,8\u00a0milliards', '5,4\u00a0milliards'],
          figure: {
            value: '+18,8\u00a0Md€',
            label: 'Dépenses publiques en plus dans un scénario du Haut Conseil pour l’avenir de l’assurance maladie (2022)\u00a0: la Sécurité sociale y rembourse aussi le ticket modérateur (la part du tarif qu’elle ne prend pas en charge aujourd’hui) et les dépenses nécessaires d’optique, de dentaire et d’audioprothèses\u00a0; des prélèvements obligatoires remplacent alors une partie des cotisations aux complémentaires\u00a0; les frais de gestion baissent de 5,4\u00a0Md€\u00a0; la réforme est favorable aux 8 premiers dixièmes de la population et coûteuse pour les 2 derniers',
            date: 'janvier 2022',
            sourceIndex: 4,
          },
        },
        {
          id: 'sante-remboursements-11',
          say: 'Alors, qui doit payer quoi\u202f?',
          visual: 'question',
          draw: 'Les trois payeurs en rang, un monument, un parapluie, une personne, suivis d’un point d’interrogation.',
          emphasis: ['qui doit payer quoi'],
        },
      ],
      sources: [
        {
          title: 'Les dépenses de santé en 2025 – édition 2026 (Panorama)',
          url: 'https://drees.solidarites-sante.gouv.fr/publications-communique-de-presse-infographie-documents-de-reference/261001-les-d%C3%A9penses-de-sant%C3%A9-en-2025-edition-2026-panorama-de-la-drees',
          publisher: 'DREES',
          date: '2026-10-01',
        },
        {
          title: 'En 2023, les personnes sous le seuil de pauvreté restent bien plus souvent sans complémentaire santé que les autres (Les Dossiers de la DREES n°\u00a0137)',
          url: 'https://drees.solidarites-sante.gouv.fr/publications-communique-de-presse/les-dossiers-de-la-drees/260401_DD_compl%C3%A9mentaire_sant%C3%A9',
          publisher: 'DREES',
          date: '2026-04-01',
        },
        {
          title: 'Les dépenses de santé en 2025, édition 2026 – Fiche 28\u00a0: Les dépenses de gestion du système de santé',
          url: 'https://drees.solidarites-sante.gouv.fr/sites/default/files/2026-09/CNS2026%20-%20Fiche%2028%20-%20Les%20d%C3%A9penses%20de%20gestion%20du%20syst%C3%A8me%20de%20sant%C3%A9.pdf',
          publisher: 'DREES',
          date: '2026-10-01',
        },
        {
          title: 'Complémentaire santé d’entreprise (mutuelle santé)',
          url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F20739',
          publisher: 'Service-public.fr (DILA)',
          date: '2024-05-15',
        },
        {
          title: 'Sécurité sociale\u00a0: la boîte à outils du Sénat (reprise du rapport du HCAAM «\u00a0Quatre scénarios polaires d’évolution de l’articulation entre Sécurité sociale et assurance maladie complémentaire\u00a0»)',
          url: 'https://www.senat.fr/rap/r24-901/r24-90136.html',
          publisher: 'Sénat',
          date: '2025-09-23',
        },
      ],
    },
    {
      id: 'sante-age',
      kind: 'deep',
      questionIds: ['sante-3'],
      title: 'Accompagner le grand âge',
      short: 'Grand âge',
      register: 'vous',
      segments: [
        {
          id: 'sante-age-01',
          say: 'Un proche âgé ne peut plus vivre seul sans aide. Où l’accompagner\u00a0: chez lui, ou en établissement\u202f?',
          visual: 'hook',
          draw: 'Un fauteuil au milieu\u202f; d’un côté une maison, de l’autre un établissement, deux flèches en pointillé, un point d’interrogation au-dessus.',
          emphasis: ['chez lui', 'en établissement'],
        },
        {
          id: 'sante-age-02',
          say: 'Dès 60\u00a0ans, les départements versent une aide à qui perd son autonomie\u00a0: l’allocation personnalisée d’autonomie. Fin 2024, 7,4\u00a0% des 60\u00a0ans ou plus la touchent.',
          spoken: 'Dès soixante ans, les départements versent une aide à qui perd son autonomie : l’allocation personnalisée d’autonomie. Fin deux mille vingt-quatre, sept virgule quatre pour cent des soixante ans ou plus la touchent.',
          visual: 'figure',
          draw: 'Un disque, toutes les personnes de 60\u00a0ans ou plus\u202f; une fine part au bleu bille, celles qui touchent l’allocation, un fauteuil à côté.',
          alt: 'Un disque, les 60\u00a0ans ou plus\u00a0: la part qui touche l’allocation.',
          emphasis: ['7,4\u00a0%'],
          figure: {
            value: '7,4\u00a0%',
            label: 'Part des personnes de 60\u00a0ans ou plus qui bénéficient de l’allocation personnalisée d’autonomie (APA), fin 2024. Le besoin d’aide est mesuré sur une grille nationale\u00a0: seuls les niveaux GIR 1 à 4 y donnent droit\u00a0; le montant dépend aussi des revenus et du plan d’aide',
            date: 'fin 2024',
            sourceIndex: 0,
          },
        },
        {
          id: 'sante-age-03',
          say: 'Fin 2023, les Ehpad, les établissements pour personnes âgées dépendantes, offraient 609\u202f970\u00a0places. Près de la moitié dans le public, le reste dans le privé, lucratif ou non.',
          spoken: 'Fin deux mille vingt-trois, les Ehpad, les établissements pour personnes âgées dépendantes, offraient six cent neuf mille neuf cent soixante-dix places. Près de la moitié dans le public, le reste dans le privé, lucratif ou non.',
          visual: 'figure',
          draw: 'Une barre des places partagée en trois, à l’échelle\u00a0: le public, près de la moitié, marqué d’une accolade au bleu bille\u202f; puis le privé non lucratif et le privé lucratif.',
          alt: 'Une barre à l’échelle\u00a0: 292\u202f840\u00a0places dans le public, 179\u202f440 dans le privé non lucratif, 137\u202f690 dans le privé lucratif.',
          emphasis: ['609\u202f970\u00a0places', 'Près de la moitié'],
          figure: {
            value: '609\u202f970\u00a0places',
            label: 'Places en Ehpad fin 2023\u00a0: 292\u202f840 dans le public, 179\u202f440 dans le privé non lucratif et 137\u202f690 dans le privé lucratif (France métropolitaine et DROM)',
            date: 'fin 2023',
            sourceIndex: 1,
          },
          chart: {
            kind: 'compare',
            unit: 'places',
            items: [
              { label: 'Public', value: 292840 },
              { label: 'Privé non lucratif', value: 179440 },
              { label: 'Privé lucratif', value: 137690 },
            ],
          },
        },
        {
          id: 'sante-age-04',
          say: 'À la même date, 697\u202f000 personnes étaient accueillies en établissement pour personnes âgées. C’est 4,5\u00a0% de moins qu’en 2019. Et 85\u00a0% étaient en perte d’autonomie.',
          spoken: 'À la même date, six cent quatre-vingt-dix-sept mille personnes étaient accueillies en établissement pour personnes âgées. C’est quatre virgule cinq pour cent de moins qu’en deux mille dix-neuf. Et quatre-vingt-cinq pour cent étaient en perte d’autonomie.',
          visual: 'figure',
          draw: 'Une grille de cent cases\u202f; quatre-vingt-cinq passent au bleu bille, les résidents en perte d’autonomie.',
          emphasis: ['697\u202f000', '4,5\u00a0% de moins', '85\u00a0%'],
          figure: {
            value: '697\u202f000',
            label: 'Personnes vivant ou accueillies dans un établissement pour personnes âgées fin 2023, soit 4,5\u00a0% de moins qu’en 2019\u00a0; 85\u00a0% des résidents sont en perte d’autonomie',
            date: 'fin 2023',
            sourceIndex: 2,
          },
        },
        {
          id: 'sante-age-05',
          say: 'Selon la statistique publique, ce recul pourrait venir d’un «\u00a0virage domiciliaire\u00a0», la volonté de privilégier le domicile. Ou d’un recul de la perte d’autonomie.',
          visual: 'point',
          draw: 'Deux hypothèses côte à côte, de même taille\u00a0: une maison\u202f; une silhouette et une flèche de baisse.',
          emphasis: ['virage domiciliaire', 'recul de la perte d’autonomie'],
        },
        {
          id: 'sante-age-06',
          say: 'Fin 2024, en nombre de bénéficiaires, 56\u00a0% des aides des départements aux personnes âgées allaient au domicile, surtout l’allocation d’autonomie. Et 44\u00a0% à l’accueil en établissement.',
          spoken: 'Fin deux mille vingt-quatre, en nombre de bénéficiaires, cinquante-six pour cent des aides des départements aux personnes âgées allaient au domicile, surtout l’allocation d’autonomie. Et quarante-quatre pour cent à l’accueil en établissement.',
          visual: 'compare',
          draw: 'Une maison et un établissement au-dessus d’une barre partagée à l’échelle\u00a0: 56 côté domicile, 44 côté établissement.',
          emphasis: ['56\u00a0%', '44\u00a0%'],
          figure: {
            value: '56\u00a0%',
            label: 'Part des bénéficiaires des aides sociales des départements aux personnes âgées aidés à domicile (850\u202f959), surtout par l’APA\u00a0; 44\u00a0% pour l’accueil en établissement (676\u202f563)',
            date: '31\u00a0décembre 2024',
            sourceIndex: 0,
          },
          chart: {
            kind: 'compare',
            unit: '%',
            items: [
              { label: 'Aides à domicile', value: 56 },
              { label: 'Accueil en établissement', value: 44 },
            ],
          },
        },
        {
          id: 'sante-age-07',
          say: 'Fin 2023, en Ehpad, pour 100\u00a0places, on comptait 66\u00a0équivalents temps plein, tous métiers confondus. Dont 29 au chevet\u00a0: infirmiers et aides-soignants, un niveau stable depuis 2019.',
          spoken: 'Fin deux mille vingt-trois, en Ehpad, pour cent places, on comptait soixante-six équivalents temps plein, tous métiers confondus. Dont vingt-neuf au chevet : infirmiers et aides-soignants, un niveau stable depuis deux mille dix-neuf.',
          visual: 'figure',
          draw: 'Deux barres à la même échelle, jusqu’au repère des 100\u00a0places\u00a0: tous métiers, puis au chevet, au bleu bille.',
          alt: 'Deux barres à la même échelle, jusqu’au repère des 100\u00a0places\u00a0: 66 tous métiers, 29 au chevet.',
          emphasis: ['66\u00a0équivalents temps plein', 'Dont 29 au chevet'],
          figure: {
            value: '66\u00a0ETP pour 100\u00a0places',
            label: 'Personnel des Ehpad en équivalents temps plein (ETP) fin 2023, tous métiers confondus (France métropolitaine et DROM)\u00a0; le personnel «\u00a0au chevet\u00a0» (infirmiers et aides-soignants)\u00a0: 29\u00a0ETP pour 100\u00a0places, un niveau stable depuis 2019',
            date: 'fin 2023',
            sourceIndex: 1,
          },
          chart: {
            kind: 'compare',
            unit: 'ETP pour 100 places',
            items: [
              { label: 'Tous métiers confondus', value: 66 },
              { label: 'Infirmiers et aides-soignants', value: 29 },
            ],
          },
        },
        {
          id: 'sante-age-08',
          say: 'En 2024, la perte d’autonomie des personnes âgées a mobilisé 31,1\u00a0milliards d’euros d’argent public. 79\u00a0% viennent de la Sécurité sociale, 16\u00a0% des départements, 5\u00a0% de l’État.',
          spoken: 'En deux mille vingt-quatre, la perte d’autonomie des personnes âgées a mobilisé trente et un virgule un milliards d’euros d’argent public. Soixante-dix-neuf pour cent viennent de la Sécurité sociale, seize pour cent des départements, cinq pour cent de l’État.',
          visual: 'figure',
          draw: 'Trois barres à la même échelle, de zéro à cent\u00a0: la Sécurité sociale, les départements, l’État.',
          alt: 'Trois barres à la même échelle, sur 100\u00a0%.',
          emphasis: ['31,1\u00a0milliards', '79\u00a0%'],
          figure: {
            value: '31,1\u00a0Md€',
            label: 'Argent public consacré en 2024 à la perte d’autonomie des personnes âgées\u00a0: 79\u00a0% par la Sécurité sociale, 16\u00a0% par les départements, 5\u00a0% par l’État, sans compter les dépenses des personnes elles-mêmes ni celles de leurs proches',
            date: '2024',
            sourceIndex: 0,
          },
          chart: {
            kind: 'compare',
            unit: '%',
            items: [
              { label: 'Sécurité sociale', value: 79 },
              { label: 'Départements', value: 16 },
              { label: 'État', value: 5 },
            ],
          },
        },
        {
          id: 'sante-age-09',
          say: 'Alors, où accompagner le grand âge, avec combien de soignants, et avec quel financement\u202f?',
          visual: 'question',
          draw: 'Une maison, un établissement, une silhouette et une pile de pièces en rang, suivis d’un point d’interrogation.',
          emphasis: ['où accompagner', 'combien de soignants', 'quel financement'],
        },
      ],
      sources: [
        {
          title: 'Les chiffres clés de l’aide à l’autonomie 2026',
          url: 'https://www.cnsa.fr/sites/default/files/2026-06/PUB-CNSA-CC2026-WEB-ACCESS.pdf',
          publisher: 'CNSA',
          date: '2026-06-30',
        },
        {
          title: 'L’aide sociale aux personnes âgées ou handicapées, édition 2025 – Fiche\u00a0: Les établissements d’hébergement pour personnes âgées',
          url: 'https://drees.solidarites-sante.gouv.fr/sites/default/files/2025-09/PAPH%20-%20Fiche%2009%20-%20Les%20%C3%A9tablissements%20d%E2%80%99h%C3%A9bergement%20pour%20personnes%20%C3%A2g%C3%A9es_0.pdf',
          publisher: 'DREES',
          date: '2025-09',
        },
        {
          title: 'Établissements d’hébergement pour personnes âgées\u00a0: des résidents aussi âgés et autant en perte d’autonomie qu’en 2019, mais moins nombreux (Études et résultats n°\u00a01351)',
          url: 'https://drees.solidarites-sante.gouv.fr/sites/default/files/2025-11/ER%201351%20EHPA-MEL.pdf',
          publisher: 'DREES',
          date: '2025-11-04',
        },
      ],
    },
    {
      id: 'sante-prevention',
      kind: 'deep',
      questionIds: ['sante-x1'],
      title: 'Quelle place pour la prévention\u202f?',
      short: 'Prévention',
      register: 'vous',
      segments: [
        {
          id: 'sante-prevention-01',
          say: 'Mieux manger, respirer un air sain, se faire vacciner\u00a0: la prévention cherche à éviter les maladies, plutôt qu’à les soigner.',
          visual: 'hook',
          draw: 'Trois pictogrammes au trait, l’un après l’autre\u00a0: une pomme, une fenêtre, une seringue.',
          emphasis: ['éviter les maladies'],
        },
        {
          id: 'sante-prevention-02',
          say: 'En 2025, les comptes de la santé repèrent 9,2\u00a0milliards d’euros de prévention, sans compter une partie faite en consultation. C’est 6,8\u00a0% de plus en un an, du fait de la hausse des dépenses de vaccination.',
          spoken: 'En deux mille vingt-cinq, les comptes de la santé repèrent neuf virgule deux milliards d’euros de prévention, sans compter une partie faite en consultation. C’est six virgule huit pour cent de plus en un an, du fait de la hausse des dépenses de vaccination.',
          visual: 'figure',
          draw: 'Un parapluie et une pile de pièces au bleu bille\u202f; à côté, une seringue et une flèche de hausse.',
          emphasis: ['9,2\u00a0milliards', '6,8\u00a0%'],
          figure: {
            value: '9,2\u00a0Md€',
            label: 'Dépenses de prévention repérées dans les comptes de la santé en 2025 (+6,8\u00a0% en un an, du fait de la hausse des dépenses de vaccination)\u00a0; une partie de la prévention faite en consultation est comptée dans les soins de ville ou d’hôpital',
            date: '2025',
            sourceIndex: 0,
          },
        },
        {
          id: 'sante-prevention-03',
          say: 'Côté budget, les dépenses de l’assurance maladie se votent pour un an. Chaque automne, le Parlement fixe un objectif pour les soins de ville et l’hôpital, à ne pas dépasser.',
          visual: 'point',
          draw: 'Une ligne du temps en trois années\u202f; au début de chacune, un document voté, et au-dessus un plafond hachuré à ne pas dépasser.',
          alt: 'Trois années à la suite\u00a0: chacune commence par un texte voté, sous un plafond.',
          emphasis: ['pour un an', 'Chaque automne'],
        },
        {
          id: 'sante-prevention-04',
          say: 'Côté alimentation, le Nutri-Score note les aliments de A à E. Le droit européen le permet à titre volontaire\u00a0: chaque entreprise choisit de l’afficher ou non.',
          visual: 'point',
          draw: 'Deux paquets au trait\u00a0: l’un porte une échelle de cinq cases, de A à E\u202f; sur l’autre, la même échelle en pointillé.',
          alt: 'Une échelle de cinq cases\u00a0: A, B, C, D, E.',
          emphasis: ['de A à E', 'volontaire'],
        },
        {
          id: 'sante-prevention-05',
          say: 'En juin 2024, 1\u202f377\u00a0entreprises s’étaient engagées à l’afficher, contre 1\u202f197 un an plus tôt. Leurs marques font 62\u00a0% des volumes vendus de produits transformés en grandes surfaces.',
          spoken: 'En juin deux mille vingt-quatre, mille trois cent soixante-dix-sept entreprises s’étaient engagées à l’afficher, contre mille cent quatre-vingt-dix-sept un an plus tôt. Leurs marques font soixante-deux pour cent des volumes vendus de produits transformés en grandes surfaces.',
          visual: 'figure',
          draw: 'Deux colonnes au trait, un an plus tôt et juin 2024, la seconde un peu plus haute\u202f; dessous, la phrase sur les volumes vendus.',
          emphasis: ['1\u202f377\u00a0entreprises', '1\u202f197', '62\u00a0%'],
          figure: {
            value: '1\u202f377\u00a0entreprises',
            label: 'Entreprises engagées dans la démarche Nutri-Score en France en juin 2024, contre 1\u202f197 en juin 2023\u00a0; leurs marques représentent 62\u00a0% des volumes de ventes des produits transformés en grandes surfaces, une part stable depuis 2023',
            date: 'juin 2024',
            sourceIndex: 2,
          },
          chart: {
            kind: 'series',
            unit: 'entreprises',
            items: [
              { label: 'Juin 2023', value: 1197 },
              { label: 'Juin 2024', value: 1377 },
            ],
          },
        },
        {
          id: 'sante-prevention-06',
          say: 'Côté air intérieur, depuis 2023, crèches, écoles, collèges et lycées doivent évaluer chaque année leur aération, avec une mesure du CO₂. Ils doivent aussi établir un plan d’actions.',
          spoken: 'Côté air intérieur, depuis deux mille vingt-trois, crèches, écoles, collèges et lycées doivent évaluer chaque année leur aération, avec une mesure du C.O. deux. Ils doivent aussi établir un plan d’actions.',
          visual: 'point',
          draw: 'Une école au trait reliée à un capteur marqué CO₂\u202f; à côté, un calendrier, puis le document du plan d’actions.',
          emphasis: ['chaque année', 'un plan d’actions'],
        },
        {
          id: 'sante-prevention-07',
          say: 'La pollution de l’air intérieur coûterait près de 19\u00a0milliards d’euros par an à la société. C’est l’estimation d’une étude exploratoire publique de 2014, sur des données de 2003 à 2005.',
          spoken: 'La pollution de l’air intérieur coûterait près de dix-neuf milliards d’euros par an à la société. C’est l’estimation d’une étude exploratoire publique de deux mille quatorze, sur des données de deux mille trois à deux mille cinq.',
          visual: 'figure',
          draw: 'Une ligne du temps\u00a0: les années des données, de 2003 à 2005, hachurées\u202f; un petit drapeau à 2014, l’année de l’étude.',
          emphasis: ['près de 19\u00a0milliards', 'de 2003 à 2005'],
          figure: {
            value: 'près de 19\u00a0Md€ par an',
            label: 'Coût socio-économique estimé de la pollution de l’air intérieur en France, d’après une étude exploratoire de l’Anses et de l’Observatoire de la qualité de l’air intérieur publiée en avril 2014, sur des données d’exposition de 2003-2005 et cinq polluants',
            date: 'avril 2014',
            sourceIndex: 5,
          },
        },
        {
          id: 'sante-prevention-08',
          say: 'Budgets, alimentation, air intérieur\u00a0: quelle priorité pour la prévention\u202f?',
          visual: 'question',
          draw: 'Un calendrier, une pomme et une fenêtre en rang, suivis d’un point d’interrogation.',
          emphasis: ['quelle priorité'],
        },
      ],
      sources: [
        {
          title: 'Les dépenses de santé en 2025, édition 2026 – Fiche 27\u00a0: Les dépenses de prévention',
          url: 'https://drees.solidarites-sante.gouv.fr/sites/default/files/2026-09/CNS2026%20-%20Fiche%2027%20-%20Les%20d%C3%A9penses%20de%20pr%C3%A9vention.pdf',
          publisher: 'DREES',
          date: '2026-10-01',
        },
        {
          title: 'Loi de financement de la sécurité sociale\u00a0: présentation',
          url: 'https://www.securite-sociale.fr/la-secu-en-detail/loi-de-financement/presentation',
          publisher: 'Direction de la Sécurité sociale (securite-sociale.fr)',
        },
        {
          title: 'Suivi du Nutri-Score par l’Oqali – Bilan annuel – Édition 2024',
          url: 'https://www.oqali.fr/media/2025/01/OQALI-2024_Suivi-du-Nutri-Score.pdf',
          publisher: 'Oqali (observatoire public de l’alimentation, INRAE-Anses)',
          date: '2025-01',
        },
        {
          title: 'Nutri-Score',
          url: 'https://www.santepubliquefrance.fr/nutrition-et-activite-physique/nutri-score',
          publisher: 'Santé publique France',
          date: '2026-03-19',
        },
        {
          title: 'Qualité de l’air intérieur',
          url: 'https://www.ecologie.gouv.fr/politiques-publiques/qualite-lair-interieur',
          publisher: 'Ministère de la Transition écologique',
          date: '2025-04-24',
        },
        {
          title: 'Coût socio-économique de la pollution de l’air intérieur',
          url: 'https://www.oqei.fr/fr/campagnes/cout-socio-economique-de-la-pollution-de-l-air-interieur',
          publisher: 'Observatoire de la qualité de l’environnement intérieur (OQEI, ex-OQAI)',
          date: '2014-04',
        },
      ],
    },
  ],
}
