// Série « Sécurité et justice » (famille « Sécurité et justice ») : l'introduction, puis quatre approfondissements
// (la police, le trafic de drogue, la justice pénale, les blocages de lycées), un par question de la banque.
// Rédigée d'après les fiches du thème seulement (research/choisir-2027/explainers.json, explainer-charts.json) ;
// règles d'écriture : ../GUIDE-SERIES.md ; planches : ../pistes/planches/securite_justice.tsx.
// Ne pas toucher aux identifiants ni aux textes dits sans raison : changer un « say » ou un « spoken », c'est
// devoir réenregistrer la voix du passage.
// Datée : blocages de lycées de l'automne 2026 ; amende forfaitaire pour usage de stupéfiants de 500 € depuis le
// 20 août 2026 ; chiffres de l'incarcération au 1er septembre 2026 ; effectifs visés par le projet de budget
// 2026. À revoir après octobre 2026.

import type { VideoSeries } from '../types'

export const SECURITE_JUSTICE: VideoSeries = {
  topicId: 'securite_justice',
  familyId: 'justice',
  label: 'Sécurité et justice',
  videos: [
    {
      id: 'securite-intro',
      kind: 'intro',
      questionIds: ['securite_justice-1', 'securite_justice-2', 'securite_justice-3', 'securite_justice-4'],
      title: 'Sécurité et justice, l’essentiel',
      short: 'Introduction',
      register: 'vous',
      segments: [
        {
          id: 'securite-intro-01',
          say: 'En croisant un policier ou un gendarme dans la rue, vous sentez-vous en confiance, ou sur vos gardes\u202f?',
          visual: 'hook',
          draw: 'Une personne au trait, et en face d’elle un bouclier, signe de la police\u202f; entre les deux, un point d’interrogation.',
          emphasis: ['en confiance', 'sur vos gardes'],
        },
        {
          id: 'securite-intro-02',
          say: 'Selon le Défenseur des droits, en présence d’un policier ou d’un gendarme, 50\u00a0% des habitants se disent confiants ou rassurés. 28\u00a0% se disent indifférents, 22\u00a0% méfiants ou inquiets.',
          spoken: 'Selon le Défenseur des droits, en présence d’un policier ou d’un gendarme, cinquante pour cent des habitants se disent confiants ou rassurés. Vingt-huit pour cent se disent indifférents, vingt-deux pour cent méfiants ou inquiets.',
          visual: 'figure',
          draw: 'Trois barres au trait, à la même échelle depuis zéro\u00a0: confiants ou rassurés, indifférents, méfiants ou inquiets.',
          alt: 'Trois barres à la même échelle\u00a0: confiants ou rassurés, 50\u00a0%\u202f; indifférents, 28\u00a0%\u202f; méfiants ou inquiets, 22\u00a0%.',
          emphasis: ['50\u00a0%', '28\u00a0%', '22\u00a0%'],
          figure: {
            value: '50\u00a0%',
            label: 'Habitants qui se disent confiants ou rassurés en présence d’un policier ou d’un gendarme sur la voie publique\u202f; 28\u00a0% se disent indifférents et 22\u00a0% méfiants ou inquiets (France métropolitaine, 18-79\u00a0ans)',
            date: 'enquête d’octobre 2024 à janvier 2025',
            sourceIndex: 0,
          },
          chart: {
            kind: 'compare',
            unit: '%',
            items: [
              { label: 'Confiants ou rassurés', value: 50 },
              { label: 'Indifférents', value: 28 },
              { label: 'Méfiants ou inquiets', value: 22 },
            ],
          },
        },
        {
          id: 'securite-intro-03',
          say: 'En 2025, la police et la gendarmerie ont enregistré 472\u202f956\u00a0victimes de violences physiques. Plus de la moitié dans le cadre familial.',
          spoken: 'En deux mille vingt-cinq, la police et la gendarmerie ont enregistré quatre cent soixante-douze mille neuf cent cinquante-six victimes de violences physiques. Plus de la moitié dans le cadre familial.',
          visual: 'figure',
          draw: 'Un disque au trait pour l’ensemble des victimes enregistrées\u202f; la part du cadre familial, un peu plus de la moitié, se hachure.',
          alt: 'Un disque\u00a0: la part des victimes dans le cadre familial, 256\u202f863 sur 472\u202f956.',
          emphasis: ['472\u202f956\u00a0victimes', 'Plus de la moitié'],
          figure: {
            value: '472\u202f956',
            label: 'Victimes de violences physiques enregistrées par la police et la gendarmerie en 2025, contre 449\u202f819 en 2024\u202f; plus de la moitié (256\u202f863) dans le cadre familial (France métropolitaine et départements d’outre-mer)',
            date: '2025',
            sourceIndex: 1,
          },
          chart: {
            kind: 'compare',
            items: [
              { label: 'Ensemble des victimes', value: 472956 },
              { label: 'Dont dans le cadre familial', value: 256863 },
            ],
          },
        },
        {
          id: 'securite-intro-04',
          say: 'Ces chiffres ne comptent que les faits enregistrés\u00a0: après une plainte, un signalement, ou à l’initiative des forces de l’ordre. Selon le ministère de l’Intérieur, ils donnent une idée du volume réel surtout pour les faits que les victimes signalent souvent, comme les cambriolages.',
          visual: 'point',
          draw: 'Trois flèches entrent dans un registre ouvert\u00a0: une plainte, un signalement, l’initiative des forces de l’ordre.',
          emphasis: ['les faits enregistrés', 'signalent souvent'],
        },
        {
          id: 'securite-intro-05',
          say: 'Le trafic de drogues, lui, représente au moins 3,5\u00a0milliards d’euros par an en France, selon une estimation basse citée par le Sénat.',
          spoken: 'Le trafic de drogues, lui, représente au moins trois virgule cinq milliards d’euros par an en France, selon une estimation basse citée par le Sénat.',
          visual: 'figure',
          draw: 'Une pile de billets posée sur un plancher hachuré, «\u00a0au moins\u00a0»\u202f; à côté, un calendrier, «\u00a0par an\u00a0».',
          emphasis: ['3,5\u00a0milliards'],
          figure: {
            value: '3,5\u00a0Md€',
            label: 'Chiffre d’affaires annuel minimal du trafic de drogues (toutes drogues) en France\u00a0: estimation basse avancée par le ministre de l’Économie devant la commission d’enquête du Sénat',
            date: '2024',
            sourceIndex: 2,
          },
        },
        {
          id: 'securite-intro-06',
          say: 'Au 1er\u00a0septembre 2026, les prisons comptaient 90\u202f020\u00a0détenus pour 63\u202f348\u00a0places. Plus de 142\u00a0détenus pour 100\u00a0places.',
          spoken: 'Au premier septembre deux mille vingt-six, les prisons comptaient quatre-vingt-dix mille vingt détenus pour soixante-trois mille trois cent quarante-huit places. Plus de cent quarante-deux détenus pour cent places.',
          visual: 'figure',
          draw: 'Deux barres à la même échelle, les places et les détenus\u202f; ce qui dépasse le nombre de places se hachure.',
          alt: 'Deux barres à la même échelle\u00a0: 63\u202f348 places, 90\u202f020 détenus\u202f; ce qui dépasse le nombre de places est hachuré.',
          emphasis: ['90\u202f020\u00a0détenus', '63\u202f348\u00a0places'],
          figure: {
            value: '142,1\u00a0%',
            label: 'Densité carcérale (détenus rapportés aux places)\u00a0: 90\u202f020 détenus pour 63\u202f348 places, contre 134,7\u00a0% un an plus tôt\u202f; 8\u202f347 détenus dorment sur un matelas au sol (France entière)',
            date: '1er\u00a0septembre 2026',
            sourceIndex: 3,
          },
          chart: {
            kind: 'compare',
            items: [
              { label: 'Détenus', value: 90020 },
              { label: 'Places', value: 63348 },
            ],
          },
        },
        {
          id: 'securite-intro-07',
          say: 'Alors, quatre questions se posent. Quelle priorité pour la police\u202f? Comment lutter contre le trafic de drogue\u202f? Quelle orientation pour la justice pénale\u202f? Et comment répondre aux blocages de lycées\u202f?',
          visual: 'question',
          draw: 'Quatre pictogrammes en grille, dessinés l’un après l’autre\u00a0: un bouclier, des billets, un palais de justice, un lycée.',
          emphasis: ['la police', 'le trafic de drogue', 'la justice pénale'],
        },
        {
          id: 'securite-intro-08',
          say: 'Ce sont les quatre sujets des vidéos qui suivent.',
          visual: 'outro',
          draw: 'Les quatre pictogrammes se rangent en file, comme les chapitres d’un carnet.',
        },
      ],
      sources: [
        {
          title: 'Relations police/population\u00a0: contrôles d’identité et dépôts de plainte – Enquête Accès aux droits, 2e\u00a0édition, volume\u00a01 (dossier de presse)',
          url: 'https://www.defenseurdesdroits.fr/sites/default/files/2025-07/ddd_EAD-2024_volume-1_relations-police-population_DP.pdf',
          publisher: 'Défenseur des droits',
          date: '2025-06',
        },
        {
          title: 'Base nationale des caractéristiques des victimes enregistrées par la police et la gendarmerie nationales (fichier xlsx)',
          url: 'https://static.data.gouv.fr/resources/principales-caracteristiques-des-victimes-enregistrees-et-des-mis-en-cause-pour-des-infractions-elucidees-par-la-police-et-la-gendarmerie-nationales/20260129-160110/donnee-nat-caract-victimes-data.gouv-2025-produit-le-29012026.xlsx',
          publisher: 'Ministère de l’Intérieur – SSMSI (data.gouv.fr)',
          date: '2026-01-29',
        },
        {
          title: 'L’essentiel sur le rapport de la commission d’enquête sur l’impact du narcotrafic en France (rapport n°\u00a0588, 2023-2024)',
          url: 'https://www.senat.fr/rap/r23-588-1/r23-588-1-syn.pdf',
          publisher: 'Sénat',
          date: '2024-05-07',
        },
        {
          title: 'Mesure de l’incarcération – Indicateurs clés au 1er\u00a0septembre 2026',
          url: 'https://www.justice.gouv.fr/sites/default/files/2026-10/mesure_mensuelle_01092026.pdf',
          publisher: 'Ministère de la Justice – Direction de l’administration pénitentiaire',
          date: '2026-10',
        },
        {
          title: 'Présentation du jeu de données «\u00a0Principales caractéristiques des victimes enregistrées et des mis en cause\u00a0» (SSMSI)',
          url: 'https://static.data.gouv.fr/resources/principales-caracteristiques-des-victimes-enregistrees-et-des-mis-en-cause-pour-des-infractions-elucidees-par-la-police-et-la-gendarmerie-nationales/20260129-113555/metadonnees-victimes-mec-caract-ssmsi-29012026.pdf',
          publisher: 'Ministère de l’Intérieur – SSMSI (data.gouv.fr)',
          date: '2026-01-29',
        },
      ],
    },
    {
      id: 'securite-police',
      kind: 'deep',
      questionIds: ['securite_justice-1'],
      title: 'Quelle priorité pour la police\u202f?',
      short: 'Police',
      register: 'vous',
      segments: [
        {
          id: 'securite-police-01',
          say: 'Policiers et gendarmes patrouillent, contrôlent, interviennent. Avec quels moyens, et selon quelles règles\u202f?',
          visual: 'hook',
          draw: 'Trois pictogrammes au trait, l’un après l’autre\u00a0: une voiture de patrouille, une carte d’identité, un bouclier.',
          emphasis: ['quels moyens', 'quelles règles'],
        },
        {
          id: 'securite-police-02',
          say: 'Côté moyens, le Sénat relève un objectif de hausse des effectifs de 2023 à 2027. Pour la police, 3\u202f872\u00a0postes de plus\u202f; pour la gendarmerie, 3\u202f540.',
          spoken: 'Côté moyens, le Sénat relève un objectif de hausse des effectifs de deux mille vingt-trois à deux mille vingt-sept. Pour la police, trois mille huit cent soixante-douze postes de plus ; pour la gendarmerie, trois mille cinq cent quarante.',
          visual: 'figure',
          draw: 'Deux barres au trait à la même échelle, la police et la gendarmerie, leur hausse écrite au bout.',
          emphasis: ['3\u202f872\u00a0postes', '3\u202f540'],
          figure: {
            value: '+3\u202f872',
            label: 'Postes de policiers (équivalents temps plein) visés entre 2023 et 2027, et +3\u202f540 dans la gendarmerie, selon la trajectoire liée à la loi de programmation du ministère de l’Intérieur relevée par le Sénat (ces cibles ne sont pas inscrites dans la loi elle-même). Après un gel en 2025, le projet de budget 2026 prévoyait +1\u202f000\u00a0postes dans la police et +400 dans la gendarmerie',
            date: '2023-2027',
            sourceIndex: 0,
          },
          chart: {
            kind: 'compare',
            unit: 'postes',
            items: [
              { label: 'Hausse visée, police', value: 3872 },
              { label: 'Hausse visée, gendarmerie', value: 3540 },
            ],
          },
        },
        {
          id: 'securite-police-03',
          say: 'Pour l’usage de leurs armes, la loi fixe cinq cas depuis 2017. Et une condition\u00a0: «\u00a0en cas d’absolue nécessité et de manière strictement proportionnée\u00a0».',
          spoken: 'Pour l’usage de leurs armes, la loi fixe cinq cas depuis deux mille dix-sept. Et une condition : « en cas d’absolue nécessité et de manière strictement proportionnée ».',
          visual: 'point',
          draw: 'Un texte de loi au trait, daté\u202f; dessous, cinq cases qui se cochent une à une.',
          emphasis: ['cinq cas', 'absolue nécessité'],
        },
        {
          id: 'securite-police-04',
          say: 'L’un de ces cas\u00a0: un conducteur qui refuse de s’arrêter. Il faut alors qu’on ne puisse pas immobiliser le véhicule autrement. Et que ses occupants soient susceptibles, dans leur fuite, de porter atteinte à la vie ou à l’intégrité physique des agents ou d’autrui.',
          visual: 'point',
          draw: 'Une voiture au trait passe une ligne d’arrêt sans s’arrêter\u202f; dessous, deux conditions qui se cochent l’une après l’autre.',
          emphasis: ['refuse de s’arrêter'],
        },
        {
          id: 'securite-police-05',
          say: 'Les contrôles d’identité ont progressé. Selon le Défenseur des droits, 16\u00a0% des personnes disaient en 2016 avoir été contrôlées au moins une fois en cinq ans. En 2024, 26\u00a0%.',
          spoken: 'Les contrôles d’identité ont progressé. Selon le Défenseur des droits, seize pour cent des personnes disaient en deux mille seize avoir été contrôlées au moins une fois en cinq ans. En deux mille vingt-quatre, vingt-six pour cent.',
          visual: 'timeline',
          draw: 'Deux colonnes au trait depuis zéro, datées 2016 et 2024, la seconde plus haute.',
          emphasis: ['16\u00a0%', '26\u00a0%'],
          figure: {
            value: '26\u00a0%',
            label: 'Personnes qui disent avoir été contrôlées au moins une fois en cinq ans, contre 16\u00a0% en 2016 (France métropolitaine, 18-79\u00a0ans)',
            date: 'enquête d’octobre 2024 à janvier 2025',
            sourceIndex: 1,
          },
        },
        {
          id: 'securite-police-06',
          say: 'Et selon la même enquête, les jeunes hommes perçus comme noirs, arabes ou maghrébins ont 4\u00a0fois plus de risque d’avoir été contrôlés que le reste de la population.',
          spoken: 'Et selon la même enquête, les jeunes hommes perçus comme noirs, arabes ou maghrébins ont quatre fois plus de risque d’avoir été contrôlés que le reste de la population.',
          visual: 'compare',
          draw: 'Deux rangées\u00a0: une personne et une carte d’identité pour le reste de la population\u202f; une personne et quatre cartes pour l’autre groupe.',
          alt: 'Deux rangées de cartes d’identité\u00a0: une pour le reste de la population, quatre pour les jeunes hommes perçus comme noirs, arabes ou maghrébins.',
          emphasis: ['4\u00a0fois plus'],
          figure: {
            value: '4\u00a0fois',
            label: 'Risque d’avoir été contrôlés, par rapport au reste de la population, pour les jeunes hommes perçus comme noirs, arabes ou maghrébins (France métropolitaine, 18-79\u00a0ans)',
            date: 'enquête d’octobre 2024 à janvier 2025',
            sourceIndex: 1,
          },
        },
        {
          id: 'securite-police-07',
          say: 'Les caméras ont aussi leurs règles. Dans les établissements scolaires, elles peuvent filmer les entrées, les sorties et les lieux de passage. Mais sauf cas exceptionnels, la CNIL exclut la cour, la classe ou la cantine pendant les heures d’ouverture, au nom de la vie privée.',
          spoken: 'Les caméras ont aussi leurs règles. Dans les établissements scolaires, elles peuvent filmer les entrées, les sorties et les lieux de passage. Mais sauf cas exceptionnels, la Cnil exclut la cour, la classe ou la cantine pendant les heures d’ouverture, au nom de la vie privée.',
          visual: 'point',
          draw: 'Le plan d’un établissement scolaire au trait\u00a0: une caméra près de l’entrée, dans les lieux de passage\u202f; dans la cour, la classe et la cantine, des caméras barrées.',
          emphasis: ['les entrées', 'la cour, la classe ou la cantine'],
        },
        {
          id: 'securite-police-08',
          say: 'D’un côté, les moyens\u00a0: effectifs, caméras. De l’autre, les pratiques\u00a0: contrôles, usage de la force. Deux leviers, qui peuvent se combiner.',
          visual: 'compare',
          draw: 'Une balance au fléau horizontal\u00a0: un bouclier et une caméra sur un plateau, une carte d’identité et un texte de loi sur l’autre.',
          emphasis: ['les moyens', 'les pratiques'],
        },
        {
          id: 'securite-police-09',
          say: 'Alors, quelle priorité pour la police et la sécurité du quotidien\u202f?',
          visual: 'question',
          draw: 'Le bouclier du début, et un point d’interrogation à côté.',
          emphasis: ['quelle priorité'],
        },
      ],
      sources: [
        {
          title: 'Projet de loi de finances pour 2026\u00a0: Sécurités (Gendarmerie nationale – Police nationale) – Rapport général n°\u00a0139 (2025-2026), tome\u00a0III, annexe\u00a028',
          url: 'https://www.senat.fr/rap/l25-139-328-1/l25-139-328-1_mono.html',
          publisher: 'Sénat – commission des finances',
          date: '2025-11-24',
        },
        {
          title: 'Relations police/population\u00a0: contrôles d’identité et dépôts de plainte – Enquête Accès aux droits, 2e\u00a0édition, volume\u00a01 (dossier de presse)',
          url: 'https://www.defenseurdesdroits.fr/sites/default/files/2025-07/ddd_EAD-2024_volume-1_relations-police-population_DP.pdf',
          publisher: 'Défenseur des droits',
          date: '2025-06',
        },
        {
          title: 'Code de la sécurité intérieure, article L435-1',
          url: 'https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000034107970',
          publisher: 'Légifrance',
          date: 'en vigueur depuis le 2\u00a0mars 2017',
        },
        {
          title: 'Les dispositifs vidéo dans les établissements scolaires',
          url: 'https://www.cnil.fr/fr/la-videosurveillance-videoprotection-dans-les-etablissements-scolaires',
          publisher: 'Commission nationale de l’informatique et des libertés (CNIL)',
          date: '2025-09-12',
        },
      ],
    },
    {
      id: 'securite-drogues',
      kind: 'deep',
      questionIds: ['securite_justice-2'],
      title: 'Comment lutter contre le trafic de drogue\u202f?',
      short: 'Trafic de drogue',
      register: 'vous',
      segments: [
        {
          id: 'securite-drogues-01',
          say: 'Le cannabis est interdit en France. Mais le trafic de drogues fait vivre des réseaux criminels. Que pèse ce trafic\u202f?',
          visual: 'hook',
          draw: 'Un texte de loi marqué «\u00a0interdit\u00a0»\u202f; une flèche en pointillé file vers une liasse de billets, puis un point d’interrogation.',
          emphasis: ['interdit', 'Que pèse ce trafic'],
        },
        {
          id: 'securite-drogues-02',
          say: 'Selon une estimation basse citée par le Sénat, le trafic de drogues représente au moins 3,5\u00a0milliards d’euros par an en France. Toutes drogues confondues.',
          spoken: 'Selon une estimation basse citée par le Sénat, le trafic de drogues représente au moins trois virgule cinq milliards d’euros par an en France. Toutes drogues confondues.',
          visual: 'figure',
          draw: 'Une pile de billets posée sur un plancher hachuré, «\u00a0au moins\u00a0»\u202f; à côté, un calendrier, «\u00a0par an\u00a0».',
          emphasis: ['3,5\u00a0milliards'],
          figure: {
            value: '3,5\u00a0Md€',
            label: 'Chiffre d’affaires annuel minimal du trafic de drogues (toutes drogues) en France\u00a0: estimation basse avancée par le ministre de l’Économie devant la commission d’enquête du Sénat',
            date: '2024',
            sourceIndex: 0,
          },
        },
        {
          id: 'securite-drogues-03',
          say: 'Côté consommation, 10,8\u00a0% des 18 à 64\u00a0ans ont consommé du cannabis dans l’année. Un peu plus d’un sur dix, une part stable.',
          spoken: 'Côté consommation, dix virgule huit pour cent des dix-huit à soixante-quatre ans ont consommé du cannabis dans l’année. Un peu plus d’un sur dix, une part stable.',
          visual: 'figure',
          draw: 'Un disque au trait\u202f; une part d’un peu plus d’un dixième se hachure.',
          emphasis: ['10,8\u00a0%', 'un sur dix'],
          figure: {
            value: '10,8\u00a0%',
            label: 'Part des 18-64\u00a0ans qui ont consommé du cannabis dans l’année, une proportion stable. À 17\u00a0ans, 29,9\u00a0% des jeunes en avaient déjà fumé en 2022\u00a0: le niveau le plus bas mesuré depuis 2000, et 20\u00a0points de moins qu’en 2002 (France)',
            date: '2023 (17\u00a0ans\u00a0: 2022)',
            sourceIndex: 1,
          },
          chart: { kind: 'part', value: 10.8, total: 100, unit: '%', whole: 'des 18-64 ans' },
        },
        {
          id: 'securite-drogues-04',
          say: 'À 17\u00a0ans, 29,9\u00a0% des jeunes avaient déjà fumé du cannabis en 2022. C’est le niveau le plus bas mesuré depuis 2000, et 20\u00a0points de moins qu’en 2002.',
          spoken: 'À dix-sept ans, vingt-neuf virgule neuf pour cent des jeunes avaient déjà fumé du cannabis en deux mille vingt-deux. C’est le niveau le plus bas mesuré depuis deux mille, et vingt points de moins qu’en deux mille deux.',
          visual: 'timeline',
          draw: 'Deux colonnes au trait depuis zéro, 2002 et 2022\u202f; la seconde plus basse, l’écart marqué d’une accolade.',
          alt: 'Deux colonnes à la même échelle, 2002 et 2022\u00a0: 29,9\u00a0% en 2022, 20\u00a0points de moins qu’en 2002.',
          emphasis: ['29,9\u00a0%', '20\u00a0points de moins'],
        },
        {
          id: 'securite-drogues-05',
          say: 'L’usage de stupéfiants est un délit\u00a0: jusqu’à un an de prison et 3\u202f750\u00a0euros d’amende. Mais une amende forfaitaire peut mettre fin aux poursuites\u00a0: 500\u00a0euros depuis le 20\u00a0août 2026.',
          spoken: 'L’usage de stupéfiants est un délit : jusqu’à un an de prison et trois mille sept cent cinquante euros d’amende. Mais une amende forfaitaire peut mettre fin aux poursuites : cinq cents euros depuis le vingt août deux mille vingt-six.',
          visual: 'figure',
          draw: 'Deux colonnes au trait\u00a0: un texte de loi pour le délit et sa peine maximale\u202f; un billet pour l’amende forfaitaire, qui clôt les poursuites.',
          emphasis: ['un délit', 'une amende forfaitaire'],
          figure: {
            value: '500\u00a0€',
            label: 'Amende forfaitaire pour usage de stupéfiants depuis le 20\u00a0août 2026 (400\u00a0€ si elle est payée rapidement, 1\u202f000\u00a0€ en cas de retard)\u00a0: son paiement peut mettre fin aux poursuites, y compris en cas de récidive. L’usage est un délit puni d’un an de prison et de 3\u202f750\u00a0€ d’amende',
            date: '2026',
            sourceIndex: 2,
          },
        },
        {
          id: 'securite-drogues-06',
          say: 'La loi du 13\u00a0juin 2025 contre le narcotrafic a créé un parquet national anti-criminalité organisée\u00a0: des procureurs spécialisés. Elle renforce aussi la lutte contre le blanchiment, et facilite le gel, c’est-à-dire le blocage, des avoirs des trafiquants.',
          spoken: 'La loi du treize juin deux mille vingt-cinq contre le narcotrafic a créé un parquet national anti-criminalité organisée : des procureurs spécialisés. Elle renforce aussi la lutte contre le blanchiment, et facilite le gel, c’est-à-dire le blocage, des avoirs des trafiquants.',
          visual: 'point',
          draw: 'Un texte de loi daté\u202f; une flèche vers un palais de justice, le parquet\u202f; puis une pile de pièces fermée d’un cadenas.',
          emphasis: ['des procureurs spécialisés', 'le gel'],
        },
        {
          id: 'securite-drogues-07',
          say: 'En 2023, 117\u00a0millions d’euros d’avoirs liés au trafic de stupéfiants ont été saisis. C’est 14\u00a0% de toutes les saisies de la police et de la gendarmerie.',
          spoken: 'En deux mille vingt-trois, cent dix-sept millions d’euros d’avoirs liés au trafic de stupéfiants ont été saisis. C’est quatorze pour cent de toutes les saisies de la police et de la gendarmerie.',
          visual: 'figure',
          draw: 'Cent pièces en dix rangées, toutes les saisies\u202f; quatorze se comptent au bleu bille.',
          emphasis: ['117\u00a0millions', '14\u00a0%'],
          figure: {
            value: '117\u00a0M€',
            label: 'Avoirs saisis en lien avec le trafic de stupéfiants, soit 14\u00a0% de l’ensemble des saisies de la police et de la gendarmerie',
            date: '2023',
            sourceIndex: 0,
          },
        },
        {
          id: 'securite-drogues-08',
          say: 'D’un côté, moins de jeunes ont déjà essayé le cannabis. De l’autre, le trafic rapporte des milliards d’euros.',
          visual: 'compare',
          draw: 'Une balance au fléau horizontal\u00a0: une personne et une flèche qui descend sur un plateau, une liasse de billets sur l’autre.',
          emphasis: ['moins de jeunes', 'des milliards d’euros'],
        },
        {
          id: 'securite-drogues-09',
          say: 'Alors, comment affaiblir les réseaux du trafic de drogue\u202f?',
          visual: 'question',
          draw: 'Une liasse de billets reliée à quelques points en réseau, et un point d’interrogation.',
          emphasis: ['affaiblir les réseaux'],
        },
      ],
      sources: [
        {
          title: 'L’essentiel sur le rapport de la commission d’enquête sur l’impact du narcotrafic en France (rapport n°\u00a0588, 2023-2024)',
          url: 'https://www.senat.fr/rap/r23-588-1/r23-588-1-syn.pdf',
          publisher: 'Sénat',
          date: '2024-05-07',
        },
        {
          title: 'Cannabis (résine, herbe, huile, CBD) – synthèse des connaissances',
          url: 'https://www.ofdt.fr/cannabis-resine-herbe-huile-cbd-synthese-des-connaissances-1724',
          publisher: 'Observatoire français des drogues et des tendances addictives (OFDT)',
        },
        {
          title: 'Code de la santé publique, article L3421-1 (version issue de la loi n°\u00a02026-798 du 18\u00a0août 2026, art.\u00a025)',
          url: 'https://www.legifrance.gouv.fr/codes/section_lc/LEGITEXT000006072665/LEGISCTA000006171219/2026-10-03',
          publisher: 'Légifrance',
          date: 'en vigueur depuis le 20\u00a0août 2026',
        },
        {
          title: 'Proposition de loi visant à sortir la France du piège du narcotrafic – La loi en clair',
          url: 'https://www.senat.fr/travaux-parlementaires/textes-legislatifs/la-loi-en-clair/proposition-de-loi-visant-a-sortir-la-france-du-piege-du-narcotrafic.html',
          publisher: 'Sénat',
          date: '2025-06',
        },
      ],
    },
    {
      id: 'securite-justice',
      kind: 'deep',
      questionIds: ['securite_justice-3'],
      title: 'Quelle orientation pour la justice pénale\u202f?',
      short: 'Justice pénale',
      register: 'vous',
      segments: [
        {
          id: 'securite-justice-01',
          say: 'Une personne est condamnée pour un délit. Quelle peine reçoit-elle, et comment est-elle appliquée\u202f?',
          visual: 'hook',
          draw: 'Un palais de justice au trait, une flèche vers une personne, puis un point d’interrogation.',
          emphasis: ['Quelle peine'],
        },
        {
          id: 'securite-justice-02',
          say: 'En 2024, la justice a prononcé 559\u202f444\u00a0peines et mesures principales. Dont 121\u202f057\u00a0peines de prison au moins en partie ferme\u00a0: un peu plus d’une sur cinq.',
          spoken: 'En deux mille vingt-quatre, la justice a prononcé cinq cent cinquante-neuf mille quatre cent quarante-quatre peines et mesures principales. Dont cent vingt et un mille cinquante-sept peines de prison au moins en partie ferme : un peu plus d’une sur cinq.',
          visual: 'figure',
          draw: 'Cinq feuilles de jugement alignées\u202f; l’une se compte au bleu bille.',
          emphasis: ['121\u202f057\u00a0peines', 'une sur cinq'],
          figure: {
            value: '121\u202f057',
            label: 'Peines de prison en tout ou partie ferme prononcées en 2024, sur 559\u202f444 peines et mesures principales (données provisoires, France)',
            date: '2024',
            sourceIndex: 0,
          },
        },
        {
          id: 'securite-justice-03',
          say: 'Et 14\u202f488\u00a0travaux d’intérêt général\u00a0: un travail non rémunéré, au profit de la collectivité.',
          spoken: 'Et quatorze mille quatre cent quatre-vingt-huit travaux d’intérêt général : un travail non rémunéré, au profit de la collectivité.',
          visual: 'figure',
          draw: 'Trois barres au trait à la même échelle\u00a0: l’ensemble des peines et mesures, la prison au moins en partie ferme, le travail d’intérêt général.',
          alt: 'Trois barres à la même échelle\u00a0: ensemble des peines et mesures, 559\u202f444\u202f; prison en tout ou partie ferme, 121\u202f057\u202f; travail d’intérêt général, 14\u202f488.',
          emphasis: ['14\u202f488', 'non rémunéré'],
          figure: {
            value: '14\u202f488',
            label: 'Peines de travail d’intérêt général (TIG, un travail non rémunéré au profit de la collectivité) prononcées en 2024, et 121\u202f057 peines de prison en tout ou partie ferme, sur 559\u202f444 peines et mesures principales (données provisoires, France)',
            date: '2024',
            sourceIndex: 0,
          },
          chart: {
            kind: 'compare',
            items: [
              { label: 'Ensemble des peines et mesures', value: 559444 },
              { label: 'Prison en tout ou partie ferme', value: 121057 },
              { label: 'Travail d’intérêt général', value: 14488 },
            ],
          },
        },
        {
          id: 'securite-justice-04',
          say: 'Au 1er\u00a0septembre 2026, les prisons comptaient 142,1\u00a0détenus pour 100\u00a0places. Un an plus tôt, 134,7.',
          spoken: 'Au premier septembre deux mille vingt-six, les prisons comptaient cent quarante-deux virgule un détenus pour cent places. Un an plus tôt, cent trente-quatre virgule sept.',
          visual: 'figure',
          draw: 'Deux colonnes au trait depuis zéro, un an plus tôt et au 1er\u00a0septembre 2026, au-dessus d’un trait en pointillé à 100.',
          alt: 'Deux colonnes à la même échelle, 134,7 et 142,1\u00a0détenus, au-dessus d’un trait à 100\u00a0places.',
          emphasis: ['142,1', '134,7'],
          figure: {
            value: '142,1\u00a0%',
            label: 'Densité carcérale (détenus rapportés aux places)\u00a0: 90\u202f020 détenus pour 63\u202f348 places, contre 134,7\u00a0% un an plus tôt\u202f; 8\u202f347 détenus dorment sur un matelas au sol (France entière)',
            date: '1er\u00a0septembre 2026',
            sourceIndex: 1,
          },
        },
        {
          id: 'securite-justice-05',
          say: 'Un plan de 15\u202f000\u00a0places de prison en plus a été annoncé en 2018. À l’automne 2025, il était réalisé à 36,1\u00a0%, selon le Sénat.',
          spoken: 'Un plan de quinze mille places de prison en plus a été annoncé en deux mille dix-huit. À l’automne deux mille vingt-cinq, il était réalisé à trente-six virgule un pour cent, selon le Sénat.',
          visual: 'figure',
          draw: 'Une longue barre au trait pour les 15\u202f000\u00a0places du plan\u202f; un peu plus du tiers se hachure, le reste en pointillé.',
          emphasis: ['15\u202f000\u00a0places', '36,1\u00a0%'],
          figure: {
            value: '36,1\u00a0%',
            label: 'Part réalisée du plan de 15\u202f000 places de prison supplémentaires annoncé en 2018, à l’automne 2025\u00a0: 5\u202f411 places nettes créées, selon la commission des finances du Sénat',
            date: 'automne 2025',
            sourceIndex: 2,
          },
        },
        {
          id: 'securite-justice-06',
          say: 'En 2022, la France comptait 11,3\u00a0juges professionnels pour 100\u202f000\u00a0habitants, contre 17,6 pour la médiane européenne. La loi de programmation pour 2023 à 2027 prévoit 1\u202f500\u00a0magistrats de plus.',
          spoken: 'En deux mille vingt-deux, la France comptait onze virgule trois juges professionnels pour cent mille habitants, contre dix-sept virgule six pour la médiane européenne. La loi de programmation pour deux mille vingt-trois à deux mille vingt-sept prévoit mille cinq cents magistrats de plus.',
          visual: 'compare',
          draw: 'Deux barres au trait à la même échelle, la France et la médiane européenne\u202f; dessous, une flèche qui monte\u00a0: les magistrats prévus en plus.',
          emphasis: ['11,3', '17,6'],
          figure: {
            value: '11,3',
            label: 'Juges professionnels pour 100\u202f000 habitants en France, contre une médiane européenne de 17,6 (données de la Commission européenne pour l’efficacité de la justice du Conseil de l’Europe, reprises par le Sénat)',
            date: '2022',
            sourceIndex: 2,
          },
          chart: {
            kind: 'compare',
            unit: 'juges pour 100 000 habitants',
            items: [
              { label: 'France', value: 11.3 },
              { label: 'Médiane européenne', value: 17.6 },
            ],
          },
        },
        {
          id: 'securite-justice-07',
          say: 'Pour un délit, la récidive légale, c’est commettre le même délit, ou un délit assimilé, dans les cinq ans après la fin d’une précédente peine. La peine maximale encourue est alors doublée.',
          visual: 'timeline',
          draw: 'Une frise\u00a0: une première peine, puis cinq années marquées d’une accolade, et un drapeau pour le même délit\u202f; dessous, la peine maximale qui double.',
          alt: 'Sur une frise, une première peine puis cinq années\u202f; dessous, la peine maximale, doublée.',
          emphasis: ['récidive légale', 'doublée'],
        },
        {
          id: 'securite-justice-08',
          say: 'En 2024, 20,4\u00a0% des personnes condamnées pour un délit étaient en récidive légale. Et 24,1\u00a0%, sans l’être, avaient déjà été condamnées pour un crime ou un délit dans les cinq années précédentes.',
          spoken: 'En deux mille vingt-quatre, vingt virgule quatre pour cent des personnes condamnées pour un délit étaient en récidive légale. Et vingt-quatre virgule un pour cent, sans l’être, avaient déjà été condamnées pour un crime ou un délit dans les cinq années précédentes.',
          visual: 'figure',
          draw: 'Deux barres au trait à la même échelle\u00a0: en récidive légale, déjà condamnées sans être en récidive légale.',
          emphasis: ['20,4\u00a0%', '24,1\u00a0%'],
          figure: {
            value: '20,4\u00a0%',
            label: 'Personnes condamnées pour un délit en 2024 qui étaient en récidive légale\u202f; 24,1\u00a0% étaient «\u00a0réitérantes\u00a0», c’est-à-dire déjà condamnées pour un crime ou un délit dans les cinq années précédentes, sans être en récidive légale (données provisoires, France)',
            date: '2024',
            sourceIndex: 0,
          },
          chart: {
            kind: 'compare',
            unit: '%',
            items: [
              { label: 'En récidive légale', value: 20.4 },
              { label: 'Réitérants', value: 24.1 },
            ],
          },
        },
        {
          id: 'securite-justice-09',
          say: 'D’un côté, des prisons surpeuplées. De l’autre, la récidive légale.',
          visual: 'compare',
          draw: 'Une balance au fléau horizontal\u00a0: une fenêtre de cellule et un matelas sur un plateau, un jugement et une flèche qui tourne en rond sur l’autre.',
          emphasis: ['des prisons surpeuplées', 'la récidive légale'],
        },
        {
          id: 'securite-justice-10',
          say: 'Alors, quelle orientation pour la justice pénale\u202f?',
          visual: 'question',
          draw: 'Le palais de justice du début, et un point d’interrogation à côté.',
          emphasis: ['quelle orientation'],
        },
      ],
      sources: [
        {
          title: 'Les chiffres clés de la justice – Édition 2025 (p.\u00a020 et 21)',
          url: 'https://www.justice.gouv.fr/sites/default/files/2026-03/Chiffres_Cles_2025_corrV2.pdf',
          publisher: 'Ministère de la Justice – SSER',
          date: 'édition 2025 (version corrigée mise en ligne en 2026)',
        },
        {
          title: 'Mesure de l’incarcération – Indicateurs clés au 1er\u00a0septembre 2026',
          url: 'https://www.justice.gouv.fr/sites/default/files/2026-10/mesure_mensuelle_01092026.pdf',
          publisher: 'Ministère de la Justice – Direction de l’administration pénitentiaire',
          date: '2026-10',
        },
        {
          title: 'Projet de loi de finances pour 2026\u00a0: Justice – Rapport général n°\u00a0139 (2025-2026), tome\u00a0III, annexe\u00a017 (d’après CEPEJ, Systèmes judiciaires européens – rapport d’évaluation 2024)',
          url: 'https://www.senat.fr/rap/l25-139-317/l25-139-317_mono.html',
          publisher: 'Sénat – commission des finances',
          date: '2025-11-24',
        },
        {
          title: 'Code pénal, article 132-10',
          url: 'https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000006417367',
          publisher: 'Légifrance',
          date: 'en vigueur depuis le 1er\u00a0mars 1994',
        },
      ],
    },
    {
      id: 'securite-lycees',
      kind: 'deep',
      questionIds: ['securite_justice-4'],
      title: 'Comment répondre aux blocages de lycées\u202f?',
      short: 'Blocages de lycées',
      register: 'vous',
      segments: [
        {
          id: 'securite-lycees-01',
          say: 'À l’automne 2026, des lycées ont été bloqués. Comment répondre à ces blocages\u202f?',
          spoken: 'À l’automne deux mille vingt-six, des lycées ont été bloqués. Comment répondre à ces blocages ?',
          visual: 'hook',
          draw: 'Un lycée au trait, une barrière baissée devant son entrée\u202f; un point d’interrogation à côté.',
          emphasis: ['des lycées ont été bloqués', 'Comment répondre'],
        },
        {
          id: 'securite-lycees-02',
          say: 'À la rentrée 2025, 2\u202f261\u202f051\u00a0élèves étaient au lycée, dans le public et le privé sous contrat.',
          spoken: 'À la rentrée deux mille vingt-cinq, deux millions deux cent soixante et un mille cinquante et un élèves étaient au lycée, dans le public et le privé sous contrat.',
          visual: 'figure',
          draw: 'Un lycée au trait, et à côté une foule de petites silhouettes qui se remplit rangée par rangée.',
          emphasis: ['2\u202f261\u202f051\u00a0élèves'],
          figure: {
            value: '2\u202f261\u202f051',
            label: 'Élèves en lycée (formations générales, technologiques et professionnelles), public et privé sous contrat (France)',
            date: 'rentrée 2025',
            sourceIndex: 0,
          },
        },
        {
          id: 'securite-lycees-03',
          say: 'Au printemps 2023, 91\u00a0% des lycéens disaient se sentir bien, ou tout à fait bien, dans leur lycée. Et 59\u00a0% se disaient plutôt ou très stressés par les examens ou les évaluations.',
          spoken: 'Au printemps deux mille vingt-trois, quatre-vingt-onze pour cent des lycéens disaient se sentir bien, ou tout à fait bien, dans leur lycée. Et cinquante-neuf pour cent se disaient plutôt ou très stressés par les examens ou les évaluations.',
          visual: 'figure',
          draw: 'Deux barres au trait à la même échelle\u00a0: se sentir bien dans son lycée, être stressé par les examens.',
          emphasis: ['91\u00a0%', '59\u00a0%'],
          figure: {
            value: '91\u00a0%',
            label: 'Lycéens qui disent se sentir «\u00a0bien\u00a0» ou «\u00a0tout à fait bien\u00a0» dans leur lycée\u202f; 59\u00a0% se disent «\u00a0plutôt\u00a0» ou «\u00a0très\u00a0» stressés par les examens ou les évaluations (France, lycées publics et privés sous contrat)',
            date: 'printemps 2023',
            sourceIndex: 0,
          },
          chart: { kind: 'part', value: 91, total: 100, unit: '%', whole: 'des lycéens' },
        },
        {
          id: 'securite-lycees-04',
          say: 'Au lycée, les élèves ont la liberté d’information et d’expression. Mais la loi précise que «\u00a0l’exercice de ces libertés ne peut porter atteinte aux activités d’enseignement\u00a0».',
          visual: 'point',
          draw: 'Une pancarte au trait d’un côté, un livre ouvert de l’autre\u202f; entre les deux, une ligne en pointillé.',
          emphasis: ['liberté d’information et d’expression', 'activités d’enseignement'],
        },
        {
          id: 'securite-lycees-05',
          say: 'La Convention internationale des droits de l’enfant, qui engage la France, reconnaît aux moins de 18\u00a0ans la liberté de réunion pacifique. Seule la loi peut la restreindre, quand c’est nécessaire, notamment pour l’ordre public ou les droits d’autrui.',
          spoken: 'La Convention internationale des droits de l’enfant, qui engage la France, reconnaît aux moins de dix-huit ans la liberté de réunion pacifique. Seule la loi peut la restreindre, quand c’est nécessaire, notamment pour l’ordre public ou les droits d’autrui.',
          visual: 'point',
          draw: 'Un texte de convention au trait\u202f; à côté, trois personnes réunies\u202f; puis un cadre en pointillé, celui de la loi, autour d’elles.',
          emphasis: ['la liberté de réunion pacifique', 'Seule la loi'],
        },
        {
          id: 'securite-lycees-06',
          say: 'Et dans chaque lycée public, un conseil des délégués pour la vie lycéenne réunit dix élèves, élus pour deux ans par l’ensemble des élèves. Le chef d’établissement le préside.',
          visual: 'point',
          draw: 'Une table au trait\u00a0: dix élèves autour, comptés au bleu bille, et au bout de la table le chef d’établissement.',
          alt: 'Dix élèves autour d’une table, et le chef d’établissement au bout.',
          emphasis: ['dix élèves', 'deux ans'],
        },
        {
          id: 'securite-lycees-07',
          say: 'La loi punit le fait d’entrer ou de rester sans autorisation dans un établissement scolaire pour en troubler l’ordre. Jusqu’à un an de prison et 7\u202f500\u00a0euros d’amende. Une amende forfaitaire de 500\u00a0euros peut aussi mettre fin aux poursuites.',
          spoken: 'La loi punit le fait d’entrer ou de rester sans autorisation dans un établissement scolaire pour en troubler l’ordre. Jusqu’à un an de prison et sept mille cinq cents euros d’amende. Une amende forfaitaire de cinq cents euros peut aussi mettre fin aux poursuites.',
          visual: 'figure',
          draw: 'Un établissement scolaire au trait, sa porte franchie par une flèche en pointillé\u202f; à côté, un texte de loi et un billet pour l’amende forfaitaire.',
          emphasis: ['un an de prison', '7\u202f500\u00a0euros'],
          figure: {
            value: '1\u00a0an et 7\u202f500\u00a0€',
            label: 'Peine maximale encourue, pour être entré ou s’être maintenu sans autorisation dans un établissement scolaire afin d’en troubler l’ordre\u202f; le paiement d’une amende forfaitaire de 500\u00a0€ peut aussi mettre fin aux poursuites',
            date: 'en vigueur depuis le 26\u00a0janvier 2023',
            sourceIndex: 4,
          },
        },
        {
          id: 'securite-lycees-08',
          say: 'D’un côté, des violences commises en marge des blocages. De l’autre, l’expression et les revendications des lycéens.',
          visual: 'compare',
          draw: 'Une balance au fléau horizontal\u00a0: un bouclier sur un plateau, une pancarte sur l’autre.',
          emphasis: ['des violences commises en marge', 'l’expression et les revendications'],
        },
        {
          id: 'securite-lycees-09',
          say: 'Alors, comment répondre aux blocages de lycées\u202f?',
          visual: 'question',
          draw: 'Le lycée du début, et un point d’interrogation à côté.',
          emphasis: ['comment répondre'],
        },
      ],
      sources: [
        {
          title: 'Repères et références statistiques 2026 (fiches 2.13 et 4.01)',
          url: 'https://www.education.gouv.fr/sites/default/files/document/rers-2026-pdf-519880.pdf',
          publisher: 'Ministère de l’Éducation nationale – DEPP',
          date: '2026',
        },
        {
          title: 'Code de l’éducation, article L511-2',
          url: 'https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000006525120',
          publisher: 'Légifrance',
          date: 'en vigueur depuis le 22\u00a0juin 2000',
        },
        {
          title: 'Convention relative aux droits de l’enfant (articles 1er et 15)',
          url: 'https://www.ohchr.org/fr/instruments-mechanisms/instruments/convention-rights-child',
          publisher: 'Haut-Commissariat des Nations unies aux droits de l’homme (HCDH)',
          date: 'adoptée le 20\u00a0novembre 1989',
        },
        {
          title: 'Code de l’éducation, article R421-43',
          url: 'https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000033124234',
          publisher: 'Légifrance',
          date: 'en vigueur depuis le 19\u00a0septembre 2016',
        },
        {
          title: 'Code pénal, article 431-22',
          url: 'https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000047053426',
          publisher: 'Légifrance',
          date: 'version en vigueur depuis le 26\u00a0janvier 2023',
        },
      ],
    },
  ],
}
