// Série « Solidarités » (famille « Santé, logement, solidarités ») : l'introduction, puis quatre
// approfondissements (assurance chômage, RSA et minima sociaux, contreparties et sanctions, droits des personnes
// handicapées). Matière : les fiches des questions solidarites-x1, -x2 et -x3 (research/choisir-2027/), et rien
// d'autre. Règles d'écriture : ../GUIDE-SERIES.md ; planches : ../pistes/planches/solidarites.tsx.
// Ne pas toucher aux identifiants ni aux textes dits sans raison : changer un « say » ou un « spoken », c'est
// devoir réenregistrer la voix du passage.
// Datée : taux de chômage du deuxième trimestre 2026 (Insee, août 2026), prévisions de l'Unédic de juin 2026,
// montants du RSA et de l'AAH en vigueur en 2026, règle de la rupture conventionnelle du 1er septembre 2026.
// À revoir à la prochaine publication trimestrielle du chômage par l'Insee, ou si ces règles changent.

import type { VideoSeries } from '../types'

export const SOLIDARITES: VideoSeries = {
  topicId: 'solidarites',
  familyId: 'social',
  label: 'Solidarités',
  videos: [
    {
      id: 'solidarites-intro',
      kind: 'intro',
      questionIds: ['solidarites-x1', 'solidarites-x2', 'solidarites-x3'],
      title: 'Les solidarités, l’essentiel',
      short: 'Introduction',
      register: 'vous',
      segments: [
        {
          id: 'solidarites-intro-01',
          say: 'Vous perdez votre emploi, ou vous n’avez presque plus de revenus. Qui prend alors le relais\u202f?',
          visual: 'hook',
          draw: 'Une personne au trait\u202f; à côté, une mallette de travail et un porte-monnaie en pointillé\u202f; une flèche mène à un guichet surmonté d’un point d’interrogation.',
          emphasis: ['Qui prend alors le relais'],
        },
        {
          id: 'solidarites-intro-02',
          say: 'Premier filet, l’assurance chômage\u00a0: elle verse un revenu de remplacement aux salariés qui perdent leur emploi.',
          visual: 'point',
          draw: 'Un filet tendu entre deux piquets\u202f; dessus, une personne dont la mallette de travail s’efface\u202f; une enveloppe d’allocation vient vers elle.',
          emphasis: ['l’assurance chômage', 'revenu de remplacement'],
        },
        {
          id: 'solidarites-intro-03',
          say: 'Second filet, les minima sociaux\u00a0: un revenu minimum, comme le RSA, ou l’AAH pour les adultes handicapés. Chacun a ses propres règles.',
          spoken: 'Second filet, les minima sociaux : un revenu minimum, comme le R.S.A., ou l’A.A.H. pour les adultes handicapés. Chacun a ses propres règles.',
          visual: 'point',
          draw: 'Sous le souvenir du premier filet, un second, plus bas\u202f; dessus, deux enveloppes marquées RSA et AAH, chacune avec son propre règlement.',
          emphasis: ['les minima sociaux', 'ses propres règles'],
        },
        {
          id: 'solidarites-intro-04',
          say: 'Au deuxième trimestre 2026, 8,3\u00a0% des personnes qui travaillent ou cherchent un emploi sont au chômage. Environ 1\u00a0sur 12.',
          spoken: 'Au deuxième trimestre deux mille vingt-six, huit virgule trois pour cent des personnes qui travaillent ou cherchent un emploi sont au chômage. Environ une sur douze.',
          visual: 'figure',
          draw: 'Douze silhouettes au trait sur deux rangées\u202f; l’une se colore au bleu bille.',
          emphasis: ['8,3\u00a0%', '1\u00a0sur 12'],
          figure: {
            value: '8,3\u00a0%',
            label: 'Taux de chômage au sens du Bureau international du travail (BIT), France (Mayotte comprise), 2e\u00a0trimestre 2026\u00a0: +0,2\u00a0point sur le trimestre et +0,7\u00a0point sur un an',
            date: '2e\u00a0trimestre 2026',
            sourceIndex: 0,
          },
        },
        {
          id: 'solidarites-intro-05',
          say: 'Fin 2024, les minima sociaux comptaient 4,25\u00a0millions d’allocataires.',
          spoken: 'Fin deux mille vingt-quatre, les minima sociaux comptaient quatre virgule vingt-cinq millions d’allocataires.',
          visual: 'figure',
          draw: 'Une foule de petites silhouettes au trait qui se remplit rangée par rangée.',
          emphasis: ['4,25\u00a0millions'],
          figure: {
            value: '4,25\u00a0millions',
            label: 'Allocataires de minima sociaux fin 2024 (RSA, allocation aux adultes handicapés, allocation de solidarité spécifique pour les chômeurs en fin de droits, minimum vieillesse…)',
            date: '2024',
            sourceIndex: 1,
          },
        },
        {
          id: 'solidarites-intro-06',
          say: 'En 2024, 33,3\u00a0milliards d’euros leur ont été versés. C’est 1,1\u00a0% du PIB, la richesse produite en un an\u00a0: un peu plus d’un euro sur 100.',
          spoken: 'En deux mille vingt-quatre, trente-trois virgule trois milliards d’euros leur ont été versés. C’est un virgule un pour cent du P.I.B., la richesse produite en un an : un peu plus d’un euro sur cent.',
          visual: 'figure',
          draw: 'Cent pièces en dix rangées, la richesse produite en un an\u202f; une seule se colore au bleu bille.',
          emphasis: ['33,3\u00a0milliards', '1,1\u00a0%', 'un euro sur 100'],
          figure: {
            value: '33,3\u00a0Md€',
            label: 'Montant des minima sociaux versés en 2024, soit 1,1\u00a0% du PIB',
            date: '2024',
            sourceIndex: 1,
          },
        },
        {
          id: 'solidarites-intro-07',
          say: 'Quatre questions se posent. Quelle assurance chômage\u202f? Quel revenu minimum\u202f? Quelles contreparties\u202f? Et quels droits pour les personnes handicapées\u202f?',
          visual: 'question',
          draw: 'Quatre pictogrammes en grille, dessinés l’un après l’autre\u00a0: une mallette, un porte-monnaie, un contrat, une personne.',
          emphasis: ['assurance chômage', 'revenu minimum', 'contreparties'],
        },
        {
          id: 'solidarites-intro-08',
          say: 'Ce sont les quatre sujets des vidéos qui suivent.',
          visual: 'outro',
          draw: 'Les quatre pictogrammes se rangent en file, comme les chapitres d’un carnet.',
        },
      ],
      sources: [
        {
          title: 'Au deuxième trimestre 2026, le taux de chômage augmente de 0,2\u00a0point et atteint 8,3\u00a0% (Informations rapides n°\u00a0192)',
          url: 'https://www.insee.fr/fr/statistiques/9032359',
          publisher: 'Insee',
          date: '2026-08-07',
        },
        {
          title: 'Le nombre d’allocataires de minima sociaux augmente en 2024',
          url: 'https://drees.solidarites-sante.gouv.fr/communique-de-presse/communique-de-presse/251204-nombre-allocataires-minima-sociaux',
          publisher: 'DREES',
          date: '2025-12-04',
        },
      ],
    },
    {
      id: 'solidarites-chomage',
      kind: 'deep',
      questionIds: ['solidarites-x1'],
      title: 'Perdre son emploi\u00a0: quelle indemnisation\u202f?',
      short: 'Assurance chômage',
      register: 'vous',
      segments: [
        {
          id: 'solidarites-chomage-01',
          say: 'Vous perdez votre emploi. Pendant combien de temps toucherez-vous une allocation\u202f?',
          visual: 'hook',
          draw: 'Une mallette de travail en pointillé\u202f; à côté, une enveloppe d’allocation et un sablier, puis un point d’interrogation.',
          emphasis: ['combien de temps'],
        },
        {
          id: 'solidarites-chomage-02',
          say: 'Les syndicats et le patronat négocient les règles, dans un cadre fixé par le Premier ministre. Sans accord validé par l’État, un décret les fixe.',
          visual: 'point',
          draw: 'Deux personnes face à face autour d’un document, dans un cadre en pointillé envoyé par un bâtiment public\u202f; à côté, un décret prêt à prendre le relais.',
          emphasis: ['négocient', 'un décret'],
        },
        {
          id: 'solidarites-chomage-03',
          say: 'La durée dépend aussi du taux de chômage. S’il est sous 9\u00a0% et n’a pas augmenté de 0,8\u00a0point en un trimestre, elle est réduite de 25\u00a0%.',
          spoken: 'La durée dépend aussi du taux de chômage. S’il est sous neuf pour cent et n’a pas augmenté de zéro virgule huit point en un trimestre, elle est réduite de vingt-cinq pour cent.',
          visual: 'point',
          draw: 'Un cadran du chômage et ses deux conditions\u202f; en dessous, la durée d’indemnisation en quatre quarts, dont le dernier passe en pointillé.',
          emphasis: ['sous 9\u00a0%', 'réduite de 25\u00a0%'],
        },
        {
          id: 'solidarites-chomage-04',
          say: 'Avant 55\u00a0ans, elle est alors plafonnée à 548\u00a0jours, environ 18\u00a0mois, contre 730\u00a0jours, environ 24\u00a0mois, sinon.',
          spoken: 'Avant cinquante-cinq ans, elle est alors plafonnée à cinq cent quarante-huit jours, environ dix-huit mois, contre sept cent trente jours, environ vingt-quatre mois, sinon.',
          visual: 'compare',
          draw: 'Deux barres à la même échelle, depuis zéro\u00a0: 548 et 730\u00a0jours, chacune sous sa durée en mois.',
          emphasis: ['548\u00a0jours', '730\u00a0jours'],
          figure: {
            value: '548\u00a0jours',
            label: 'Durée maximale d’indemnisation avant 55\u00a0ans quand la règle de réduction s’applique (environ 18\u00a0mois), contre 730\u00a0jours (environ 24\u00a0mois) sinon',
            date: '2026',
            sourceIndex: 1,
          },
        },
        {
          id: 'solidarites-chomage-05',
          say: 'Après une rupture conventionnelle, une fin de contrat décidée d’un commun accord, la règle a changé. Depuis le 1er\u00a0septembre 2026, c’est 15\u00a0mois au plus, contre 18 avant, pour les moins de 55\u00a0ans en métropole.',
          spoken: 'Après une rupture conventionnelle, une fin de contrat décidée d’un commun accord, la règle a changé. Depuis le premier septembre deux mille vingt-six, c’est quinze mois au plus, contre dix-huit avant, pour les moins de cinquante-cinq ans en métropole.',
          visual: 'figure',
          draw: 'Deux barres à la même échelle, depuis zéro\u00a0: 18\u00a0mois avant, 15\u00a0mois depuis le 1er\u00a0septembre 2026.',
          emphasis: ['15\u00a0mois', 'contre 18'],
          figure: {
            value: '15\u00a0mois',
            label: 'Durée maximale d’indemnisation après une rupture conventionnelle (fin du contrat décidée d’un commun accord entre employeur et salarié), avant 55\u00a0ans, en métropole, pour les contrats rompus depuis le 1er\u00a0septembre 2026, contre 18\u00a0mois auparavant',
            date: '1er\u00a0septembre 2026',
            sourceIndex: 2,
          },
          chart: {
            kind: 'compare',
            unit: 'mois',
            items: [
              { label: 'Auparavant', value: 18 },
              { label: 'Depuis le 1er septembre 2026', value: 15 },
            ],
          },
        },
        {
          id: 'solidarites-chomage-06',
          say: 'À France Travail, tous les inscrits ne sont pas indemnisés. Fin 2025, parmi ceux tenus de chercher un emploi, 67,9\u00a0% avaient un droit ouvert à une allocation. Et 46,9\u00a0% la touchaient effectivement.',
          spoken: 'À France Travail, tous les inscrits ne sont pas indemnisés. Fin deux mille vingt-cinq, parmi ceux tenus de chercher un emploi, soixante-sept virgule neuf pour cent avaient un droit ouvert à une allocation. Et quarante-six virgule neuf pour cent la touchaient effectivement.',
          visual: 'figure',
          draw: 'Deux barres à la même échelle, de zéro à cent pour cent\u00a0: ceux qui ont un droit ouvert, ceux qui sont indemnisés.',
          alt: 'Les deux barres sur une échelle de 0 à 100\u00a0%.',
          emphasis: ['67,9\u00a0%', '46,9\u00a0%'],
          figure: {
            value: '46,9\u00a0%',
            label: 'Part des inscrits à France Travail en catégories A, B et C (tenus de chercher un emploi, sans emploi ou en activité réduite) effectivement indemnisés fin décembre 2025. 67,9\u00a0% ont un droit ouvert à indemnisation\u202f; parmi eux, 69,0\u00a0% sont indemnisés',
            date: 'fin 2025',
            sourceIndex: 3,
          },
          chart: {
            kind: 'compare',
            unit: '%',
            items: [
              { label: 'Ont un droit ouvert', value: 67.9 },
              { label: 'Effectivement indemnisés', value: 46.9 },
            ],
          },
        },
        {
          id: 'solidarites-chomage-07',
          say: 'L’Unédic, qui gère le régime, prévoit un déficit de 2,3\u00a0milliards d’euros en 2026. En 2025, elle avait un excédent de 0,1\u00a0milliard.',
          spoken: 'L’Unédic, qui gère le régime, prévoit un déficit de deux virgule trois milliards d’euros en deux mille vingt-six. En deux mille vingt-cinq, elle avait un excédent de zéro virgule un milliard.',
          visual: 'figure',
          draw: 'Une ligne du zéro\u202f; au-dessus, une colonne à peine visible pour 2025\u202f; en dessous, une colonne en pointillé qui descend pour 2026, une prévision.',
          emphasis: ['2,3\u00a0milliards', '0,1\u00a0milliard'],
          figure: {
            value: '−2,3\u00a0Md€',
            label: 'Solde de l’assurance chômage prévu pour 2026 par l’Unédic, qui gère le régime (+0,1\u00a0Md€ en 2025). L’Unédic attribue la baisse de ses recettes à des prélèvements de l’État et à des pertes de CSG. Sans nouveau prélèvement, elle prévoit +2,1\u00a0Md€ en 2027. Dette attendue fin 2026\u00a0: 61,5\u00a0Md€',
            date: '2026',
            sourceIndex: 4,
          },
          chart: {
            kind: 'series',
            unit: 'Md€',
            items: [
              { label: '2025', value: 0.1 },
              { label: '2026 (prévision)', value: -2.3 },
            ],
          },
        },
        {
          id: 'solidarites-chomage-08',
          say: 'Selon l’Unédic, ses recettes baissent du fait de pertes de CSG et de prélèvements de l’État. Sans nouveau prélèvement, elle prévoit un excédent de 2,1\u00a0milliards en 2027.',
          spoken: 'Selon l’Unédic, ses recettes baissent du fait de pertes de C.S.G. et de prélèvements de l’État. Sans nouveau prélèvement, elle prévoit un excédent de deux virgule un milliards en deux mille vingt-sept.',
          visual: 'point',
          draw: 'Une tirelire d’où partent deux flèches, vers des pièces en pointillé et vers un bâtiment public\u202f; en dessous, une flèche qui monte vers l’excédent prévu en 2027.',
          emphasis: ['pertes de CSG', 'prélèvements de l’État', '2,1\u00a0milliards'],
        },
        {
          id: 'solidarites-chomage-09',
          say: 'Alors, combien de temps indemniser, à quel niveau, et qui doit en décider\u202f?',
          visual: 'question',
          draw: 'Un sablier, une enveloppe d’allocation et un document de règles sur une même ligne, en attente\u202f; un point d’interrogation.',
          emphasis: ['combien de temps', 'qui doit en décider'],
        },
      ],
      sources: [
        {
          title: 'Code du travail, articles L5422-20 et L5422-20-1',
          url: 'https://www.legifrance.gouv.fr/codes/id/LEGISCTA000006189825',
          publisher: 'Légifrance',
        },
        {
          title: 'Allocation chômage d’aide au retour à l’emploi (ARE) d’un salarié du secteur privé dont la fin de contrat de travail intervient à compter du 1er\u00a0avril 2025',
          url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F38881',
          publisher: 'Service-public.gouv.fr (DILA)',
          date: '2026-07-23',
        },
        {
          title: 'Rupture conventionnelle\u00a0: ce qui change au 1er\u00a0septembre 2026',
          url: 'https://www.service-public.gouv.fr/particuliers/actualites/A18945',
          publisher: 'Service-public.gouv.fr (DILA)',
          date: '2026-06-12',
        },
        {
          title: 'Part des demandeurs d’emploi indemnisables\u00a0: situation au 31\u00a0décembre 2025 (n°\u00a026.014)',
          url: 'https://statistiques.francetravail.org/indem/indempub/229912',
          publisher: 'France Travail, service statistique',
          date: '2026-09-24',
        },
        {
          title: 'Prévisions financières de l’Unédic, juin 2026',
          url: 'https://www.unedic.org/publications/previsions-financieres-de-lunedic-juin-2026',
          publisher: 'Unédic',
          date: '2026-06-17',
        },
      ],
    },
    {
      id: 'solidarites-rsa',
      kind: 'deep',
      questionIds: ['solidarites-x2'],
      title: 'Le RSA\u00a0: quel montant, pour qui\u202f?',
      short: 'RSA et minima sociaux',
      register: 'vous',
      segments: [
        {
          id: 'solidarites-rsa-01',
          say: 'Si vous n’avez presque aucun revenu, un minimum peut vous être garanti. Mais combien, et à quelles conditions\u202f?',
          visual: 'hook',
          draw: 'Un porte-monnaie presque vide\u202f; au-dessous, un plancher tracé au trait fort\u202f; un point d’interrogation.',
          emphasis: ['combien', 'à quelles conditions'],
        },
        {
          id: 'solidarites-rsa-02',
          say: 'C’est le rôle du RSA, le revenu de solidarité active. D’autres minima sociaux existent à côté, chacun avec ses propres règles.',
          spoken: 'C’est le rôle du R.S.A., le revenu de solidarité active. D’autres minima sociaux existent à côté, chacun avec ses propres règles.',
          visual: 'point',
          draw: 'Un document marqué RSA au premier plan\u202f; de part et d’autre, d’autres documents aux lignes différentes.',
          emphasis: ['RSA', 'ses propres règles'],
        },
        {
          id: 'solidarites-rsa-03',
          say: 'En 2026, le RSA d’une personne seule sans enfant ni autre ressource est de 651,69\u00a0euros par mois.',
          spoken: 'En deux mille vingt-six, le R.S.A. d’une personne seule sans enfant ni autre ressource est de six cent cinquante et un euros soixante-neuf par mois.',
          visual: 'figure',
          draw: 'Une personne seule au trait\u202f; à côté, un billet et quelques pièces.',
          emphasis: ['651,69\u00a0euros'],
          figure: {
            value: '651,69\u00a0€',
            label: 'Montant mensuel du RSA pour une personne seule sans enfant ni autre ressource, en 2026. Un «\u00a0forfait logement\u00a0» de 78,20\u00a0€ en est déduit si la personne touche une aide au logement, est logée gratuitement ou est propriétaire',
            date: '2026',
            sourceIndex: 0,
          },
        },
        {
          id: 'solidarites-rsa-04',
          say: 'Si cette personne touche une aide au logement, est logée gratuitement ou propriétaire, un forfait logement de 78,20\u00a0euros en est déduit.',
          spoken: 'Si cette personne touche une aide au logement, est logée gratuitement ou propriétaire, un forfait logement de soixante-dix-huit euros vingt en est déduit.',
          visual: 'point',
          draw: 'La barre du montant du RSA\u202f; une maison au-dessus de son extrémité, qui passe en pointillé sur la longueur du forfait.',
          alt: 'Au-dessus de la barre, son montant\u00a0: 651,69\u00a0euros.',
          emphasis: ['78,20\u00a0euros'],
        },
        {
          id: 'solidarites-rsa-05',
          say: 'En juin 2026, 1,89\u00a0million de foyers touchaient le RSA, 1,9\u00a0% de plus qu’un an plus tôt.',
          spoken: 'En juin deux mille vingt-six, un virgule quatre-vingt-neuf million de foyers touchaient le R.S.A., un virgule neuf pour cent de plus qu’un an plus tôt.',
          visual: 'figure',
          draw: 'Deux rangées de petites maisons au trait\u202f; dessous, une flèche montante discrète.',
          emphasis: ['1,89\u00a0million', '1,9\u00a0%'],
          figure: {
            value: '1,89\u00a0million',
            label: 'Foyers allocataires du RSA en juin 2026, soit +1,9\u00a0% sur un an',
            date: 'juin 2026',
            sourceIndex: 1,
          },
        },
        {
          id: 'solidarites-rsa-06',
          say: 'Mais certains foyers qui y ont droit ne le touchent pas\u00a0: c’est le non-recours. Fin 2021, en métropole, 33 à 37\u00a0% des foyers éligibles ne le touchaient pas\u00a0: 560\u202f000\u00a0foyers.',
          spoken: 'Mais certains foyers qui y ont droit ne le touchent pas : c’est le non-recours. Fin deux mille vingt et un, en métropole, trente-trois à trente-sept pour cent des foyers éligibles ne le touchaient pas : cinq cent soixante mille foyers.',
          visual: 'figure',
          draw: 'Cent petites maisons en dix rangées\u202f; 33 se colorent au bleu bille, et 4 de plus au bleu clair.',
          emphasis: ['non-recours', '33 à 37\u00a0%'],
          figure: {
            value: '33\u00a0% à 37\u00a0%',
            label: 'Part des foyers éligibles au RSA qui ne le perçoivent pas (non-recours), soit 560\u202f000\u00a0foyers. France métropolitaine, logement ordinaire, fin 2021\u00a0: dernière mesure disponible',
            date: 'fin 2021',
            sourceIndex: 2,
          },
        },
        {
          id: 'solidarites-rsa-07',
          say: 'Depuis le 1er\u00a0mars 2025, les déclarations trimestrielles de ressources du RSA et de la prime d’activité sont préremplies. Les données viennent surtout des employeurs, des organismes sociaux et des impôts.',
          spoken: 'Depuis le premier mars deux mille vingt-cinq, les déclarations trimestrielles de ressources du R.S.A. et de la prime d’activité sont préremplies. Les données viennent surtout des employeurs, des organismes sociaux et des impôts.',
          visual: 'point',
          draw: 'Un formulaire au trait dont les lignes se remplissent seules\u202f; trois flèches y mènent, depuis un immeuble, un guichet et un bâtiment public.',
          emphasis: ['préremplies'],
        },
        {
          id: 'solidarites-rsa-08',
          say: 'Autre enjeu, la fraude. Sur toutes les prestations des CAF, et pas seulement le RSA, la dernière enquête l’estime entre 3,8 et 4,7\u00a0milliards d’euros. En 2025, 509\u00a0millions ont été détectés.',
          spoken: 'Autre enjeu, la fraude. Sur toutes les prestations des Caf, et pas seulement le R.S.A., la dernière enquête l’estime entre trois virgule huit et quatre virgule sept milliards d’euros. En deux mille vingt-cinq, cinq cent neuf millions ont été détectés.',
          visual: 'figure',
          draw: 'Deux barres à la même échelle, depuis zéro\u00a0: la fraude estimée, sa fin en hachures entre 3,8 et 4,7\u00a0milliards\u202f; la fraude détectée en 2025.',
          alt: 'Deux barres à la même échelle, légendées «\u00a0estimée\u00a0» et «\u00a0détectée en 2025\u00a0».',
          emphasis: ['la fraude', '3,8 et 4,7\u00a0milliards', '509\u00a0millions'],
          figure: {
            value: '3,8 à 4,7\u00a0Md€',
            label: 'Fraude estimée sur l’ensemble des prestations versées par les CAF (pas seulement le RSA), selon la dernière enquête de la CNAF. Fraudes détectées en 2025\u00a0: 509\u00a0M€',
            date: 'dernière enquête de la CNAF, citée en 2026',
            sourceIndex: 4,
          },
        },
        {
          id: 'solidarites-rsa-09',
          say: 'La lutte contre la fraude d’un côté, l’accès aux droits de l’autre\u00a0: c’est l’un des équilibres du débat.',
          visual: 'compare',
          draw: 'Une balance au fléau horizontal\u00a0: une loupe sur un plateau, une porte sur l’autre.',
          emphasis: ['La lutte contre la fraude', 'l’accès aux droits'],
        },
        {
          id: 'solidarites-rsa-10',
          say: 'Alors, quel montant pour les minima sociaux, et quelles démarches pour les obtenir\u202f?',
          visual: 'question',
          draw: 'Un porte-monnaie et un formulaire posés sur une même ligne, un point d’interrogation à côté.',
          emphasis: ['quel montant', 'quelles démarches'],
        },
      ],
      sources: [
        {
          title: 'RSA\u00a0: demandeur de 25\u00a0ans et plus',
          url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F19778',
          publisher: 'Service-public.gouv.fr (DILA)',
          date: '2026-04-01',
        },
        {
          title: 'Suivi mensuel des prestations de solidarité, édition d’août 2026',
          url: 'https://drees.solidarites-sante.gouv.fr/communique-de-presse-jeux-de-donnees/jeux-de-donnees/260831-suivi-mensuel-des-prestations-de-solidarite-aout-2026',
          publisher: 'DREES',
          date: '2026-08-31',
        },
        {
          title: 'Non-recours au RSA\u00a0: plus d’un tiers des foyers éligibles ne le percevaient pas fin 2021 (Études et Résultats n°\u00a01370)',
          url: 'https://drees.solidarites-sante.gouv.fr/publications-communique-de-presse/etudes-et-resultats/260506-non-recours-au-rsa-fin-2021',
          publisher: 'DREES',
          date: '2026-05-06',
        },
        {
          title: 'Sécurité sociale 2026, chapitre XI\u00a0: La fréquence des réformes à la CNAF et à la CNAV, un défi pour la mise en œuvre et la qualité de service (p.\u00a0365)',
          url: 'https://www.ccomptes.fr/sites/default/files/2026-05/20260527-RALFSS-2026-11-Frequence-reformes-CNAF-et-CNAV.pdf',
          publisher: 'Cour des comptes',
          date: '2026-05-27',
        },
        {
          title: 'Certification des comptes du régime général de sécurité sociale, exercice 2025 (synthèse, p.\u00a05)',
          url: 'https://www.ccomptes.fr/sites/default/files/2026-05/20260513-synthese-Certification-comptes-Securite-sociale-2025.pdf',
          publisher: 'Cour des comptes',
          date: '2026-05-13',
        },
        {
          title: 'Le nombre d’allocataires de minima sociaux augmente en 2024',
          url: 'https://drees.solidarites-sante.gouv.fr/communique-de-presse/communique-de-presse/251204-nombre-allocataires-minima-sociaux',
          publisher: 'DREES',
          date: '2025-12-04',
        },
      ],
    },
    {
      id: 'solidarites-contreparties',
      kind: 'deep',
      questionIds: ['solidarites-x2', 'solidarites-x1'],
      title: 'Quelles contreparties aux allocations\u202f?',
      short: 'Contreparties',
      register: 'vous',
      segments: [
        {
          id: 'solidarites-contreparties-01',
          say: 'Vous touchez une allocation. Qu’attend-on de vous en échange\u202f?',
          visual: 'hook',
          draw: 'Une enveloppe d’allocation d’un côté, un document de l’autre, reliés par deux flèches de sens contraire\u202f; un point d’interrogation.',
          emphasis: ['en échange'],
        },
        {
          id: 'solidarites-contreparties-02',
          say: 'Demandeurs d’emploi comme allocataires du RSA ont un contrat d’engagement\u00a0: des démarches convenues, de recherche d’emploi ou d’insertion.',
          spoken: 'Demandeurs d’emploi comme allocataires du R.S.A. ont un contrat d’engagement : des démarches convenues, de recherche d’emploi ou d’insertion.',
          visual: 'point',
          draw: 'Deux personnes de part et d’autre d’un document\u00a0: le contrat, avec des cases à cocher.',
          emphasis: ['contrat d’engagement', 'démarches convenues'],
        },
        {
          id: 'solidarites-contreparties-03',
          say: 'Un décret de mai 2025 fixe les sanctions. Si le contrat n’est pas respecté, au moins 30\u00a0% de l’allocation peut être suspendu, pendant un à deux mois.',
          spoken: 'Un décret de mai deux mille vingt-cinq fixe les sanctions. Si le contrat n’est pas respecté, au moins trente pour cent de l’allocation peut être suspendu, pendant un à deux mois.',
          visual: 'point',
          draw: 'Cent pièces en dix rangées, l’allocation\u202f; trente passent en pointillé\u202f; dessous, un calendrier, un à deux mois.',
          emphasis: ['au moins 30\u00a0%', 'un à deux mois'],
        },
        {
          id: 'solidarites-contreparties-04',
          say: 'En cas de récidive, c’est un à quatre mois. Et la suspension prend fin si la personne se remet en règle.',
          visual: 'point',
          draw: 'Quatre cases de mois qui se colorent\u202f; puis un contrat coché, et une flèche qui rend l’enveloppe entière.',
          emphasis: ['un à quatre mois', 'se remet en règle'],
        },
        {
          id: 'solidarites-contreparties-05',
          say: 'Pour le RSA, dans un foyer de plusieurs personnes, la part suspendue ne peut pas dépasser 50\u00a0%.',
          spoken: 'Pour le R.S.A., dans un foyer de plusieurs personnes, la part suspendue ne peut pas dépasser cinquante pour cent.',
          visual: 'point',
          draw: 'Trois personnes sous un même toit\u202f; à côté, la barre de l’allocation, dont la part suspendue s’arrête net à mi-longueur.',
          emphasis: ['plusieurs personnes', '50\u00a0%'],
        },
        {
          id: 'solidarites-contreparties-06',
          say: 'Pour un demandeur d’emploi, l’allocation peut aussi être supprimée en totalité pendant quatre mois. Il est alors radié de la liste des demandeurs d’emploi, pour la même durée.',
          visual: 'point',
          draw: 'Une enveloppe en pointillé et quatre cases de mois\u202f; à côté, une liste dont une ligne passe en pointillé.',
          emphasis: ['supprimée en totalité', 'radié de la liste'],
        },
        {
          id: 'solidarites-contreparties-07',
          say: 'Alors, quelle place donner aux contreparties et aux sanctions\u202f?',
          visual: 'question',
          draw: 'Le contrat et l’enveloppe d’allocation de part et d’autre d’un point d’interrogation.',
          emphasis: ['quelle place'],
        },
      ],
      sources: [
        {
          title: 'Décret n°\u00a02025-478 du 30\u00a0mai 2025 relatif aux sanctions applicables aux demandeurs d’emploi en cas de manquement à leurs obligations',
          url: 'https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000051672648',
          publisher: 'Légifrance',
          date: '2025-05-31',
        },
      ],
    },
    {
      id: 'solidarites-handicap',
      kind: 'deep',
      questionIds: ['solidarites-x3'],
      title: 'Quels droits pour les personnes handicapées\u202f?',
      short: 'Handicap',
      register: 'vous',
      segments: [
        {
          id: 'solidarites-handicap-01',
          say: 'Un handicap peut limiter l’accès à l’emploi. Quelles aides existent alors\u202f?',
          visual: 'hook',
          draw: 'Une personne au trait\u202f; devant elle, une barrière, puis une mallette de travail\u202f; un point d’interrogation.',
          emphasis: ['Quelles aides'],
        },
        {
          id: 'solidarites-handicap-02',
          say: 'L’allocation aux adultes handicapés, l’AAH, garantit un revenu minimum. Il faut un taux d’incapacité d’au moins 80\u00a0%. Ou de 50 à 79\u00a0%, si l’accès à l’emploi est restreint de façon substantielle et durable.',
          spoken: 'L’allocation aux adultes handicapés, l’A.A.H., garantit un revenu minimum. Il faut un taux d’incapacité d’au moins quatre-vingts pour cent. Ou de cinquante à soixante-dix-neuf pour cent, si l’accès à l’emploi est restreint de façon substantielle et durable.',
          visual: 'point',
          draw: 'Une jauge du taux d’incapacité\u00a0: la zone de 80 à 100 se colore, celle de 50 à 79 se grise, une mallette en pointillé en dessous.',
          alt: 'Une jauge du taux d’incapacité, graduée 0, 50, 80 et 100\u00a0%.',
          emphasis: ['l’AAH', 'au moins 80\u00a0%', '50 à 79\u00a0%'],
        },
        {
          id: 'solidarites-handicap-03',
          say: 'Son montant maximal est de 1\u202f041,59\u00a0euros par mois, pour une personne sans autres ressources.',
          spoken: 'Son montant maximal est de mille quarante et un euros cinquante-neuf par mois, pour une personne sans autres ressources.',
          visual: 'figure',
          draw: 'Une barre au trait depuis zéro, le montant maximal de l’AAH.',
          emphasis: ['1\u202f041,59\u00a0euros'],
          figure: {
            value: '1\u202f041,59\u00a0€',
            label: 'Montant mensuel maximal de l’AAH pour une personne sans autres ressources, en vigueur en septembre 2026',
            date: '2026',
            sourceIndex: 0,
          },
        },
        {
          id: 'solidarites-handicap-04',
          say: 'Le seuil de pauvreté d’une personne seule, en métropole, était de 1\u202f337\u00a0euros par mois en 2024. Il se compare au revenu après impôts et prestations, aides au logement comprises.',
          spoken: 'Le seuil de pauvreté d’une personne seule, en métropole, était de mille trois cent trente-sept euros par mois en deux mille vingt-quatre. Il se compare au revenu après impôts et prestations, aides au logement comprises.',
          visual: 'compare',
          draw: 'Sous la barre de l’AAH, une seconde barre à la même échelle, depuis zéro\u00a0: le seuil de pauvreté.',
          alt: 'Deux barres à la même échelle, depuis zéro\u00a0: l’AAH, 1\u202f041,59\u00a0€, et le seuil de pauvreté, 1\u202f337\u00a0€.',
          emphasis: ['1\u202f337\u00a0euros'],
          figure: {
            value: '1\u202f337\u00a0€',
            label: 'Seuil de pauvreté mensuel pour une personne seule (60\u00a0% du niveau de vie médian), France métropolitaine, 2024. Il se compare au revenu disponible, c’est-à-dire après impôts directs et prestations sociales, aides au logement comprises',
            date: '2024',
            sourceIndex: 1,
          },
        },
        {
          id: 'solidarites-handicap-05',
          say: 'Depuis le 1er\u00a0octobre 2023, l’AAH ne dépend plus des revenus du conjoint, sauf si l’ancien calcul est plus favorable.',
          spoken: 'Depuis le premier octobre deux mille vingt-trois, l’A.A.H. ne dépend plus des revenus du conjoint, sauf si l’ancien calcul est plus favorable.',
          visual: 'point',
          draw: 'Deux personnes côte à côte\u202f; les pièces du conjoint passent en pointillé, l’enveloppe de l’AAH reste entière.',
          emphasis: ['revenus du conjoint'],
        },
        {
          id: 'solidarites-handicap-06',
          say: 'Les demandes d’aides passent par les MDPH, les maisons départementales des personnes handicapées. En 2024, 1,8\u00a0million de personnes s’y sont adressées\u00a0: 2,7\u00a0% de la population.',
          spoken: 'Les demandes d’aides passent par les M.D.P.H., les maisons départementales des personnes handicapées. En deux mille vingt-quatre, un virgule huit million de personnes s’y sont adressées : deux virgule sept pour cent de la population.',
          visual: 'figure',
          draw: 'Un guichet marqué MDPH\u202f; des formulaires y arrivent de part et d’autre.',
          emphasis: ['les MDPH', '1,8\u00a0million'],
          figure: {
            value: '1,8\u00a0million',
            label: 'Personnes ayant adressé une demande à une MDPH en 2024, soit 2,7\u00a0% de la population',
            date: '2024',
            sourceIndex: 2,
          },
        },
        {
          id: 'solidarites-handicap-07',
          say: 'Une demande y était traitée en 4,8\u00a0mois en moyenne, en 2024.',
          spoken: 'Une demande y était traitée en quatre virgule huit mois en moyenne, en deux mille vingt-quatre.',
          visual: 'figure',
          draw: 'Une ligne de six mois, graduée\u202f; un drapeau planté à 4,8.',
          alt: 'Sur une ligne graduée 0, 2, 4 et 6\u00a0mois, un drapeau marque le délai moyen.',
          emphasis: ['4,8\u00a0mois'],
          figure: {
            value: '4,8\u00a0mois',
            label: 'Délai moyen de traitement des demandes déposées en MDPH, en 2024',
            date: '2024',
            sourceIndex: 2,
          },
        },
        {
          id: 'solidarites-handicap-08',
          say: 'À la rentrée 2025, 593\u202f300\u00a0élèves en situation de handicap étaient scolarisés. Près de 9\u00a0sur 10 l’étaient uniquement en milieu ordinaire, hors établissement spécialisé.',
          spoken: 'À la rentrée deux mille vingt-cinq, cinq cent quatre-vingt-treize mille trois cents élèves en situation de handicap étaient scolarisés. Près de neuf sur dix l’étaient uniquement en milieu ordinaire, hors établissement spécialisé.',
          visual: 'figure',
          draw: 'Dix petites silhouettes au trait\u202f; neuf se colorent au bleu bille.',
          emphasis: ['593\u202f300\u00a0élèves', 'Près de 9\u00a0sur 10'],
          figure: {
            value: '593\u202f300',
            label: 'Élèves en situation de handicap scolarisés à la rentrée 2025-2026, dont 88,8\u00a0% uniquement en milieu ordinaire, c’est-à-dire hors établissement spécialisé',
            date: '2025-2026',
            sourceIndex: 3,
          },
        },
        {
          id: 'solidarites-handicap-09',
          say: 'Pour les accompagner, l’Éducation nationale paie 137\u202f800\u00a0accompagnants, les AESH, tous contractuels.',
          spoken: 'Pour les accompagner, l’Éducation nationale paie cent trente-sept mille huit cents accompagnants, les A.E.S.H., tous contractuels.',
          visual: 'figure',
          draw: 'Une grande et une petite silhouette côte à côte près d’un livre ouvert\u202f; à côté, un contrat.',
          emphasis: ['137\u202f800', 'tous contractuels'],
          figure: {
            value: '137\u202f800',
            label: 'Accompagnants d’élèves en situation de handicap (AESH) payés par l’Éducation nationale en 2025-2026, tous contractuels (France, personnes en activité au 30\u00a0novembre 2025)',
            date: '2025-2026',
            sourceIndex: 3,
          },
        },
        {
          id: 'solidarites-handicap-10',
          say: 'Logement\u00a0: depuis une loi de 2018, dans les immeubles collectifs neufs, 20\u00a0% des logements, et au moins un, doivent être accessibles. Les autres doivent pouvoir le devenir par des travaux simples.',
          spoken: 'Logement : depuis une loi de deux mille dix-huit, dans les immeubles collectifs neufs, vingt pour cent des logements, et au moins un, doivent être accessibles. Les autres doivent pouvoir le devenir par des travaux simples.',
          visual: 'point',
          draw: 'Un immeuble au trait de dix logements\u202f; deux se colorent au bleu bille, les autres reçoivent un contour en pointillé, prêts à être adaptés.',
          emphasis: ['20\u00a0%', 'travaux simples'],
        },
        {
          id: 'solidarites-handicap-11',
          say: 'Alors, quelle priorité\u00a0: le niveau de l’allocation, les démarches, l’école ou l’accessibilité\u202f?',
          visual: 'question',
          draw: 'Quatre pictogrammes de même taille\u00a0: une enveloppe, un guichet, un livre, une porte.',
          emphasis: ['quelle priorité'],
        },
      ],
      sources: [
        {
          title: 'Allocation aux adultes handicapés (AAH)',
          url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F12242',
          publisher: 'Service-public.gouv.fr (DILA)',
          date: '2026-09-14',
        },
        {
          title: 'L’essentiel sur… la pauvreté',
          url: 'https://www.insee.fr/fr/statistiques/5759045',
          publisher: 'Insee',
          date: '2026-07-09',
        },
        {
          title: 'Chiffres clés de l’aide à l’autonomie 2026 (p.\u00a016 et 17)',
          url: 'https://www.cnsa.fr/sites/default/files/2026-06/PUB-CNSA-CC2026-WEB-ACCESS.pdf',
          publisher: 'CNSA (branche autonomie de la Sécurité sociale)',
          date: '2026-06',
        },
        {
          title: 'Repères et références statistiques 2026 (fiches 9.16, p.\u00a0370, et 1.07, p.\u00a024)',
          url: 'https://www.education.gouv.fr/sites/default/files/document/rers-2026-pdf-519880.pdf',
          publisher: 'DEPP, ministère de l’Éducation nationale',
          date: '2026',
        },
        {
          title: 'Loi n°\u00a02018-1021 du 23\u00a0novembre 2018 portant évolution du logement, de l’aménagement et du numérique, article 64',
          url: 'https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000037639567',
          publisher: 'Légifrance',
          date: '2018-11-23',
        },
      ],
    },
  ],
}
