// Série « Salaires et travail » (famille « Travail et économie ») : l'introduction, puis cinq approfondissements,
// un par question de la banque (pouvoir d'achat, autres salaires, partage des bénéfices, droits des salariés,
// temps de travail). Règles d'écriture : ../GUIDE-SERIES.md ; planches : ../pistes/planches/travail_salaires.tsx.
// Tous les chiffres viennent des fiches du thème (research/choisir-2027/explainers.json, questions
// travail_salaires-1 à -4 et -x1), à la lettre, avec leur source.
// Ne pas toucher aux identifiants ni aux textes dits sans raison : changer un « say » ou un « spoken », c'est
// devoir réenregistrer la voix du passage.
// Datée : Smic du 1er juin 2026 (une nouvelle hausse automatique peut venir si les prix montent encore de 2 %
// depuis), et prix de septembre 2026 (estimation provisoire de l'Insee). À revoir à la prochaine hausse du Smic
// et à la publication des résultats définitifs de l'Insee pour septembre 2026.
// « Smic » s'écrit comme à l'Insee et sur service-public.fr (pas « SMIC », que la voix épellerait).

import type { VideoSeries } from '../types'

export const TRAVAIL_SALAIRES: VideoSeries = {
  topicId: 'travail_salaires',
  familyId: 'economie',
  label: 'Salaires et travail',
  videos: [
    {
      id: 'travail-intro',
      kind: 'intro',
      questionIds: ['travail_salaires-1', 'travail_salaires-2', 'travail_salaires-3', 'travail_salaires-4', 'travail_salaires-x1'],
      title: 'Salaires et travail, l’essentiel',
      short: 'Introduction',
      register: 'vous',
      segments: [
        {
          id: 'travail-intro-01',
          say: 'Votre salaire augmente. Les prix aussi. Au bout du compte, pouvez-vous acheter plus\u202f?',
          visual: 'hook',
          draw: 'Un billet et une étiquette de prix montent côte à côte, chacun avec sa flèche\u202f; entre les deux, un point d’interrogation.',
          emphasis: ['Votre salaire', 'Les prix'],
        },
        {
          id: 'travail-intro-02',
          say: 'C’est la question du pouvoir d’achat. Il dépend du salaire net, ce qui reste après les prélèvements, et des prix.',
          visual: 'point',
          draw: 'Sous le mot «\u00a0pouvoir d’achat\u00a0», un porte-monnaie et une étiquette de prix, face à face, reliés par une flèche à double sens.',
          emphasis: ['pouvoir d’achat', 'salaire net', 'prix'],
        },
        {
          id: 'travail-intro-03',
          say: 'Le salaire minimum, le Smic\u00a0: 12,31\u00a0euros bruts de l’heure depuis le 1er\u00a0juin 2026. À temps plein, près de 1\u202f478\u00a0euros nets par mois.',
          spoken: 'Le salaire minimum, le Smic : douze euros trente et un bruts de l’heure depuis le premier juin deux mille vingt-six. À temps plein, près de mille quatre cent soixante-dix-huit euros nets par mois.',
          visual: 'figure',
          draw: 'Le chiffre écrit à la main\u202f; une horloge pour l’heure de travail, une flèche vers un porte-monnaie marqué du montant net du mois.',
          emphasis: ['12,31\u00a0euros', 'près de 1\u202f478\u00a0euros nets'],
          figure: {
            value: '12,31\u00a0€',
            label: 'Smic horaire brut depuis le 1er\u00a0juin 2026, contre 12,02\u00a0€ avant (+2,41\u00a0%). Pour un temps plein\u00a0: 1\u202f867,02\u00a0€ brut et 1\u202f477,93\u00a0€ net par mois (France hors Mayotte)',
            date: '1er\u00a0juin 2026',
            sourceIndex: 1,
          },
        },
        {
          id: 'travail-intro-04',
          say: 'Les prix ont augmenté de 3,0\u00a0% sur un an en septembre 2026, selon une première estimation de l’Insee. L’énergie, de 21,2\u00a0%. L’alimentation, de 1,5\u00a0%.',
          spoken: 'Les prix ont augmenté de trois pour cent sur un an en septembre deux mille vingt-six, selon une première estimation de l’Insee. L’énergie, de vingt et un virgule deux pour cent. L’alimentation, de un virgule cinq pour cent.',
          visual: 'figure',
          draw: 'Trois barres à la même échelle, depuis zéro\u00a0: l’ensemble des prix, l’énergie, l’alimentation.',
          emphasis: ['3,0\u00a0%', '21,2\u00a0%', '1,5\u00a0%'],
          figure: {
            value: '3,0\u00a0%',
            label: 'Hausse des prix à la consommation sur un an en septembre 2026 (estimation provisoire, France). Sur la même période\u00a0: énergie +21,2\u00a0%, alimentation +1,5\u00a0%',
            date: 'septembre 2026',
            sourceIndex: 2,
          },
          chart: {
            kind: 'compare',
            unit: '%',
            items: [
              { label: 'Prix à la consommation', value: 3 },
              { label: 'Énergie', value: 21.2 },
              { label: 'Alimentation', value: 1.5 },
            ],
          },
        },
        {
          id: 'travail-intro-05',
          say: 'Et le salaire net moyen du privé, hausse des prix déduite\u202f? Moins 1,3\u00a0% en 2022, moins 1,0\u00a0% en 2023.',
          spoken: 'Et le salaire net moyen du privé, hausse des prix déduite ? Moins un virgule trois pour cent en deux mille vingt-deux, moins un pour cent en deux mille vingt-trois.',
          visual: 'figure',
          draw: 'Sous la question, une ligne zéro\u00a0; deux barres descendent sous la ligne, 2022 puis 2023.',
          alt: 'Deux barres sous une ligne zéro\u00a0: −1,3\u00a0% en 2022, −1,0\u00a0% en 2023.',
          emphasis: ['1,3\u00a0%', '1,0\u00a0%'],
          figure: {
            value: '−1,3\u00a0% puis −1,0\u00a0%',
            label: 'Évolution du salaire net moyen du privé, inflation déduite, en 2022 puis en 2023. Selon l’Insee, les hausses du Smic ont alors préservé le bas de l’échelle, quand l’inflation rognait les salaires plus élevés. Après +0,8\u00a0% en 2024, le salaire moyen retrouve «\u00a0à peine\u00a0» son niveau de 2019 (France y compris Mayotte, apprentis et stagiaires compris, hors agriculture et particuliers employeurs)',
            date: '2022 à 2024',
            sourceIndex: 3,
          },
          chart: {
            kind: 'compare',
            unit: '%',
            items: [
              { label: '2022', value: -1.3 },
              { label: '2023', value: -1 },
              { label: '2024', value: 0.8 },
            ],
          },
        },
        {
          id: 'travail-intro-06',
          say: 'En 2024, plus 0,8\u00a0%\u00a0: il retrouve à peine son niveau de 2019, selon l’Insee.',
          spoken: 'En deux mille vingt-quatre, plus zéro virgule huit pour cent : il retrouve à peine son niveau de deux mille dix-neuf, selon l’Insee.',
          visual: 'figure',
          draw: 'Les barres de 2022 et 2023 restent sous la ligne zéro\u00a0; celle de 2024 monte au-dessus, et dessous s’écrit «\u00a0à peine son niveau de 2019\u00a0».',
          alt: 'Trois barres de part et d’autre d’une ligne zéro\u00a0: −1,3\u00a0% en 2022, −1,0\u00a0% en 2023, +0,8\u00a0% en 2024.',
          emphasis: ['0,8\u00a0%', 'à peine'],
          chart: {
            kind: 'compare',
            unit: '%',
            items: [
              { label: '2022', value: -1.3 },
              { label: '2023', value: -1 },
              { label: '2024', value: 0.8 },
            ],
          },
        },
        {
          id: 'travail-intro-07',
          say: 'Alors, cinq questions. Comment gagner en pouvoir d’achat\u202f? Comment faire progresser les autres salaires\u202f? Comment partager les bénéfices\u202f? Quels droits pour les salariés\u202f? Et quel temps de travail\u202f?',
          visual: 'question',
          draw: 'Cinq pictogrammes en grille, dessinés l’un après l’autre\u00a0: un porte-monnaie, un escalier de salaires, des pièces, un document, un sablier.',
          emphasis: ['pouvoir d’achat', 'autres salaires', 'bénéfices'],
        },
        {
          id: 'travail-intro-08',
          say: 'Ce sont les cinq sujets des vidéos qui suivent.',
          visual: 'outro',
          draw: 'Les cinq pictogrammes se rangent en file, comme les chapitres d’un carnet.',
        },
      ],
      sources: [
        {
          title: 'La CSG-CRDS',
          url: 'https://www.urssaf.fr/accueil/employeur/cotisations/liste-cotisations/csg-crds.html',
          publisher: 'Urssaf',
          date: '2026-02-12',
        },
        {
          title: 'Revalorisation annuelle du Smic au 1er\u00a0juin 2026',
          url: 'https://normandie.dreets.gouv.fr/Revalorisation-annuelle-du-SMIC-au-1er-juin-2026',
          publisher: 'DREETS Normandie (ministère du Travail et des Solidarités)',
          date: '2026-05-22',
        },
        {
          title: 'En septembre 2026, les prix à la consommation augmenteraient de 3,0\u00a0% sur un an (Informations rapides n° 242)',
          url: 'https://www.insee.fr/fr/statistiques/9056956',
          publisher: 'Insee',
          date: '2026-09-30',
        },
        {
          title: 'Insee Première n° 2079 – Salaires dans le secteur privé en 2024 (23 octobre 2025)',
          url: 'https://www.insee.fr/fr/statistiques/8657156',
          publisher: 'Insee',
          date: '2025-10-23',
        },
      ],
    },
    {
      id: 'travail-pouvoir',
      kind: 'deep',
      questionIds: ['travail_salaires-1'],
      title: 'Comment gagner en pouvoir d’achat\u202f?',
      short: 'Pouvoir d’achat',
      register: 'vous',
      segments: [
        {
          id: 'travail-pouvoir-01',
          say: 'Comment acheter plus avec votre paie\u202f? Deux voies\u00a0: un salaire net plus élevé, ou des prix plus bas.',
          visual: 'hook',
          draw: 'Deux chemins au trait\u00a0: un billet qui monte d’une flèche, une étiquette de prix qui descend d’une flèche.',
          emphasis: ['Deux voies', 'salaire net plus élevé', 'prix plus bas'],
        },
        {
          id: 'travail-pouvoir-02',
          say: 'Chaque 1er\u00a0janvier, le Smic, le salaire minimum, suit la hausse des prix pour les 20\u00a0% de ménages les plus modestes. S’y ajoute la moitié du gain de pouvoir d’achat du salaire horaire moyen des ouvriers et employés.',
          spoken: 'Chaque premier janvier, le Smic, le salaire minimum, suit la hausse des prix pour les vingt pour cent de ménages les plus modestes. S’y ajoute la moitié du gain de pouvoir d’achat du salaire horaire moyen des ouvriers et employés.',
          visual: 'point',
          draw: 'Un calendrier ouvert au 1er janvier\u202f; dix maisons, dont deux comptées au bleu bille\u202f; un disque à moitié hachuré pour le gain de pouvoir d’achat.',
          alt: 'Dix maisons, dont deux comptées\u00a0: 20\u00a0% des ménages.',
          emphasis: ['1er\u00a0janvier', '20\u00a0%', 'la moitié'],
        },
        {
          id: 'travail-pouvoir-03',
          say: 'En cours d’année, il augmente tout seul dès que les prix ont monté de 2\u00a0% depuis la dernière hausse. Comme au 1er\u00a0juin 2026. Le gouvernement peut aussi décider un «\u00a0coup de pouce\u00a0».',
          spoken: 'En cours d’année, il augmente tout seul dès que les prix ont monté de deux pour cent depuis la dernière hausse. Comme au premier juin deux mille vingt-six. Le gouvernement peut aussi décider un « coup de pouce ».',
          visual: 'timeline',
          draw: 'Une ligne des mois de 2026\u00a0: la courbe des prix monte jusqu’à un seuil pointillé de 2\u00a0%\u202f; le Smic, au bleu bille, monte d’une marche au 1er juin\u202f; une petite flèche en pointillé pour le coup de pouce possible.',
          alt: 'Sur une ligne de janvier à l’été 2026, la courbe des prix et la marche du Smic, au 1er\u00a0janvier puis au 1er\u00a0juin.',
          emphasis: ['2\u00a0%', '1er\u00a0juin 2026', 'coup de pouce'],
        },
        {
          id: 'travail-pouvoir-04',
          say: 'À la hausse du 1er\u00a0novembre 2024, la dernière mesurée, 2,2\u00a0millions de salariés du privé hors agriculture étaient directement concernés. C’est 12,4\u00a0%, environ 1\u00a0sur 8.',
          spoken: 'À la hausse du premier novembre deux mille vingt-quatre, la dernière mesurée, deux virgule deux millions de salariés du privé hors agriculture étaient directement concernés. C’est douze virgule quatre pour cent, environ un sur huit.',
          visual: 'figure',
          draw: 'Huit silhouettes en rang\u202f; l’une se compte au bleu bille.',
          emphasis: ['2,2\u00a0millions', 'environ 1\u00a0sur 8'],
          figure: {
            value: '12,4\u00a0%',
            label: 'Part des salariés du privé non agricole directement concernés par la hausse du Smic du 1er\u00a0novembre 2024, soit 2,2\u00a0millions de personnes. C’est la dernière hausse mesurée par la Dares (France hors Mayotte, hors apprentis, stagiaires et intérimaires)',
            date: '1er\u00a0novembre 2024',
            sourceIndex: 1,
          },
        },
        {
          id: 'travail-pouvoir-05',
          say: 'Le Smic est à 12,31\u00a0euros bruts de l’heure. À temps plein, un peu plus de 1\u202f867\u00a0euros bruts par mois, près de 1\u202f478 nets.',
          spoken: 'Le Smic est à douze euros trente et un bruts de l’heure. À temps plein, un peu plus de mille huit cent soixante-sept euros bruts par mois, près de mille quatre cent soixante-dix-huit nets.',
          visual: 'figure',
          draw: 'Deux barres à la même échelle, depuis zéro\u00a0: le brut du mois, et le net, plus court\u202f; la différence en pointillé.',
          alt: 'Deux barres à la même échelle\u00a0: le brut et le net d’un mois au Smic à temps plein\u202f; la différence, en pointillé, ce sont les prélèvements.',
          emphasis: ['12,31\u00a0euros', 'près de 1\u202f478 nets'],
          figure: {
            value: '12,31\u00a0€',
            label: 'Smic horaire brut depuis le 1er\u00a0juin 2026, contre 12,02\u00a0€ avant (+2,41\u00a0%). Pour un temps plein\u00a0: 1\u202f867,02\u00a0€ brut et 1\u202f477,93\u00a0€ net par mois (France hors Mayotte)',
            date: '1er\u00a0juin 2026',
            sourceIndex: 2,
          },
          chart: {
            kind: 'compare',
            unit: '€',
            items: [
              { label: 'Brut par mois, temps plein', value: 1867.02 },
              { label: 'Net par mois, temps plein', value: 1477.93 },
            ],
          },
        },
        {
          id: 'travail-pouvoir-06',
          say: 'L’écart\u00a0: deux contributions sociales, CSG et CRDS, et des cotisations, surtout pour la retraite. Les baisser augmente le net, à coût égal pour l’employeur. Il faut alors compenser par d’autres recettes ou des économies.',
          spoken: 'L’écart : deux contributions sociales, C.S.G. et C.R.D.S., et des cotisations, surtout pour la retraite. Les baisser augmente le net, à coût égal pour l’employeur. Il faut alors compenser par d’autres recettes ou des économies.',
          visual: 'point',
          draw: 'Trois lignes d’effets\u00a0: le porte-monnaie qui grossit, la mallette de l’employeur inchangée, le guichet de la protection sociale qui perd une recette.',
          emphasis: ['CSG et CRDS', 'à coût égal', 'compenser'],
        },
        {
          id: 'travail-pouvoir-07',
          say: 'Et les prix\u202f? En principe, ils sont libres. Mais en cas de crise notamment, le gouvernement peut, par décret, contrer des hausses ou des baisses excessives dans un secteur. Pour six mois au plus.',
          visual: 'point',
          draw: 'Une étiquette de prix libre\u202f; puis une courbe de prix qui s’emballe, tenue entre deux traits pointillés le temps de six cases de mois.',
          emphasis: ['libres', 'six mois au plus'],
        },
        {
          id: 'travail-pouvoir-08',
          say: 'Une hausse du Smic pèse d’abord sur les employeurs. Une baisse des prélèvements, sur les finances publiques et sociales. Une baisse des prix, sur les producteurs, les distributeurs ou l’État. Alors, quel levier privilégier\u202f?',
          spoken: 'Une hausse du Smic pèse d’abord sur les employeurs. Une baisse des prélèvements, sur les finances publiques et sociales. Une baisse des prix, sur les producteurs, les distributeurs ou l’État. Alors, quel levier privilégier ?',
          visual: 'question',
          draw: 'Trois leviers côte à côte, le Smic, les prélèvements, les prix\u202f; sous chacun, une flèche vers qui le porte d’abord\u00a0: une mallette, un guichet, un immeuble.',
          emphasis: ['les employeurs', 'les finances publiques et sociales', 'quel levier'],
        },
      ],
      sources: [
        {
          title: 'Smic (salaire minimum interprofessionnel de croissance)',
          url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F2300',
          publisher: 'Service-public.gouv.fr (DILA)',
          date: '2026-06-01',
        },
        {
          title: 'La revalorisation du Smic au 1er\u00a0novembre 2024 (Dares Résultats n° 52)',
          url: 'https://dares.travail-emploi.gouv.fr/publication/la-revalorisation-du-smic-au-1er-novembre-2024',
          publisher: 'Dares (ministère du Travail)',
          date: '2025-10-29',
        },
        {
          title: 'Revalorisation annuelle du Smic au 1er\u00a0juin 2026',
          url: 'https://normandie.dreets.gouv.fr/Revalorisation-annuelle-du-SMIC-au-1er-juin-2026',
          publisher: 'DREETS Normandie (ministère du Travail et des Solidarités)',
          date: '2026-05-22',
        },
        {
          title: 'La CSG-CRDS',
          url: 'https://www.urssaf.fr/accueil/employeur/cotisations/liste-cotisations/csg-crds.html',
          publisher: 'Urssaf',
          date: '2026-02-12',
        },
        {
          title: 'Article L410-2 du code de commerce',
          url: 'https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000019798129',
          publisher: 'Légifrance',
          date: '2008-11-15',
        },
      ],
    },
    {
      id: 'travail-salaires',
      kind: 'deep',
      questionIds: ['travail_salaires-2'],
      title: 'Au-delà du Smic, les autres salaires',
      short: 'Autres salaires',
      register: 'vous',
      segments: [
        {
          id: 'travail-salaires-01',
          say: 'Le Smic augmente automatiquement. Mais les autres salaires, ceux qui sont au-dessus\u202f?',
          spoken: 'Le Smic augmente automatiquement. Mais les autres salaires, ceux qui sont au-dessus ?',
          visual: 'hook',
          draw: 'Un escalier de salaires\u00a0: la première marche, le Smic, monte d’elle-même au bleu bille\u202f; au-dessus, les marches attendent, un point d’interrogation sur la plus haute.',
          emphasis: ['automatiquement', 'les autres salaires'],
        },
        {
          id: 'travail-salaires-02',
          say: 'Ils se négocient entre syndicats et employeurs, dans les branches, c’est-à-dire les secteurs d’activité, et dans les entreprises. Et la loi interdit de les faire suivre automatiquement le Smic ou les prix.',
          spoken: 'Ils se négocient entre syndicats et employeurs, dans les branches, c’est-à-dire les secteurs d’activité, et dans les entreprises. Et la loi interdit de les faire suivre automatiquement le Smic ou les prix.',
          visual: 'point',
          draw: 'Deux silhouettes de part et d’autre d’un accord\u202f; à côté, un billet relié à une étiquette de prix par un lien barré.',
          emphasis: ['se négocient', 'la loi interdit'],
        },
        {
          id: 'travail-salaires-03',
          say: 'En 2022 et 2023, selon l’Insee, les hausses du Smic ont préservé le pouvoir d’achat du bas de l’échelle. L’inflation, la hausse des prix, rognait celui des salaires plus élevés.',
          spoken: 'En deux mille vingt-deux et deux mille vingt-trois, selon l’Insee, les hausses du Smic ont préservé le pouvoir d’achat du bas de l’échelle. L’inflation, la hausse des prix, rognait celui des salaires plus élevés.',
          visual: 'point',
          draw: 'Une échelle de barres de salaires\u00a0: la plus basse tient, soutenue par une flèche au bleu bille\u202f; le haut des autres se gomme en pointillé.',
          emphasis: ['bas de l’échelle', 'salaires plus élevés'],
        },
        {
          id: 'travail-salaires-04',
          say: 'Fin juin 2026, le salaire mensuel de base du privé avait augmenté de 2,0\u00a0% en un an. Les prix, de 1,7\u00a0%. Inflation déduite, un gain de 0,2\u00a0%.',
          spoken: 'Fin juin deux mille vingt-six, le salaire mensuel de base du privé avait augmenté de deux pour cent en un an. Les prix, de un virgule sept pour cent. Inflation déduite, un gain de zéro virgule deux pour cent.',
          visual: 'figure',
          draw: 'Deux barres à la même échelle, depuis zéro\u00a0: le salaire de base et les prix, presque aussi longues l’une que l’autre.',
          alt: 'Deux barres à la même échelle\u00a0: le salaire mensuel de base et les prix (hors tabac).',
          emphasis: ['2,0\u00a0%', '1,7\u00a0%', '0,2\u00a0%'],
          figure: {
            value: '+2,0\u00a0%',
            label: 'Hausse sur un an du salaire mensuel de base dans le privé, à fin juin 2026. Les prix (hors tabac) ont augmenté de 1,7\u00a0% sur la même période, soit un gain de 0,2\u00a0% une fois l’inflation déduite (France hors Mayotte, hors agriculture et particuliers employeurs)',
            date: '2e\u00a0trimestre 2026',
            sourceIndex: 2,
          },
          chart: {
            kind: 'compare',
            unit: '%',
            items: [
              { label: 'Salaire mensuel de base', value: 2 },
              { label: 'Prix (hors tabac)', value: 1.7 },
            ],
          },
        },
        {
          id: 'travail-salaires-05',
          say: 'Chaque branche a sa grille de salaires minimums. Quand le Smic monte, le bas de la grille peut passer dessous. Au 1er\u00a0juin 2026, le ministère du Travail le prévoyait pour 126\u00a0branches sur 179 suivies.',
          spoken: 'Chaque branche a sa grille de salaires minimums. Quand le Smic monte, le bas de la grille peut passer dessous. Au premier juin deux mille vingt-six, le ministère du Travail le prévoyait pour cent vingt-six branches sur cent soixante-dix-neuf suivies.',
          visual: 'figure',
          draw: 'Une grille de 179 petites cases, une par branche suivie\u202f; 126 se comptent au bleu bille.',
          alt: 'Une case par branche suivie par le ministère.',
          emphasis: ['126\u00a0branches sur 179'],
          figure: {
            value: '126 sur 179',
            label: 'Branches suivies par le ministère dont les salaires minimums devaient passer sous le Smic avec la hausse du 1er\u00a0juin 2026 (projection du ministère). Fin mai, 30 étaient sous le Smic du 1er\u00a0janvier 2026. Selon le ministère, ce phénomène est habituel après chaque hausse en cours d’année',
            date: '1er\u00a0juin 2026',
            sourceIndex: 3,
          },
          chart: { kind: 'part', value: 126, total: 179, whole: 'branches suivies' },
        },
        {
          id: 'travail-salaires-06',
          say: 'Selon le ministère, c’est habituel après chaque hausse en cours d’année. Le salaire versé, lui, reste au moins au Smic. Et syndicats et employeurs de la branche doivent ouvrir des négociations dans les 45\u00a0jours.',
          spoken: 'Selon le ministère, c’est habituel après chaque hausse en cours d’année. Le salaire versé, lui, reste au moins au Smic. Et syndicats et employeurs de la branche doivent ouvrir des négociations dans les quarante-cinq jours.',
          visual: 'point',
          draw: 'Le bas de la grille passe sous le trait du Smic, mais le salaire versé reste posé sur le trait\u202f; à côté, un calendrier de 45 jours.',
          emphasis: ['au moins au Smic', '45\u00a0jours'],
        },
        {
          id: 'travail-salaires-07',
          say: 'Alors, quelle place pour la loi, et quelle place pour la négociation entre syndicats et employeurs\u202f?',
          visual: 'question',
          draw: 'Un texte de loi et un accord signé, côte à côte, à la même taille\u202f; un point d’interrogation entre les deux.',
          emphasis: ['la loi', 'la négociation'],
        },
      ],
      sources: [
        {
          title: 'Article L112-2 du code monétaire et financier',
          url: 'https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000024039949',
          publisher: 'Légifrance',
          date: '2011-05-19',
        },
        {
          title: 'Insee Première n° 2079 – Salaires dans le secteur privé en 2024 (23 octobre 2025)',
          url: 'https://www.insee.fr/fr/statistiques/8657156',
          publisher: 'Insee',
          date: '2025-10-23',
        },
        {
          title: 'Évolution des salaires de base dans le secteur privé\u00a0: résultats définitifs du 2e\u00a0trimestre 2026 (Dares Indicateurs n° 40)',
          url: 'https://dares.travail-emploi.gouv.fr/publication/evolution-des-salaires-de-base-dans-le-secteur-prive-resultats-definitifs-du-T2-2026',
          publisher: 'Dares (ministère du Travail)',
          date: '2026-09-25',
        },
        {
          title: 'Comité de suivi de la négociation salariale de branches du 27 mai 2026',
          url: 'https://travail-emploi.gouv.fr/comite-de-suivi-de-la-negociation-salariale-de-branches-du-27-mai-2026',
          publisher: 'Ministère du Travail et des Solidarités',
          date: '2026-05-27',
        },
      ],
    },
    {
      id: 'travail-partage',
      kind: 'deep',
      questionIds: ['travail_salaires-3'],
      title: 'Partager les bénéfices des entreprises',
      short: 'Partage des bénéfices',
      register: 'vous',
      segments: [
        {
          id: 'travail-partage-01',
          say: 'Une entreprise fait des bénéfices. Quelle part en revient à ceux qui y travaillent\u202f?',
          visual: 'hook',
          draw: 'Un immeuble d’entreprise, une pile de pièces devant\u202f; une flèche en pointillé vers trois silhouettes, et un point d’interrogation.',
          emphasis: ['des bénéfices', 'Quelle part'],
        },
        {
          id: 'travail-partage-02',
          say: 'La participation aux bénéfices est obligatoire dès 50\u00a0salariés. Depuis 2025, de 11 à 49\u00a0salariés aussi, il faut partager la valeur. À une condition\u00a0: trois ans de suite, un bénéfice d’au moins 1\u00a0% du chiffre d’affaires.',
          spoken: 'La participation aux bénéfices est obligatoire dès cinquante salariés. Depuis deux mille vingt-cinq, de onze à quarante-neuf salariés aussi, il faut partager la valeur. À une condition : trois ans de suite, un bénéfice d’au moins un pour cent du chiffre d’affaires.',
          visual: 'point',
          draw: 'Une règle des tailles d’entreprise\u00a0: à partir de 50 salariés, un trait plein\u202f; de 11 à 49, un trait au bleu bille, depuis 2025.',
          alt: 'Une ligne des tailles d’entreprise, en nombre de salariés\u00a0: 11, 49 et 50.',
          emphasis: ['dès 50\u00a0salariés', 'de 11 à 49\u00a0salariés'],
        },
        {
          id: 'travail-partage-03',
          say: 'Participation, intéressement, épargne salariale\u00a0: en 2024, 54,0\u00a0% des salariés du privé hors agriculture étaient couverts par au moins l’un d’eux. 46,0\u00a0% ont reçu une prime.',
          spoken: 'Participation, intéressement, épargne salariale : en deux mille vingt-quatre, cinquante-quatre pour cent des salariés du privé hors agriculture étaient couverts par au moins l’un d’eux. Quarante-six pour cent ont reçu une prime.',
          visual: 'figure',
          draw: 'Cent petits carrés\u00a0: 54 au bleu bille, couverts\u202f; parmi eux, 46 en bleu plein, une prime reçue.',
          alt: 'Cent carrés\u00a0: 54 couverts, dont 46 ont reçu une prime.',
          emphasis: ['54,0\u00a0%', '46,0\u00a0%'],
          figure: {
            value: '54,0\u00a0%',
            label: 'Part des salariés du privé non agricole couverts en 2024 par au moins un dispositif (participation, intéressement ou plan d’épargne salariale). 46,0\u00a0% ont effectivement reçu une prime (France hors Mayotte)',
            date: '2024',
            sourceIndex: 1,
          },
          chart: { kind: 'part', value: 54, total: 100, unit: '%', whole: 'des salariés du privé non agricole' },
        },
        {
          id: 'travail-partage-04',
          say: 'Côté entreprises, le taux de marge\u00a0: la part de la richesse créée qui leur reste, une fois payés salaires et impôts sur la production. Pour les sociétés non financières, 32,2\u00a0% en 2025.',
          spoken: 'Côté entreprises, le taux de marge : la part de la richesse créée qui leur reste, une fois payés salaires et impôts sur la production. Pour les sociétés non financières, trente-deux virgule deux pour cent en deux mille vingt-cinq.',
          visual: 'figure',
          draw: 'Un disque, la richesse créée\u202f; une part d’un peu moins d’un tiers se compte au bleu bille, ce qui reste aux entreprises.',
          emphasis: ['le taux de marge', '32,2\u00a0%'],
          figure: {
            value: '32,2\u00a0%',
            label: 'Taux de marge des sociétés non financières en 2025 (32,7\u00a0% en 2024). C’est la part de leur valeur ajoutée qui leur reste une fois payés les salariés et les impôts sur la production, en comptant les subventions d’exploitation reçues',
            date: '2025',
            sourceIndex: 2,
          },
          chart: { kind: 'part', value: 32.2, total: 100, unit: '%', whole: 'de leur valeur ajoutée' },
        },
        {
          id: 'travail-partage-05',
          say: 'Et dans les décisions\u202f? Dès 1\u202f000\u00a0salariés en France, ou 5\u202f000 avec l’étranger, une société doit avoir des représentants des salariés à son conseil d’administration. Au moins un, et au moins deux au-delà de huit autres membres.',
          spoken: 'Et dans les décisions ? Dès mille salariés en France, ou cinq mille avec l’étranger, une société doit avoir des représentants des salariés à son conseil d’administration. Au moins un, et au moins deux au-delà de huit autres membres.',
          visual: 'point',
          draw: 'Une longue table au trait, neuf membres autour\u202f; deux sièges se comptent au bleu bille, les représentants des salariés.',
          alt: 'Autour de la table, neuf autres membres et deux représentants des salariés.',
          emphasis: ['conseil d’administration', 'Au moins un'],
        },
        {
          id: 'travail-partage-06',
          say: 'En 2024, la moitié des salariés du privé gagnaient moins de 2\u202f190\u00a0euros nets par mois, en équivalent temps plein. Et 1\u00a0%, plus de 10\u202f261\u00a0euros.',
          spoken: 'En deux mille vingt-quatre, la moitié des salariés du privé gagnaient moins de deux mille cent quatre-vingt-dix euros nets par mois, en équivalent temps plein. Et un pour cent, plus de dix mille deux cent soixante et un euros.',
          visual: 'figure',
          draw: 'Deux barres à la même échelle, depuis zéro\u00a0: le seuil de la moitié des salariés, et celui des 1\u00a0% les mieux payés.',
          alt: 'Deux barres à la même échelle\u00a0: le seuil de la moitié des salariés et celui des 1\u00a0% les mieux payés.',
          emphasis: ['2\u202f190\u00a0euros', '10\u202f261\u00a0euros'],
          figure: {
            value: '10\u202f261\u00a0€',
            label: 'Salaire net mensuel en équivalent temps plein au-dessus duquel se situent les 1\u00a0% de salariés du privé les mieux payés en 2024, soit 7,3\u00a0fois le Smic. La moitié des salariés gagne moins de 2\u202f190\u00a0€ (France y compris Mayotte, apprentis et stagiaires compris, hors agriculture et particuliers employeurs)',
            date: '2024',
            sourceIndex: 4,
          },
          chart: {
            kind: 'compare',
            unit: '€',
            items: [
              { label: 'Seuil des 1 % les mieux payés', value: 10261 },
              { label: 'Seuil de la moitié des salariés', value: 2190 },
            ],
          },
        },
        {
          id: 'travail-partage-07',
          say: 'Aucune loi ne plafonne ces écarts dans le privé. Profits, décisions, écarts de salaires\u00a0: quel partage entre l’entreprise et ceux qui y travaillent\u202f?',
          visual: 'question',
          draw: 'Une première phrase écrite quand la voix la dit\u00a0; dessous, l’immeuble d’entreprise et trois silhouettes, de part et d’autre d’une pile de pièces\u202f; un point d’interrogation au-dessus.',
          emphasis: ['Aucune loi', 'quel partage'],
        },
      ],
      sources: [
        {
          title: 'Participation',
          url: 'https://entreprendre.service-public.gouv.fr/vosdroits/F2141',
          publisher: 'Service-public.gouv.fr Entreprendre (DILA)',
          date: '2026-07-21',
        },
        {
          title: 'L’épargne salariale en 2024 (Dares Résultats n° 23)',
          url: 'https://dares.travail-emploi.gouv.fr/publication/lepargne-salariale-en-2024',
          publisher: 'Dares (ministère du Travail)',
          date: '2026-06-10',
        },
        {
          title: 'Les comptes de la Nation en 2025 (Insee Première n° 2105)',
          url: 'https://www.insee.fr/fr/statistiques/8996855?sommaire=8071406',
          publisher: 'Insee',
          date: '2026-05-29',
        },
        {
          title: 'Article L225-27-1 du code de commerce',
          url: 'https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000042339592',
          publisher: 'Légifrance',
          date: '2021-01-01',
        },
        {
          title: 'Insee Première n° 2079 – Salaires dans le secteur privé en 2024 (23 octobre 2025)',
          url: 'https://www.insee.fr/fr/statistiques/8657156',
          publisher: 'Insee',
          date: '2025-10-23',
        },
        {
          title: 'Décret n° 53-707 du 9 août 1953, article 3 (modifié par le décret n° 2012-915 du 26 juillet 2012)',
          url: 'https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000026228693',
          publisher: 'Légifrance',
          date: '2012-07-28',
        },
      ],
    },
    {
      id: 'travail-droits',
      kind: 'deep',
      questionIds: ['travail_salaires-4'],
      title: 'Quels droits pour les salariés\u202f?',
      short: 'Droits des salariés',
      register: 'vous',
      segments: [
        {
          id: 'travail-droits-01',
          say: 'Votre licenciement est jugé injustifié. Combien pouvez-vous obtenir\u202f?',
          visual: 'hook',
          draw: 'Une lettre au trait\u202f; à côté, quelques pièces et un point d’interrogation.',
          emphasis: ['jugé injustifié', 'Combien'],
        },
        {
          id: 'travail-droits-02',
          say: 'Depuis 2017, le juge suit un barème. De 1 à 2\u00a0mois de salaire brut pour un an d’ancienneté\u202f; de 3 à 20\u00a0mois dès 29\u00a0ans d’ancienneté.',
          spoken: 'Depuis deux mille dix-sept, le juge suit un barème. D’un à deux mois de salaire brut pour un an d’ancienneté ; de trois à vingt mois dès vingt-neuf ans d’ancienneté.',
          visual: 'point',
          draw: 'Une ligne de l’ancienneté, d’un an à 29\u00a0ans\u202f; au-dessus de chaque repère, une fourchette de mois de salaire, étroite au début, haute à la fin.',
          alt: 'Sur une ligne de l’ancienneté, deux fourchettes\u00a0: à un an, de 1 à 2\u00a0mois\u202f; à 29\u00a0ans, de 3 à 20\u00a0mois.',
          emphasis: ['un barème', '1 à 2\u00a0mois', '3 à 20\u00a0mois'],
        },
        {
          id: 'travail-droits-03',
          say: 'Pas de barème pour un licenciement nul, par exemple pour harcèlement ou discrimination. L’indemnité est alors d’au moins 6\u00a0mois de salaire.',
          spoken: 'Pas de barème pour un licenciement nul, par exemple pour harcèlement ou discrimination. L’indemnité est alors d’au moins six mois de salaire.',
          visual: 'point',
          draw: 'Six cases de mois au bleu bille, et une flèche en pointillé qui part plus loin\u00a0: au moins six.',
          emphasis: ['licenciement nul', 'au moins 6\u00a0mois'],
        },
        {
          id: 'travail-droits-04',
          say: 'Depuis 2017 aussi, l’accord d’entreprise prime sur l’accord de branche dans la plupart des domaines, qu’il soit plus ou moins favorable aux salariés. La branche prévaut dans 13\u00a0domaines, dont les salaires minimums.',
          spoken: 'Depuis deux mille dix-sept aussi, l’accord d’entreprise prime sur l’accord de branche dans la plupart des domaines, qu’il soit plus ou moins favorable aux salariés. La branche prévaut dans treize domaines, dont les salaires minimums.',
          visual: 'point',
          draw: 'Deux feuilles d’accord\u00a0: celle de l’entreprise posée devant celle de la branche\u202f; sur la feuille de branche, treize cases restent visibles.',
          emphasis: ['l’accord d’entreprise', '13\u00a0domaines'],
        },
        {
          id: 'travail-droits-05',
          say: 'Les syndicats\u00a0: en 2019, dernière mesure disponible, 10,3\u00a0% des salariés y adhéraient. 7,8\u00a0% dans le privé, 18,4\u00a0% dans la fonction publique.',
          spoken: 'Les syndicats : en deux mille dix-neuf, dernière mesure disponible, dix virgule trois pour cent des salariés y adhéraient. Sept virgule huit pour cent dans le privé, dix-huit virgule quatre pour cent dans la fonction publique.',
          visual: 'figure',
          draw: 'Trois barres à la même échelle, depuis zéro\u00a0: tous les salariés, le privé, la fonction publique.',
          alt: 'Trois barres à la même échelle\u00a0: tous les salariés, dans le privé, dans la fonction publique.',
          emphasis: ['10,3\u00a0%', '7,8\u00a0%', '18,4\u00a0%'],
          figure: {
            value: '10,3\u00a0%',
            label: 'Part des salariés adhérant à un syndicat en 2019\u00a0: 7,8\u00a0% dans le privé, 18,4\u00a0% dans la fonction publique. C’est la dernière mesure disponible (France hors Mayotte)',
            date: '2019',
            sourceIndex: 2,
          },
          chart: {
            kind: 'compare',
            unit: '%',
            items: [
              { label: 'Tous les salariés', value: 10.3 },
              { label: 'Dans le privé', value: 7.8 },
              { label: 'Dans la fonction publique', value: 18.4 },
            ],
          },
        },
        {
          id: 'travail-droits-06',
          say: 'La santé au travail. En 2024, au régime général, 1\u202f805 affections psychiques, surtout des dépressions, ont été prises en charge comme maladies professionnelles. Contre 840 en 2020.',
          spoken: 'La santé au travail. En deux mille vingt-quatre, au régime général, mille huit cent cinq affections psychiques, surtout des dépressions, ont été prises en charge comme maladies professionnelles. Contre huit cent quarante en deux mille vingt.',
          visual: 'figure',
          draw: 'Deux colonnes depuis zéro, 2020 et 2024\u202f; la seconde plus de deux fois plus haute.',
          emphasis: ['1\u202f805', '840'],
          figure: {
            value: '1\u202f805',
            label: 'Affections psychiques liées au travail, surtout des dépressions, prises en charge comme maladies professionnelles en 2024 (régime général), contre 840 en 2020. Aucun tableau de maladies professionnelles ne les prévoit, pas plus que l’épuisement professionnel\u00a0: un comité régional les examine au cas par cas et exige une incapacité permanente d’au moins 25\u00a0% (ou un décès) et un lien «\u00a0direct et essentiel\u00a0» avec le travail',
            date: '2024',
            sourceIndex: 3,
          },
          chart: {
            kind: 'series',
            items: [
              { label: '2020', value: 840 },
              { label: '2024', value: 1805 },
            ],
          },
        },
        {
          id: 'travail-droits-07',
          say: 'Les contrats courts, enfin. En 2025, CDD, contrats à durée déterminée, et intérim font 9,4\u00a0% de l’emploi. Une part en baisse depuis 2023.',
          spoken: 'Les contrats courts, enfin. En deux mille vingt-cinq, C.D.D., contrats à durée déterminée, et intérim font neuf virgule quatre pour cent de l’emploi. Une part en baisse depuis deux mille vingt-trois.',
          visual: 'figure',
          draw: 'Un disque, tout l’emploi\u202f; une fine part au bleu bille, les CDD et l’intérim.',
          emphasis: ['9,4\u00a0%'],
          figure: {
            value: '9,4\u00a0%',
            label: 'Part des CDD et de l’intérim dans l’emploi total en 2025. Elle baisse depuis 2023 et se situe 0,9\u00a0point sous son niveau d’avant la crise sanitaire (France, hors personnes vivant en collectivité)',
            date: '2025',
            sourceIndex: 4,
          },
          chart: { kind: 'part', value: 9.4, total: 100, unit: '%', whole: 'de l’emploi total' },
        },
        {
          id: 'travail-droits-08',
          say: 'Depuis 2022, dans six secteurs, un bonus-malus s’applique aux employeurs d’au moins 11\u00a0salariés. Leur contribution chômage va de 2,95 à 5\u00a0%, au lieu de 4\u00a0%.',
          spoken: 'Depuis deux mille vingt-deux, dans six secteurs, un bonus-malus s’applique aux employeurs d’au moins onze salariés. Leur contribution chômage va de deux virgule quatre-vingt-quinze à cinq pour cent, au lieu de quatre pour cent.',
          visual: 'point',
          draw: 'Une réglette graduée de 2,95 à 5\u00a0%, un curseur posé à 4\u00a0%\u202f; deux flèches, l’une vers le bas, l’autre vers le haut.',
          emphasis: ['bonus-malus', '2,95 à 5\u00a0%'],
        },
        {
          id: 'travail-droits-09',
          say: 'Elle dépend du nombre de leurs fins de contrat suivies d’une inscription à France Travail, comparé à celui de leur secteur. Protection des salariés d’un côté, marge de manœuvre des employeurs de l’autre\u00a0: où placer l’équilibre\u202f?',
          visual: 'question',
          draw: 'D’abord, des fins de contrat qui mènent à un guichet, leur nombre comparé à celui du secteur\u00a0; puis une balance au fléau horizontal\u00a0: un parapluie au-dessus d’une silhouette sur un plateau, une mallette sur l’autre.',
          emphasis: ['Protection des salariés', 'marge de manœuvre des employeurs'],
        },
      ],
      sources: [
        {
          title: 'Article L1235-3 du code du travail',
          url: 'https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000036762052',
          publisher: 'Légifrance',
          date: '2018-04-01',
        },
        {
          title: 'Code du travail, articles L2253-1 à L2253-4 (rapports entre accords d’entreprise et accords de branche)',
          url: 'https://www.legifrance.gouv.fr/codes/section_lc/LEGITEXT000006072050/LEGISCTA000006177936',
          publisher: 'Légifrance',
          date: '2018-04-01',
        },
        {
          title: 'Léger repli de la syndicalisation en France entre 2013 et 2019 (Dares Analyses n° 6)',
          url: 'https://dares.travail-emploi.gouv.fr/publication/leger-repli-de-la-syndicalisation-en-france-entre-2013-et-2019',
          publisher: 'Dares (ministère du Travail)',
          date: '2023-02-01',
        },
        {
          title: 'Rapport annuel 2024 de l’Assurance Maladie – Risques professionnels (p. 47, 50 et 152)',
          url: 'https://www.assurance-maladie.ameli.fr/sites/default/files/rapport_annuel_2024_de_lassurance_maladie_-_risques_professionnels_novembre_2025.pdf',
          publisher: 'Assurance Maladie – Risques professionnels',
          date: '2025-11',
        },
        {
          title: 'Une photographie du marché du travail en 2025 (Insee Première n° 2096)',
          url: 'https://www.insee.fr/fr/statistiques/8901327',
          publisher: 'Insee',
          date: '2026-03-25',
        },
        {
          title: 'Le bonus-malus assurance chômage',
          url: 'https://travail-emploi.gouv.fr/le-bonus-malus-assurance-chomage',
          publisher: 'Ministère du Travail et des Solidarités',
          date: '2026-06-11',
        },
      ],
    },
    {
      id: 'travail-temps',
      kind: 'deep',
      questionIds: ['travail_salaires-x1'],
      title: 'Le temps de travail, combien et comment\u202f?',
      short: 'Temps de travail',
      register: 'vous',
      segments: [
        {
          id: 'travail-temps-01',
          say: '35\u00a0heures par semaine\u00a0: c’est la durée légale du travail. Mais est-ce un plafond\u202f?',
          spoken: 'Trente-cinq heures par semaine : c’est la durée légale du travail. Mais est-ce un plafond ?',
          visual: 'hook',
          draw: 'Une semaine de cinq jours au trait, remplie jusqu’à un trait des 35 heures\u202f; un point d’interrogation sur ce trait.',
          emphasis: ['35\u00a0heures', 'un plafond'],
        },
        {
          id: 'travail-temps-02',
          say: 'Non\u00a0: c’est le seuil des heures supplémentaires. Sans accord, elles sont payées 25\u00a0% de plus de la 36e à la 43e\u00a0heure, puis 50\u00a0% de plus. Un accord peut fixer d’autres taux, d’au moins 10\u00a0%.',
          spoken: 'Non : c’est le seuil des heures supplémentaires. Sans accord, elles sont payées vingt-cinq pour cent de plus de la trente-sixième à la quarante-troisième heure, puis cinquante pour cent de plus. Un accord peut fixer d’autres taux, d’au moins dix pour cent.',
          visual: 'point',
          draw: 'Une réglette des heures de la semaine\u00a0: un trait au seuil de 35\u202f; de la 36e à la 43e heure, une bande au bleu bille clair, +25\u00a0%\u202f; au-delà, une bande plus soutenue, +50\u00a0%.',
          alt: 'Sur une réglette des heures de la semaine\u00a0: le seuil de 35\u00a0heures, puis +25\u00a0% de la 36e à la 43e\u00a0heure, et +50\u00a0% au-delà.',
          emphasis: ['le seuil', '25\u00a0%', '50\u00a0%'],
        },
        {
          id: 'travail-temps-03',
          say: 'Ces heures sont exonérées d’impôt sur le revenu jusqu’à 7\u202f500\u00a0euros par an. Et l’employeur déduit de ses cotisations 1,50\u00a0euro par heure supplémentaire sous 20\u00a0salariés, 0,50\u00a0euro au-delà.',
          spoken: 'Ces heures sont exonérées d’impôt sur le revenu jusqu’à sept mille cinq cents euros par an. Et l’employeur déduit de ses cotisations un euro cinquante par heure supplémentaire sous vingt salariés, cinquante centimes au-delà.',
          visual: 'figure',
          draw: 'Un avis d’impôt avec son plafond d’exonération\u202f; une pièce par heure supplémentaire qui revient vers l’employeur.',
          emphasis: ['7\u202f500\u00a0euros', '1,50\u00a0euro'],
          figure: {
            value: '1,50\u00a0€',
            label: 'Somme que l’employeur déduit de ses cotisations patronales pour chaque heure supplémentaire dans une entreprise de moins de 20\u00a0salariés (0,50\u00a0€ à partir de 20\u00a0salariés)',
            date: '2026',
            sourceIndex: 1,
          },
        },
        {
          id: 'travail-temps-04',
          say: 'Prenons les salariés du privé à temps complet dont le temps est compté en heures. En 2025, 54\u00a0% ont fait au moins une heure supplémentaire. Ceux-là en ont fait 103 en moyenne.',
          spoken: 'Prenons les salariés du privé à temps complet dont le temps est compté en heures. En deux mille vingt-cinq, cinquante-quatre pour cent ont fait au moins une heure supplémentaire. Ceux-là en ont fait cent trois en moyenne.',
          visual: 'figure',
          draw: 'Cent petits carrés\u202f; 54 se comptent au bleu bille.',
          emphasis: ['54\u00a0%', '103'],
          figure: {
            value: '54\u00a0%',
            label: 'Part des salariés du privé à temps complet, dont le temps est compté en heures, qui ont fait au moins une heure supplémentaire rémunérée en 2025. Ceux qui en ont fait en ont effectué 103 en moyenne (France hors Mayotte, hors intérim)',
            date: '2025',
            sourceIndex: 2,
          },
          chart: { kind: 'part', value: 54, total: 100, unit: '%', whole: 'des salariés au temps compté en heures' },
        },
        {
          id: 'travail-temps-05',
          say: 'En 2025, 16,0\u00a0% des salariés du privé à temps complet comptaient leur temps en jours. En 2024, ils ont travaillé 1\u202f821\u00a0heures en moyenne. Contre 1\u202f613 pour ceux comptés en heures.',
          spoken: 'En deux mille vingt-cinq, seize pour cent des salariés du privé à temps complet comptaient leur temps en jours. En deux mille vingt-quatre, ils ont travaillé mille huit cent vingt et une heures en moyenne. Contre mille six cent treize pour ceux comptés en heures.',
          visual: 'figure',
          draw: 'Deux barres à la même échelle, depuis zéro\u00a0: les heures de l’année quand le temps se compte en jours, et quand il se compte en heures.',
          alt: 'Deux barres à la même échelle, les heures travaillées dans l’année, en 2024\u00a0: temps compté en jours, temps compté en heures.',
          emphasis: ['16,0\u00a0%', '1\u202f821\u00a0heures', '1\u202f613'],
          figure: {
            value: '16,0\u00a0%',
            label: 'Part des salariés du privé à temps complet au forfait annuel en jours en 2025 (2,5\u00a0millions de personnes). Leur temps de travail se compte en jours (218 au maximum par an), et non en heures\u00a0: les 35\u00a0heures ne s’appliquent pas à eux',
            date: '2025',
            sourceIndex: 3,
          },
          chart: { kind: 'part', value: 16, total: 100, unit: '%', whole: 'des salariés du privé à temps complet' },
        },
        {
          id: 'travail-temps-06',
          say: 'La journée de travail est limitée à 10\u00a0heures, sauf dérogation. Faire 35\u00a0heures en quatre jours suppose donc des journées de 8\u00a0h\u00a045. Alors, combien d’heures travailler, et comment les organiser\u202f?',
          spoken: 'La journée de travail est limitée à dix heures, sauf dérogation. Faire trente-cinq heures en quatre jours suppose donc des journées de huit heures quarante-cinq. Alors, combien d’heures travailler, et comment les organiser ?',
          visual: 'question',
          draw: 'Quatre colonnes de jours remplies jusqu’à 8\u00a0h\u00a045, sous un plafond hachuré à 10\u00a0heures\u202f; puis la question.',
          emphasis: ['10\u00a0heures', 'quatre jours', '8\u00a0h\u00a045'],
        },
      ],
      sources: [
        {
          title: 'Heures supplémentaires d’un salarié du secteur privé',
          url: 'https://www.service-public.gouv.fr/particuliers/vosdroits/F2391',
          publisher: 'Service-public.gouv.fr (DILA)',
          date: '2026-06-08',
        },
        {
          title: 'Déduction forfaitaire patronale',
          url: 'https://www.urssaf.fr/accueil/employeur/beneficier-exonerations/exonerations-heures/deduction-forfaitaire-patronale.html',
          publisher: 'Urssaf',
          date: '2026-01-09',
        },
        {
          title: 'Les heures supplémentaires (données)',
          url: 'https://dares.travail-emploi.gouv.fr/donnees/les-heures-supplementaires',
          publisher: 'Dares (ministère du Travail)',
          date: '2026-07-10',
        },
        {
          title: 'Les salariés au forfait en jours (séries longues)',
          url: 'https://dares.travail-emploi.gouv.fr/donnees/les-salaries-au-forfait-en-jours',
          publisher: 'Dares (ministère du Travail)',
          date: '2026-07-16',
        },
        {
          title: 'Qui sont les salariés au forfait en jours et comment leur travail s’organise-t-il\u202f? (Dares Analyses n° 20)',
          url: 'https://dares.travail-emploi.gouv.fr/publication/qui-sont-les-salaries-au-forfait-en-jours-et-comment-leur-travail-sorganise-t-il',
          publisher: 'Dares (ministère du Travail)',
          date: '2026-05-12',
        },
        {
          title: 'Article L3121-18 du code du travail',
          url: 'https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000033020428',
          publisher: 'Légifrance',
          date: '2016-08-10',
        },
      ],
    },
  ],
}
